### ISSUE TITLE
tensile_test visualization

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#103]
Hi,

I am wondering how to extract data from tensile_test. It appears that the outputs from "Compute Class Parameters" are not shown in ParaView, such as the "Strain Gage Top Initial Position" and "Top Reaction Force", while the other outputs like Displacement, Velocity, Element_Id can be visualized in ParaView.

**Comment by djlittl** [comment]
You can see them in Paraview if you apply one of the filters for global variables. "Plot Global Variables Over Time" should work.  You could also write a python script and use the exodus.py module.
