### ISSUE TITLE
Peridigm make failed. Makefile:140: recipe for target 'all' failed

### ISSUE THREAD

**Issue by bb515** [peridigm/peridigm#106]
Hello, new to this, help would be very much appreciated!

Tried compiling Peridigm:

rm -f CMakeCache.txt

`
cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Trilinos_DIR:PATH=/usr/local/bin/trilinos-12.4.2/lib/cmake/Trilinos/ \
-D CMAKE_C_COMPILER:STRING=/usr/local/bin/mpicc \
-D CMAKE_CXX_COMPILER:STRING=/usr/local/bin/mpicxx \
-D BOOST_ROOT=/usr/local/lib/ \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
/home/ben/Downloads/peridigm
`

I suspect it is an issue with my Trilinos build? When I was compiling Trilinos, I had to add
-D Trilinos_ENABLE_TESTS:BOOL=OFF \
so that it would successfully compile.

fyi I have closely been following these install instructions https://pdfs.semanticscholar.org/85cd/61b50b63eb0936169923b26d9efffe5a2e8b.pdf

Output is:

`[ 53%] Building CXX object src/CMakeFiles/Peridigm.dir/core/Peridigm_Main.cpp.o
[ 54%] Linking CXX executable Peridigm
libPeridigmLib.a(Peridigm.cpp.o): In function `PeridigmNS::Peridigm::Peridigm(int const&, Teuchos::RCP<Teuchos::ParameterList>, Teuchos::RCP<PeridigmNS::Discretization>)':
Peridigm.cpp:(.text+0x11c40): undefined reference to `Epetra_MpiComm::Epetra_MpiComm(int)'
/usr/local/bin/trilinos-12.4.2/lib/libnox.a(NOX_Utils.C.o): In function `NOX::Utils::reset(Teuchos::ParameterList&)':
NOX_Utils.C:(.text+0x3caf): undefined reference to `ompi_mpi_comm_world'
/usr/local/bin/trilinos-12.4.2/lib/libml.a(ml_agg_METIS.c.o): In function `ML_Aggregate_CoarsenMETIS':
ml_agg_METIS.c:(.text+0xf5e): undefined reference to `ompi_mpi_op_sum'
ml_agg_METIS.c:(.text+0xf66): undefined reference to `ompi_mpi_int'
ml_agg_METIS.c:(.text+0x12be): undefined reference to `ompi_mpi_op_sum'
ml_agg_METIS.c:(.text+0x12c5): undefined reference to `ompi_mpi_int'
ml_agg_METIS.c:(.text+0x12f9): undefined reference to `ompi_mpi_op_sum'
ml_agg_METIS.c:(.text+0x1300): undefined reference to `ompi_mpi_int'
ml_agg_METIS.c:(.text+0x2dbc): undefined reference to `ompi_mpi_op_sum'
ml_agg_METIS.c:(.text+0x2dc7): undefined reference to `ompi_mpi_int'
ml_agg_METIS.c:(.text+0x32a2): undefined reference to `ompi_mpi_op_sum'
ml_agg_METIS.c:(.text+0x32ad): undefined reference to `ompi_mpi_int'
/usr/local/bin/trilinos-12.4.2/lib/libml.a(ml_agg_METIS.c.o): In function `ML_DecomposeGraph_BuildOffsets':
ml_agg_METIS.c:(.text+0x382b): undefined reference to `ompi_mpi_int'
/usr/local/bin/trilinos-12.4.2/lib/libepetraext.a(EpetraExt_MMHelpers.cpp.o): In function `void EpetraExt::boundary_exchange<int>(Epetra_MpiComm, ompi_datatype_t*, int, int const*, int const*, int*, int, int const*, int const*, int*, int, int) [clone .constprop.444]':
EpetraExt_MMHelpers.cpp:(.text+0x257): undefined reference to `ompi_mpi_int'
EpetraExt_MMHelpers.cpp:(.text+0x2af): undefined reference to `ompi_mpi_int'
/usr/local/bin/trilinos-12.4.2/lib/libepetraext.a(EpetraExt_MMHelpers.cpp.o): In function `void EpetraExt::LightweightCrsMatrix::Construct<EpetraExt::RemoteOnlyImport, int>(Epetra_CrsMatrix const&, EpetraExt::RemoteOnlyImport&, bool, char const*)':
EpetraExt_MMHelpers.cpp:(.text._ZN9EpetraExt20LightweightCrsMatrix9ConstructINS_16RemoteOnlyImportEiEEvRK16Epetra_CrsMatrixRT_bPKc[_ZN9EpetraExt20LightweightCrsMatrix9ConstructINS_16RemoteOnlyImportEiEEvRK16Epetra_CrsMatrixRT_bPKc]+0x4f3): undefined reference to `ompi_mpi_char'
EpetraExt_MMHelpers.cpp:(.text._ZN9EpetraExt20LightweightCrsMatrix9ConstructINS_16RemoteOnlyImportEiEEvRK16Epetra_CrsMatrixRT_bPKc[_ZN9EpetraExt20LightweightCrsMatrix9ConstructINS_16RemoteOnlyImportEiEEvRK16Epetra_CrsMatrixRT_bPKc]+0x682): undefined reference to `ompi_mpi_int'
/usr/local/bin/trilinos-12.4.2/lib/libepetraext.a(EpetraExt_MMHelpers.cpp.o): In function `void EpetraExt::LightweightCrsMatrix::Construct<Epetra_Import, int>(Epetra_CrsMatrix const&, Epetra_Import&, bool, char const*)':
EpetraExt_MMHelpers.cpp:(.text._ZN9EpetraExt20LightweightCrsMatrix9ConstructI13Epetra_ImportiEEvRK16Epetra_CrsMatrixRT_bPKc[_ZN9EpetraExt20LightweightCrsMatrix9ConstructI13Epetra_ImportiEEvRK16Epetra_CrsMatrixRT_bPKc]+0x518): undefined reference to `ompi_mpi_char'
EpetraExt_MMHelpers.cpp:(.text._ZN9EpetraExt20LightweightCrsMatrix9ConstructI13Epetra_ImportiEEvRK16Epetra_CrsMatrixRT_bPKc[_ZN9EpetraExt20LightweightCrsMatrix9ConstructI13Epetra_ImportiEEvRK16Epetra_CrsMatrixRT_bPKc]+0x6b1): undefined reference to `ompi_mpi_int'
/usr/local/bin/trilinos-12.4.2/lib/libepetraext.a(EpetraExt_MMHelpers.cpp.o): In function `void EpetraExt::LightweightCrsMatrix::Construct<EpetraExt::RemoteOnlyImport, long long>(Epetra_CrsMatrix const&, EpetraExt::RemoteOnlyImport&, bool, char const*)':
EpetraExt_MMHelpers.cpp:(.text._ZN9EpetraExt20LightweightCrsMatrix9ConstructINS_16RemoteOnlyImportExEEvRK16Epetra_CrsMatrixRT_bPKc[_ZN9EpetraExt20LightweightCrsMatrix9ConstructINS_16RemoteOnlyImportExEEvRK16Epetra_CrsMatrixRT_bPKc]+0x4f3): undefined reference to `ompi_mpi_char'
EpetraExt_MMHelpers.cpp:(.text._ZN9EpetraExt20LightweightCrsMatrix9ConstructINS_16RemoteOnlyImportExEEvRK16Epetra_CrsMatrixRT_bPKc[_ZN9EpetraExt20LightweightCrsMatrix9ConstructINS_16RemoteOnlyImportExEEvRK16Epetra_CrsMatrixRT_bPKc]+0x682): undefined reference to `ompi_mpi_long_long_int'
/usr/local/bin/trilinos-12.4.2/lib/libepetraext.a(EpetraExt_MMHelpers.cpp.o): In function `void EpetraExt::LightweightCrsMatrix::Construct<Epetra_Import, long long>(Epetra_CrsMatrix const&, Epetra_Import&, bool, char const*)':
EpetraExt_MMHelpers.cpp:(.text._ZN9EpetraExt20LightweightCrsMatrix9ConstructI13Epetra_ImportxEEvRK16Epetra_CrsMatrixRT_bPKc[_ZN9EpetraExt20LightweightCrsMatrix9ConstructI13Epetra_ImportxEEvRK16Epetra_CrsMatrixRT_bPKc]+0x518): undefined reference to `ompi_mpi_char'
EpetraExt_MMHelpers.cpp:(.text._ZN9EpetraExt20LightweightCrsMatrix9ConstructI13Epetra_ImportxEEvRK16Epetra_CrsMatrixRT_bPKc[_ZN9EpetraExt20LightweightCrsMatrix9ConstructI13Epetra_ImportxEEvRK16Epetra_CrsMatrixRT_bPKc]+0x6c5): undefined reference to `ompi_mpi_long_long_int'
/usr/local/bin/trilinos-12.4.2/lib/libzoltan.a(phg_rdivide.c.o): In function `split_hypergraph.isra.1':
phg_rdivide.c:(.text+0x382): undefined reference to `ompi_mpi_double'
phg_rdivide.c:(.text+0x393): undefined reference to `ompi_mpi_op_sum'
phg_rdivide.c:(.text+0x655): undefined reference to `ompi_mpi_op_sum'
phg_rdivide.c:(.text+0x6a8): undefined reference to `ompi_mpi_op_sum'
/usr/local/bin/trilinos-12.4.2/lib/libzoltan.a(phg_rdivide.c.o): In function `Zoltan_PHG_rdivide':
phg_rdivide.c:(.text+0x1861): undefined reference to `ompi_mpi_op_sum'
phg_rdivide.c:(.text+0x1868): undefined reference to `ompi_mpi_int'
`

... much the same output but  with different '/usr/local/bin/trilinos-12.4.2/lib/' files

`collect2: error: ld returned 1 exit status
src/CMakeFiles/Peridigm.dir/build.make:575: recipe for target 'src/Peridigm' failed
make[2]: *** [src/Peridigm] Error 1
CMakeFiles/Makefile2:102: recipe for target 'src/CMakeFiles/Peridigm.dir/all' failed
make[1]: *** [src/CMakeFiles/Peridigm.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by bb515** [comment]
Further information:

had to set Trilinos_ENABLE_TESTS to OFF during the trilinos compile since, error:


"""
CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/TestThyraDebugHang.cpp.o: In function `ThyraEpetraMultiVector_HangingInParallelDebug_UnitTest::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const':
TestThyraDebugHang.cpp:(.text+0x116b): undefined reference to `Thyra::DefaultSpmdVectorSpace<double>::initialize(Teuchos::RCP<Teuchos::Comm<long> const> const&, long, long, bool)'
collect2: error: ld returned 1 exit status
packages/thyra/adapters/epetra/test/CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/build.make:137: recipe for target 'packages/thyra/adapters/epetra/test/ThyraEpetraAdapters_TestThyraDebugHang.exe' failed
make[2]: *** [packages/thyra/adapters/epetra/test/ThyraEpetraAdapters_TestThyraDebugHang.exe] Error 1
CMakeFiles/Makefile2:34296: recipe for target 'packages/thyra/adapters/epetra/test/CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/all' failed
make[1]: *** [packages/thyra/adapters/epetra/test/CMakeFiles/ThyraEpetraAdapters_TestThyraDebugHang.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
"""

It then built sucessfully but I expect this might bring up problems in the future with Peridigm?

**Comment by oldninja** [comment]
Hi @bb515, I'm new to this too and encountered a similar problem. I'm using the same instructions as you (https://pdfs.semanticscholar.org/85cd/61b50b63eb0936169923b26d9efffe5a2e8b.pdf), the major difference is I'm using Ubuntu 18.04 LTS and I had to change a few things:
1. CMake = 3.10.2
2. HDF5 = 1.10.5
3. OpenMPI = 1.10.7
4. GCC = 7.4.0
the rest are the same.

My build fails at:
`[ 48%] Linking CXX executable Peridigm
/usr/bin/ld: cannot find /usr/local/bin/trilinos-12.4.2/lib/libteuchosnumerics.a: Too many open files
....
[more and more ...and more errors on "/usr/bin/ld: cannot find X: Too many open files"]
....
collect2: error: ld returned 1 exit status
src/CMakeFiles/Peridigm.dir/build.make:1352: recipe for target 'src/Peridigm' failed
make[2]: *** [src/Peridigm] Error 1
CMakeFiles/Makefile2:102: recipe for target 'src/CMakeFiles/Peridigm.dir/all' failed
make[1]: *** [src/CMakeFiles/Peridigm.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2`

CMake for building:
`rm -f CMakeCache.txt
rm -rf CMakeFiles/

cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Trilinos_DIR:PATH=/usr/local/bin/trilinos-12.4.2/lib/cmake/Trilinos/ \
-D CMAKE_C_COMPILER:STRING=/usr/bin/mpicc \
-D CMAKE_CXX_COMPILER:STRING=/usr/bin/mpicxx \
-D BOOST_ROOT=/usr/local/lib/boost-1.55.0/ \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
/usr/local/src/Peridigm-1.5.0-Source`

[cmakeopts.log](https://github.com/peridigm/peridigm/files/4051309/cmakeopts.log)

**Comment by oldninja** [comment]
Apparently needed to increase the number of files open - refs: https://underyx.me/articles/raising-the-maximum-number-of-file-descriptors
