### ISSUE TITLE
"Pressure Dependent Elastic Plastic"

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#109]
Hi,

I would like to use "LammiConcreteModel" by compiling with -DUSE_CJL. However, it shows "Peridigm_LammiConcreteModel.hpp: No such file or directory". Is the Pressure Dependent Elastic Plastic material model still available in Peridigm?

Thanks very much!

**Comment by johntfoster** [comment]
This was a private model developed by Chris Lammi when he was a graduate
student at Georgia Tech.  It was never available in the public version of
Peridigm.
