### ISSUE TITLE
Build peridigm with yaml ERROR

### ISSUE THREAD

**Issue by Coooooco** [peridigm/peridigm#110]
Dear all,
When I built Trilinos and peridigm without yaml, the whole building processes went well. When I rebuilt Trilinos with yaml,it went well,too.But when I came into rebuilding peridigm ,errors occurred during ''make -j 4''. The details are as follows：
root@coco-Precision-7920-Rack:/home/coco/download/pdbuild# make -j 4
[  0%] Building CXX object src/io/pdneigh/CMakeFiles/PdNeigh.dir/__/Peridigm_JAMSearchTree.cpp.o
[  0%] Building CXX object src/io/mesh_input/quick_grid/CMakeFiles/QuickGrid.dir/QuickGrid.cxx.o
[  1%] Building CXX object src/materials/CMakeFiles/PdMaterialUtilities.dir/__/core/Peridigm_InfluenceFunction.cpp.o
/home/coco/download/peridigm-master/src/io/mesh_input/quick_grid/QuickGrid.cxx:51:12: fatal error: Teuchos_YamlParameterListCoreHelpers.hpp: no such file or directory
   #include <Teuchos_YamlParameterListCoreHelpers.hpp>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
…
[ 31%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Factory.cpp.o
[ 31%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Field.cpp.o
/home/coco/download/peridigm-master/src/core/Peridigm_Factory.cpp:52:12: fatal error: Teuchos_YamlParser_decl.hpp: no such file or directory
   #include <Teuchos_YamlParser_decl.hpp>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
…
CMakeFiles/Makefile2:141: recipe for target 'src/CMakeFiles/PeridigmLib.dir/all' failed
make[1]: *** [src/CMakeFiles/PeridigmLib.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

By the way,I do add：
-D TPL_ENABLE_yaml-cpp:BOOL=ON \
-D yaml-cpp_INCLUDE_DIRS:PATH=/usr/local/include \
-D yaml-cpp_LIBRARY_DIRS:PATH=/usr/local/lib \
in rebuild Trilinos.

Does anyone know what's the problem？
I would appreciate your replies.
Thank you very much！

**Comment by Coooooco** [comment]
Also,when I tried to rebuild trilinos with yaml-cpp :+1: 
rm -f CMakeCache.txt
cmake -D CMAKE_INSTALL_PREFIX:PATH=/usr/local/trilinos \
-D MPI_BASE_DIR:PATH="/usr/local/mpich-3.3.1/" \
-D CMAKE_CXX_FLAGS:STRING="-O2 -std=c++11 -pedantic -ftrapv -Wall -ansi -Wno-long-long" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Sacado:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_ML:BOOL=ON \
-D Trilinos_ENABLE_Phalanx:BOOL=ON \
-D Trilinos_ENABLE_Intrepid:BOOL=ON \
-D Trilinos_ENABLE_NOX:BOOL=ON \
-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Trilinos_ENABLE_Rythmos:BOOL=ON \
-D Trilinos_ENABLE_MOOCHO:BOOL=ON \
-D Trilinos_ENABLE_TriKota:BOOL=OFF \
-D Trilinos_ENABLE_Stokhos:BOOL=ON \
-D Trilinos_ENABLE_Zoltan:BOOL=ON \
-D Trilinos_ENABLE_Piro:BOOL=ON \
-D Trilinos_ENABLE_Teko:BOOL=ON \
-D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
-D Trilinos_ENABLE_SEACAS:BOOL=ON \
-D Trilinos_ENABLE_SEACASBlot:BOOL=ON \
-D Trilinos_ENABLE_Pamgen:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D TPL_ENABLE_HDF5:BOOL=ON \
-D HDF5_INCLUDE_DIRS:PATH="/usr/local/HDF5/include" \
-D HDF5_LIBRARY_DIRS:PATH="/usr/local/HDF5/lib" \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D TPL_Netcdf_Enables_Netcdf4:BOOL=ON \
-D Netcdf_INCLUDE_DIRS:PATH="/usr/local/netcdf/include" \
-D Netcdf_LIBRARY_DIRS:PATH="/usr/local/netcdf/lib" \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_BLAS:BOOL=ON \
-D TPL_ENABLE_LAPACK:BOOL=ON \
-D TPL_ENABLE_Boost:BOOL=ON \
-D Boost_INCLUDE_DIRS:PATH="/usr/local/boost/include" \
-D Boost_LIBRARY_DIRS:PATH="/usr/local/boost/lib" \
-D TPL_ENABLE_Matio:BOOL=ON \
-D Matio_INCLUDE_DIRS:PATH="/usr/local/matio/include" \
-D Matio_LIBRARY_DIRS:PATH="/usr/local/matio/lib" \
-D TPL_ENABLE_yaml-cpp:BOOL=ON \
-D yaml-cpp_INCLUDE_DIRS:PATH=/usr/local/yaml-cpp/include \
-D yaml-cpp_LIBRARY_DIRS:PATH=/usr/local/yaml-cpp/lib \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
/home/coco/download/trilinos-12.10.1-Source

Error occurred during'' make -j 4'' :

Scanning dependencies of target TeuchosComm_ParameterList_UnitTest_Parallel
[ 59%] Building CXX object packages/teuchos/comm/test/ParameterList/CMakeFiles/TeuchosComm_ParameterList_UnitTest_Parallel.dir/ParameterList_UnitTest_Parallel.cpp.o
[ 59%] Linking CXX executable TeuchosComm_scatter.exe
[ 59%] Built target TeuchosComm_scatter
[ 59%] Building CXX object packages/teuchos/comm/test/ParameterList/CMakeFiles/TeuchosComm_ParameterList_UnitTest_Parallel.dir/__/__/__/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o
Scanning dependencies of target TeuchosComm_TimeMonitor_UnitTests
[ 59%] Building CXX object packages/teuchos/comm/test/ParameterList/CMakeFiles/TeuchosComm_ParameterList_UnitTest_Parallel.dir/ParameterList_yaml_Parallel.cpp.o
[ 59%] Building CXX object packages/teuchos/comm/test/Time/CMakeFiles/TeuchosComm_TimeMonitor_UnitTests.dir/TimeMonitor_UnitTests.cpp.o
[ 59%] Linking CXX executable TeuchosComm_ParameterList_UnitTest_Parallel.exe
CMakeFiles/TeuchosComm_ParameterList_UnitTest_Parallel.dir/ParameterList_yaml_Parallel.cpp.o：在函数‘TeuchosTests::YAML_MPIBroadcast_UnitTest::runUnitTestImpl(Teuchos::basic_FancyOStream<char, std::char_traits<char> >&, bool&) const’中：
ParameterList_yaml_Parallel.cpp:(.text+0x54a)：对‘Teuchos::updateParametersFromYamlFileAndBroadcast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::Ptr<Teuchos::ParameterList> const&, Teuchos::Comm<int> const&, bool)’未定义的引用  
**This error means An undefined reference of ParameterList_yaml_Parallel.cpp:(.text+0x54a)to‘Teuchos::updateParametersFromYamlFileAndBroadcast(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Teuchos::Ptr<Teuchos::ParameterList> const&, Teuchos::Comm<int> const&, bool)’**
collect2: error: ld returned 1 exit status
packages/teuchos/comm/test/ParameterList/CMakeFiles/TeuchosComm_ParameterList_UnitTest_Parallel.dir/build.make:153: recipe for target 'packages/teuchos/comm/test/ParameterList/TeuchosComm_ParameterList_UnitTest_Parallel.exe' failed
make[2]: *** [packages/teuchos/comm/test/ParameterList/TeuchosComm_ParameterList_UnitTest_Parallel.exe] Error 1
CMakeFiles/Makefile2:6123: recipe for target 'packages/teuchos/comm/test/ParameterList/CMakeFiles/TeuchosComm_ParameterList_UnitTest_Parallel.dir/all' failed
make[1]: *** [packages/teuchos/comm/test/ParameterList/CMakeFiles/TeuchosComm_ParameterList_UnitTest_Parallel.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 59%] Building CXX object packages/teuchos/comm/test/Comm/CMakeFiles/TeuchosComm_DefaultMpiComm_UnitTests.dir/__/__/__/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o
[ 59%] Building CXX object packages/teuchos/comm/test/Time/CMakeFiles/TeuchosComm_TimeMonitor_UnitTests.dir/__/__/__/core/test/UnitTest/Teuchos_StandardUnitTestMain.cpp.o
[ 59%] Linking CXX executable TeuchosComm_TimeMonitor_UnitTests.exe
[ 59%] Built target TeuchosComm_TimeMonitor_UnitTests
[ 59%] Linking CXX executable TeuchosComm_Comm_test.exe
[ 59%] Built target TeuchosComm_Comm_test
[ 59%] Linking CXX executable TeuchosComm_DefaultMpiComm_UnitTests.exe
[ 59%] Built target TeuchosComm_DefaultMpiComm_UnitTests
Makefile:162: recipe for target 'all' failed

Are there some problems between trilinos and yaml-cpp？
Thanks

**Comment by Yichun-Wang666** [comment]
i got this problem when install it with yaml-cpp too,did you have solve it?

**Comment by oldninja** [comment]
Hi, I have a similar problem. I added the yaml-cpp library in a similar way, and recompiled Trilinos - all went fine. But trying to recompile Peridigm 1.5.0 gives me the following error:
`[ 33%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Field.cpp.o
/usr/local/src/Peridigm-1.5.0-Source/src/core/Peridigm_Factory.cpp:52:12: fatal error: Teuchos_YamlParser_decl.hpp: No such file or directory
   #include <Teuchos_YamlParser_decl.hpp>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
src/CMakeFiles/PeridigmLib.dir/build.make:1094: recipe for target 'src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Factory.cpp.o' failed
make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Factory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....`

Not sure what's going on because it compiled and installed fine without the yaml-cpp library, and I only noticed the requirement when I tried to run the disk example.

The yaml-cpp was from this repo: https://github.com/jbeder/yaml-cpp
and using Trilinos 12.4.2

Any help would be greatly appreciated!

**Comment by suaid94** [comment]
> Hi, I have a similar problem. I added the yaml-cpp library in a similar way, and recompiled Trilinos - all went fine. But trying to recompile Peridigm 1.5.0 gives me the following error: `[ 33%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Field.cpp.o /usr/local/src/Peridigm-1.5.0-Source/src/core/Peridigm_Factory.cpp:52:12: fatal error: Teuchos_YamlParser_decl.hpp: No such file or directory #include <Teuchos_YamlParser_decl.hpp> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. src/CMakeFiles/PeridigmLib.dir/build.make:1094: recipe for target 'src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Factory.cpp.o' failed make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Factory.cpp.o] Error 1 make[2]: *** Waiting for unfinished jobs....`
> 
> Not sure what's going on because it compiled and installed fine without the yaml-cpp library, and I only noticed the requirement when I tried to run the disk example.
> 
> The yaml-cpp was from this repo: https://github.com/jbeder/yaml-cpp and using Trilinos 12.4.2
> 
> Any help would be greatly appreciated!
> 
> *Edited on 2020/02/09: Recompiled everything and performed a clean installation. - It worked fine.

Hello oldninja

I see you solved the problem, can you please tell me how did you do it? 
what did you mean by clean installation? 

Thanks!

**Comment by oldninja** [comment]
I meant start from scratch on Trilinos and Peridigm.
