### ISSUE TITLE
error happened when run the fragmenting cylinder example 

### ISSUE THREAD

**Issue by woaio5** [peridigm/peridigm#111]
Dear All:
I have installed the Peridigm-master and I can run all the examples except fragmenting cylinder. The Peridigm throws a exception about node set. The details shows here:
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
/public/home/cniclixy/lxy/peridigm/src/core/Peridigm_BoundaryCondition.cpp:175:

Throw number = 1

Throw test that evaluated to true: nodeSets->find(nodeSetName) == nodeSets->end()

**** Error in DirichletBC::apply(), node set not found: FULL_DOMAIN
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
I want to know what cause the exception and how can i set the node set parameter correctly

Thanks!

**Comment by oldninja** [comment]
Hi @woaio5,
Apparently the option/command for "Full Domain" is not longer available. Please take a look at the wave_in_bar example and do something similar for the node-set in the file "fragmenting_cylinder_nodeset.txt":
`  Boundary Conditions:
      Node Set One: "node_set_1.txt"
      Bar Initial Velocity:
          Type: "Initial Velocity"
          Node Set: "Node Set One"
          Coordinate: "x"
          Value: "100.0"`
Hopefully, this helps! Good luck!
