### ISSUE TITLE
make test fail

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#122]
I received test failure in 5 steps:
133:InitialDamage_np4
170:IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np1
171:IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np4
172:IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np1
173:IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np4

In IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw.log:
  ==============================================================
  NOTE: All node and element ids are reported as global ids.

Sideset Distribution Factors:
  --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, abs diff:  0.00000e+00 ---------
Nodal variables:
Element variables:
  --------- Time step 2, 2.5000000e-07 ~ 2.5000000e-07, abs diff:  0.00000e+00 ---------
Nodal variables:
   VelocityX                 abs diff: -3.1615493e-03 ~ -3.1724197e-03 = 1.08704e-05 (node 371)
   VelocityY                 abs diff:  2.8750000e+05 ~  2.8750000e+05 = 1.81039e-05 (node 238)
   VelocityZ                 abs diff:  3.1615493e-03 ~  3.1724197e-03 = 1.08704e-05 (node 348)
   ForceX                    abs diff: -1.5412553e+08 ~ -1.5465546e+08 = 5.29933e+05 (node 371)
   ForceY                    abs diff:  1.7184524e+08 ~  1.7096268e+08 = 8.82563e+05 (node 315)
   ForceZ                    abs diff:  1.5412553e+08 ~  1.5465546e+08 = 5.29933e+05 (node 348)
Element variables:
   Unrotated_Cauchy_StressXX        abs diff:  1.5600223e+09 ~  1.5653862e+09 = 5.36386e+06 (block 1, elmt 360)
   Unrotated_Cauchy_StressYY        abs diff:  2.0888103e+09 ~  2.0780825e+09 = 1.07277e+07 (block 1, elmt 82)
   Unrotated_Cauchy_StressZZ        abs diff:  1.5600223e+09 ~  1.5653862e+09 = 5.36386e+06 (block 1, elmt 360)
   Cauchy_StressXX                  abs diff:  1.5600223e+09 ~  1.5653862e+09 = 5.36386e+06 (block 1, elmt 360)
   Cauchy_StressYY                  abs diff:  2.0888103e+09 ~  2.0780825e+09 = 1.07277e+07 (block 1, elmt 82)
   Cauchy_StressZZ                  abs diff:  1.5600223e+09 ~  1.5653862e+09 = 5.36386e+06 (block 1, elmt 360)
   Von_Mises_Stress                 abs diff:  5.2878795e+08 ~  5.1269638e+08 = 1.60916e+07 (block 1, elmt 47)
   Equivalent_Plastic_Strain        abs diff:  1.3522824e-02 ~  1.3534261e-02 = 1.14371e-05 (block 1, elmt 208)
  --------- Time step 3, 5.0000000e-07 ~ 5.0000000e-07, abs diff:  0.00000e+00 ---------
Nodal variables:
   VelocityX                 abs diff:  6.7049740e-03 ~  6.7177713e-03 = 1.27973e-05 (node 298)
   VelocityY                 abs diff:  2.8749999e+05 ~  2.8749999e+05 = 2.08054e-05 (node 238)
   VelocityZ                 abs diff: -6.7049740e-03 ~ -6.7177713e-03 = 1.27973e-05 (node 321)
   ForceX                    abs diff:  3.2686748e+08 ~  3.2749135e+08 = 6.23867e+05 (node 298)
   ForceY                    abs diff: -3.1532297e+08 ~ -3.1430870e+08 = 1.01426e+06 (node 238)
   ForceZ                    abs diff: -3.2686748e+08 ~ -3.2749135e+08 = 6.23867e+05 (node 321)
Element variables:
   Unrotated_Cauchy_StressXX        abs diff:  3.2297025e+09 ~  3.2358668e+09 = 6.16429e+06 (block 1, elmt 243)
   Unrotated_Cauchy_StressYY        abs diff:  3.8328082e+09 ~  3.8204796e+09 = 1.23286e+07 (block 1, elmt 14)
   Unrotated_Cauchy_StressZZ        abs diff:  3.2297025e+09 ~  3.2358668e+09 = 6.16429e+06 (block 1, elmt 243)
   Cauchy_StressXX                  abs diff:  3.2297025e+09 ~  3.2358668e+09 = 6.16429e+06 (block 1, elmt 243)
   Cauchy_StressYY                  abs diff:  3.8328082e+09 ~  3.8204796e+09 = 1.23286e+07 (block 1, elmt 14)
   Cauchy_StressZZ                  abs diff:  3.2297025e+09 ~  3.2358668e+09 = 6.16429e+06 (block 1, elmt 243)
   Von_Mises_Stress                 abs diff:  6.0310572e+08 ~  5.8461286e+08 = 1.84929e+07 (block 1, elmt 231)
   Equivalent_Plastic_Strain        abs diff:  2.8158837e-02 ~  2.8145066e-02 = 1.37716e-05 (block 1, elmt 9)
  --------- Time step 4, 7.5000000e-07 ~ 7.5000000e-07, abs diff:  0.00000e+00 ---------
Nodal variables:
   VelocityX                 abs diff:  1.0329481e-02 ~  1.0344249e-02 = 1.47677e-05 (node 299)
   VelocityY                 abs diff:  2.8749999e+05 ~  2.8749999e+05 = 2.34505e-05 (node 238)
   VelocityZ                 abs diff:  1.0329481e-02 ~  1.0344249e-02 = 1.47677e-05 (node 256)
   ForceX                    abs diff:  5.0356219e+08 ~  5.0428212e+08 = 7.19925e+05 (node 299)
   ForceY                    abs diff: -4.5546317e+08 ~ -4.5431995e+08 = 1.14321e+06 (node 238)
   ForceZ                    abs diff:  5.0356219e+08 ~  5.0428212e+08 = 7.19925e+05 (node 256)
Element variables:
   Unrotated_Cauchy_StressXX        abs diff:  4.8598711e+09 ~  4.8668190e+09 = 6.94798e+06 (block 1, elmt 360)
   Unrotated_Cauchy_StressYY        abs diff:  5.5362379e+09 ~  5.5223419e+09 = 1.38960e+07 (block 1, elmt 221)
   Unrotated_Cauchy_StressZZ        abs diff:  4.8598711e+09 ~  4.8668190e+09 = 6.94798e+06 (block 1, elmt 360)
   Cauchy_StressXX                  abs diff:  4.8598711e+09 ~  4.8668190e+09 = 6.94798e+06 (block 1, elmt 360)
   Cauchy_StressYY                  abs diff:  5.5362379e+09 ~  5.5223419e+09 = 1.38960e+07 (block 1, elmt 221)
   Cauchy_StressZZ                  abs diff:  4.8598711e+09 ~  4.8668190e+09 = 6.94798e+06 (block 1, elmt 360)
   Von_Mises_Stress                 abs diff:  6.7636680e+08 ~  6.5552285e+08 = 2.08439e+07 (block 1, elmt 11)
   Equivalent_Plastic_Strain        abs diff:  4.2586016e-02 ~  4.2550661e-02 = 3.53550e-05 (block 1, elmt 313)
  --------- Time step 5, 1.0000000e-06 ~ 1.0000000e-06, abs diff:  0.00000e+00 ---------
Nodal variables:
   VelocityX                 abs diff:  1.4033256e-02 ~  1.4050035e-02 = 1.67794e-05 (node 207)
   VelocityY                 abs diff:  2.8749999e+05 ~  2.8749999e+05 = 2.60395e-05 (node 238)
   VelocityZ                 abs diff: -1.4033256e-02 ~ -1.4050035e-02 = 1.67794e-05 (node 345)
   ForceX                    abs diff:  6.8412123e+08 ~  6.8493922e+08 = 8.17995e+05 (node 207)
   ForceY                    abs diff: -5.9241210e+08 ~ -5.9114268e+08 = 1.26942e+06 (node 238)
   ForceZ                    abs diff: -6.8412123e+08 ~ -6.8493922e+08 = 8.17995e+05 (node 345)
Element variables:
   Unrotated_Cauchy_StressXX        abs diff:  6.4523880e+09 ~  6.4601031e+09 = 7.71504e+06 (block 1, elmt 164)
   Unrotated_Cauchy_StressYY        abs diff:  7.2008772e+09 ~  7.1854471e+09 = 1.54301e+07 (block 1, elmt 298)
   Unrotated_Cauchy_StressZZ        abs diff:  6.4523880e+09 ~  6.4601031e+09 = 7.71504e+06 (block 1, elmt 164)
   Cauchy_StressXX                  abs diff:  6.4523880e+09 ~  6.4601031e+09 = 7.71504e+06 (block 1, elmt 164)
   Cauchy_StressYY                  abs diff:  7.2008772e+09 ~  7.1854471e+09 = 1.54301e+07 (block 1, elmt 298)
   Cauchy_StressZZ                  abs diff:  6.4523880e+09 ~  6.4601031e+09 = 7.71504e+06 (block 1, elmt 164)
   Von_Mises_Stress                 abs diff:  7.4848912e+08 ~  7.2534400e+08 = 2.31451e+07 (block 1, elmt 15)
   Equivalent_Plastic_Strain        abs diff:  5.6788416e-02 ~  5.6734527e-02 = 5.38883e-05 (block 1, elmt 15)

exodiff: Files are different

And in IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw.log:
  ==============================================================
  NOTE: All node and element ids are reported as global ids.

Sideset Distribution Factors:
  --------- Time step 1, 0.0000000e+00 ~ 0.0000000e+00, abs diff:  0.00000e+00 ---------
Nodal variables:
Element variables:
  --------- Time step 2, 2.5000000e-07 ~ 2.5000000e-07, abs diff:  0.00000e+00 ---------
Nodal variables:
   VelocityX                 abs diff: -3.1615609e-03 ~ -3.1724310e-03 = 1.08701e-05 (node 370)
   VelocityY                 abs diff:  2.8750000e+05 ~  2.8750000e+05 = 1.81038e-05 (node 238)
   VelocityZ                 abs diff:  3.1615609e-03 ~  3.1724310e-03 = 1.08701e-05 (node 256)
   ForceX                    abs diff: -1.5412610e+08 ~ -1.5465601e+08 = 5.29916e+05 (node 370)
   ForceY                    abs diff:  1.7184518e+08 ~  1.7096262e+08 = 8.82561e+05 (node 314)
   ForceZ                    abs diff:  1.5412610e+08 ~  1.5465601e+08 = 5.29916e+05 (node 348)
Element variables:
   Unrotated_Cauchy_StressXX        abs diff:  1.5600223e+09 ~  1.5653862e+09 = 5.36386e+06 (block 1, elmt 216)
   Unrotated_Cauchy_StressYY        abs diff:  2.0888102e+09 ~  2.0780825e+09 = 1.07277e+07 (block 1, elmt 361)
   Unrotated_Cauchy_StressZZ        abs diff:  1.5600223e+09 ~  1.5653862e+09 = 5.36386e+06 (block 1, elmt 216)
   Cauchy_StressXX                  abs diff:  1.5600223e+09 ~  1.5653862e+09 = 5.36386e+06 (block 1, elmt 216)
   Cauchy_StressYY                  abs diff:  2.0888102e+09 ~  2.0780825e+09 = 1.07277e+07 (block 1, elmt 361)
   Cauchy_StressZZ                  abs diff:  1.5600223e+09 ~  1.5653862e+09 = 5.36386e+06 (block 1, elmt 216)
   Von_Mises_Stress                 abs diff:  5.2878792e+08 ~  5.1269635e+08 = 1.60916e+07 (block 1, elmt 289)
   Equivalent_Plastic_Strain        abs diff:  1.3522824e-02 ~  1.3534261e-02 = 1.14371e-05 (block 1, elmt 213)
  --------- Time step 3, 5.0000000e-07 ~ 5.0000000e-07, abs diff:  0.00000e+00 ---------
Nodal variables:
   VelocityX                 abs diff: -6.7049860e-03 ~ -6.7177830e-03 = 1.27969e-05 (node 370)
   VelocityY                 abs diff:  2.8749999e+05 ~  2.8749999e+05 = 2.08054e-05 (node 238)
   VelocityZ                 abs diff:  6.7049860e-03 ~  6.7177830e-03 = 1.27969e-05 (node 324)
   ForceX                    abs diff: -3.2686807e+08 ~ -3.2749192e+08 = 6.23850e+05 (node 370)
   ForceY                    abs diff: -3.1532291e+08 ~ -3.1430865e+08 = 1.01426e+06 (node 238)
   ForceZ                    abs diff:  3.2686807e+08 ~  3.2749192e+08 = 6.23850e+05 (node 324)
Element variables:
   Unrotated_Cauchy_StressXX        abs diff:  3.2297025e+09 ~  3.2358668e+09 = 6.16429e+06 (block 1, elmt 216)
   Unrotated_Cauchy_StressYY        abs diff:  3.8328082e+09 ~  3.8204796e+09 = 1.23286e+07 (block 1, elmt 213)
   Unrotated_Cauchy_StressZZ        abs diff:  3.2297025e+09 ~  3.2358668e+09 = 6.16429e+06 (block 1, elmt 216)
   Cauchy_StressXX                  abs diff:  3.2297025e+09 ~  3.2358668e+09 = 6.16429e+06 (block 1, elmt 216)
   Cauchy_StressYY                  abs diff:  3.8328082e+09 ~  3.8204796e+09 = 1.23286e+07 (block 1, elmt 213)
   Cauchy_StressZZ                  abs diff:  3.2297025e+09 ~  3.2358668e+09 = 6.16429e+06 (block 1, elmt 216)
   Von_Mises_Stress                 abs diff:  6.0310570e+08 ~  5.8461284e+08 = 1.84929e+07 (block 1, elmt 288)
   Equivalent_Plastic_Strain        abs diff:  2.8018332e-02 ~  2.7988966e-02 = 2.93660e-05 (block 1, elmt 123)
  --------- Time step 4, 7.5000000e-07 ~ 7.5000000e-07, abs diff:  0.00000e+00 ---------
Nodal variables:
   VelocityX                 abs diff: -1.0329493e-02 ~ -1.0344261e-02 = 1.47673e-05 (node 370)
   VelocityY                 abs diff:  2.8749999e+05 ~  2.8749999e+05 = 2.34505e-05 (node 238)
   VelocityZ                 abs diff: -1.0329493e-02 ~ -1.0344261e-02 = 1.47673e-05 (node 253)
   ForceX                    abs diff: -5.0356280e+08 ~ -5.0428270e+08 = 7.19907e+05 (node 370)
   ForceY                    abs diff: -4.5546311e+08 ~ -4.5431990e+08 = 1.14321e+06 (node 262)
   ForceZ                    abs diff: -5.0356280e+08 ~ -5.0428270e+08 = 7.19907e+05 (node 253)
Element variables:
   Unrotated_Cauchy_StressXX        abs diff:  4.8598711e+09 ~  4.8668190e+09 = 6.94798e+06 (block 1, elmt 364)
   Unrotated_Cauchy_StressYY        abs diff:  5.5362378e+09 ~  5.5223419e+09 = 1.38960e+07 (block 1, elmt 289)
   Unrotated_Cauchy_StressZZ        abs diff:  4.8598711e+09 ~  4.8668190e+09 = 6.94798e+06 (block 1, elmt 364)
   Cauchy_StressXX                  abs diff:  4.8598711e+09 ~  4.8668190e+09 = 6.94798e+06 (block 1, elmt 364)
   Cauchy_StressYY                  abs diff:  5.5362378e+09 ~  5.5223419e+09 = 1.38960e+07 (block 1, elmt 289)
   Cauchy_StressZZ                  abs diff:  4.8598711e+09 ~  4.8668190e+09 = 6.94798e+06 (block 1, elmt 364)
   Von_Mises_Stress                 abs diff:  6.7636677e+08 ~  6.5552283e+08 = 2.08439e+07 (block 1, elmt 216)
   Equivalent_Plastic_Strain        abs diff:  4.2312495e-02 ~  4.2258198e-02 = 5.42962e-05 (block 1, elmt 122)
  --------- Time step 5, 1.0000000e-06 ~ 1.0000000e-06, abs diff:  0.00000e+00 ---------
Nodal variables:
   VelocityX                 abs diff:  1.4033269e-02 ~  1.4050048e-02 = 1.67790e-05 (node 207)
   VelocityY                 abs diff:  2.8749999e+05 ~  2.8749999e+05 = 2.60394e-05 (node 238)
   VelocityZ                 abs diff:  1.4033269e-02 ~  1.4050048e-02 = 1.67790e-05 (node 256)
   ForceX                    abs diff:  6.8412185e+08 ~  6.8493983e+08 = 8.17977e+05 (node 207)
   ForceY                    abs diff: -5.9241204e+08 ~ -5.9114262e+08 = 1.26942e+06 (node 263)
   ForceZ                    abs diff:  6.8412185e+08 ~  6.8493983e+08 = 8.17977e+05 (node 256)
Element variables:
   Unrotated_Cauchy_StressXX        abs diff:  6.4523881e+09 ~  6.4601031e+09 = 7.71504e+06 (block 1, elmt 292)
   Unrotated_Cauchy_StressYY        abs diff:  7.2008771e+09 ~  7.1854471e+09 = 1.54301e+07 (block 1, elmt 289)
   Unrotated_Cauchy_StressZZ        abs diff:  6.4523881e+09 ~  6.4601031e+09 = 7.71504e+06 (block 1, elmt 292)
   Cauchy_StressXX                  abs diff:  6.4523881e+09 ~  6.4601031e+09 = 7.71504e+06 (block 1, elmt 292)
   Cauchy_StressYY                  abs diff:  7.2008771e+09 ~  7.1854471e+09 = 1.54301e+07 (block 1, elmt 289)
   Cauchy_StressZZ                  abs diff:  6.4523881e+09 ~  6.4601031e+09 = 7.71504e+06 (block 1, elmt 292)
   Von_Mises_Stress                 abs diff:  7.4848909e+08 ~  7.2534397e+08 = 2.31451e+07 (block 1, elmt 216)
   Equivalent_Plastic_Strain        abs diff:  5.6409555e-02 ~  5.6333916e-02 = 7.56384e-05 (block 1, elmt 118)

exodiff: Files are different

Any help will be highly appreciated!

Thanks!

**Comment by jritta** [comment]
@rbh007720
The four tests 170,171,172,173 do also always fail with my binary as well (By the way, on my installation those are the tests 188, 189, 190 and, 191). I guess the 'gold' file is corrupt or something in the implementation of the material model is wrong. I did not implement it and thus I can not help you with that.
Regarding test 133: In my installation test 133 is `DeformationGradient_SolidRotation_np4` and `InitialDamage_np4` is test 145. I do not know now which one fails on your installation. Anyway, with my binary non of those two fails. So maybe you send us your log file from the test that fails.

Best,
Jonas
