### ISSUE TITLE
Difference between contact search radius and contact radius

### ISSUE THREAD

**Issue by mewael-isiet** [peridigm/peridigm#123]
Could anyone please explain the difference between the contact search radius and contact radius? As far as I know, the contact radius is used to define the distance after which contact forces are experienced between non-similar material points, and it is typically set as 0.9*grid_spacing. If two bodies exist with different grid_spacing, which one would you use to set the contact radius. And, what is the rule of thumb for setting the contact search radius and search frequency?

Thanks alot!

**Comment by djlittl** [comment]
The contact search radius is the value that’s passed into the proximity search algorithm, whereas the contact radius is the value that’s used for calculating the contact force.  The contact search frequency is the number of time steps that occur before the proximity search is executed again.

In theory, setting a large contact search radius should allow you to get away with executing the proximity search less often.  My experience is that this doesn’t pay off in practice, and I suggest you set the contact search radius equal to the contact radius and set the contact search frequency to 1.

As far as I know, there is no foolproof way to set the contact radius.  Setting it to 0.9 times the grid spacing seems like a good starting point.  Peridigm uses a simplistic sphere-sphere contact model, which can produce decent results in many cases.  But it’s definitely not guaranteed to work.  One thing that can obviously go wrong is that bodies can penetrate each other in a unphysical way such that the peridynamic neighborhoods become intertwined.  This can happen if the contact radius is too small, or if the velocities are large relative to the contact forces such that the forces that push the bodies apart are not strong enough to avoid interpenetration.  In practice, trail-and-error is usually required.  In other words, start with reasonable values for the contact radii and the contact force parameters, and adjust as needed if the simulation does not produce reasonable results.  Not very satisfying, I realize.  If would be great if Peridigm had more robust methods available (e.g., level set surface definitions), but these are not trivial to implement and could be more computationally expensive.






On May 31, 2020 at 11:03:23 PM MDT, Mewael <notifications@github.com> wrote:

Could anyone please explain the difference between the contact search radius and contact radius? As far as I know, the contact radius is used to define the distance after which contact forces are experienced between non-similar material points, and it is typically set as 0.9*grid_spacing. If two bodies exist with different grid_spacing, which one would you use to set the contact radius. And, what is the rule of thumb for setting the contact search radius and search frequency?

Thanks alot!

**Comment by sahirbutt** [comment]
For different grid spacings, one can also try to extract the radii from volume of individual points (assuming that they are spheres), i.e. not use a fixed contact radius for all points. 
@djlittl, or does it have some negative implications? I also wanted to ask, why is the contact condition in ShortRangeForceContactModel checking for the **square** of currentDistance and contactRadius, i.e. `if(currentDistanceSquared < contactRadiusSquared)`, why is it not checking for absolute distances?

**Comment by djlittl** [comment]
@sahirbutt, the squared quantity is used only because the sqrt() function is computationally expensive.  If memory serves, if the (currentDistanceSquared < contactRadiusSquared) condition is met, then sqrt(currentDistanceSquared) is computed so that it's available in the force calculation.

Using different contact radii for different points strikes me as a reasonable thing to try.  There are possible negative consequences either way.  Using a fixed value with a graded discretization could result in missed contact and/or interpenetration.  Using a variable value could lead to odd results when planar surfaces are pressed together, for example.

**Comment by sahirbutt** [comment]
Thanks Dave!
I also just realized that for positive numbers, the Distance and DistanceSquare condition is actually equivalent.

**Comment by mewael-isiet** [comment]
Thanks for the help!
