### ISSUE TITLE
Fragment volume

### ISSUE THREAD

**Issue by mewael-isiet** [peridigm/peridigm#125]
In my impact application, a large number number of varying sized fragments are produced after collision. How would I be able to output the volume of each fragment at the end of my timeframe?

**Comment by djlittl** [comment]
I don’t believe this function is implemented in Peridigm.  An algorithm for computing the fragments can be found in this IMECE conference paper:

https://doi.org/10.1115/IMECE2016-65400

You can email me directly if your institution does not have access to IMECE papers.
