### ISSUE TITLE
Critical stretch of interlayer bonds

### ISSUE THREAD

**Issue by Annaovgu** [peridigm/peridigm#127]
Dear Mr. Littlewood,

I have question about critical stretch between two layers. When I solve the fracture mechanics problem with two materials with very different energy release rate: G01>>G02, and pce-crack is located at the boundary of these materials. I would like to know, how Peridigm calculate the critical stretch of these interlayer bonds and what energy release rate is chosen. 

In the book "Handbook of Peridynamic Modeling", p.52  for bond based material is written: The properties of bonds connecting two different materials must be assigned taking into account the properties of both materials. The harmonic average is used here because the two partial bonds can be thought of as two springs “in series” rather than “in parallel.” And formula is 

c*= 2/ (1/c1 + 1/c2)

If c* is not known, it is reasonable to set 
G∗= min{G∗(1),G∗(2)}.

So I would like to know what strategy was implemented in the program and is it possible to change the value of critical stretch of interlayer bonds when I decide to set a strong adhesion between the layers for example.

Thank you in advance for the answer. It would help me a lot!

Best regards
Anna

**Comment by Annaovgu** [comment]
When somebody knows - please give an answer. It would really help!!!

**Comment by andrisfreimanis** [comment]
Peridigm doesn't calculate the critical stretch (CS) value. The user sets the CS value for a block of nodes in the input file (the yaml, xml, txt files). 

You can use the Interface Aware damage model to specify different CS values for two different blocks. And for the nodes that cross the interface the lowest CS value will be used. However, there is a bug in Peridigm (see #119) where it doesn't work. Use the files in pull request #126 to fix it. https://github.com/peridigm/peridigm/pull/126

**Comment by Annaovgu** [comment]
Thank you for the answer. I do not understand 100 percent what this model is used for. As I understand from the description, it is used to remove the brocken bonds from the analysis? 
I would like to ask, can I use this fracture model to set the CS value for the interface between the blocks. For example, a plate consists of two blocks of different materials with different CSes. I need to set the CS for the bonds that bind these blocks (for interface).  That means I have 3 CS values.  Is it possible?

And if yes, how can I use it? In the Block Section I mention Block Names, Material, Damage Model and Horizon. But there is no block for interface.

Is there any literature about  Interface Aware damage model, I can read?

**Comment by andrisfreimanis** [comment]
In Peridigm a block is a group of nodes that have the same material, damage, and contact model. If I understand this correctly, you want to have one CS for material 1, different CS value for material 2, and a third CS value for the interface bonds. 

This is only possible if you use three blocks each with a different CS damage model. Block 1 would have CS value for material 1, block 2 would have CS value for material 2, and the the interface layer would have its own block with its own CS value.

Interface aware damage model is the same as critical stretch, except that when a node and its neighbor have different critical stretch values, it uses the lowest one. I don't know any papers that mention interface aware model, but you can check the code it's basically the same as critical stretch.

**Comment by Annaovgu** [comment]
Thank you for the help. 

The strategy with 3 blocks will not work, because interface layer consist of 2 different materials.

**Comment by djlittl** [comment]
You could perhaps change the code to do what you want.  There is a field called block_id, which you should be able to access within the damage model.  For a given bond, you would then know which blocks the nodes belong to, and you could adjust your damage model accordingly.

Side note:  the critical stretch damage model was proposed in Silling and Askari, "A meshfree method based on the peridynamic model of solid mechanics", Computers and Structures (83), 2005.  It is based on the energy release rate.  It's not clear to me if the assumptions in the original derivation still hold when multiple materials are involved.
