### ISSUE TITLE
PALS model: error when applying any non-zero value in the boundary conditions (explicit solver)

### ISSUE THREAD

**Issue by maxincrease** [peridigm/peridigm#130]
Dear developers,

I am trying to solve a simple task in Peridigm using a PALS material model (with an "elastic" model simulation is successful, then I only changed a material model from "elastic" to "Pals") with an explicit solver specifying initial velocity value for the certain elements (the issue is the same for any type of boundary condition (BC)). If I set a zero value in the BC then simulation is running ok, but if I specify any non-zero value then in several time steps elements fly away from the region of the applied BC and as the result I get the following error:

"/home/max/pnf/peridigm_new_2020/src/core/Peridigm.cpp:1718:

Throw number = 1

Throw test that evaluated to true: !std::isfinite((*force)[i])

**** NaN returned by force evaluation."

If you have any ideas about it, please, let me know.

Thank you in advance,

Maksim

**Comment by oldninja** [comment]
Hi Maksim, I do have the same issue with a model of a simple beam- I don't have any solutions yet or workarounds at the moment. 

In my simulation nothing happens in the first 9 increments, but all of the sudden at increments 10,11,12 the model blows up... I'm simply applying some body forces at the ends nothing fancy. The output is similar to yours "NaN returned by force evaluation."
It would be great to know if there are any limiations on the application of BCs between models or to have some directions from the developement team/someone that solved this issue.

Thanks,

![inc_10](https://user-images.githubusercontent.com/49734546/94350438-6647d500-001c-11eb-8670-2a4d6fd3cdd8.png)
![inc_11](https://user-images.githubusercontent.com/49734546/94350440-6ea01000-001c-11eb-9f2d-ef598ecb0d05.png)
![inc_12](https://user-images.githubusercontent.com/49734546/94350447-76f84b00-001c-11eb-869f-8e43dd0e9f32.png)
