### ISSUE TITLE
Damage Model in Materials with Plasticity 

### ISSUE THREAD

**Issue by APernatii** [peridigm/peridigm#143]
Dear Mr Littlewood,

I have a question, is it possible to use the Elastic Plastic or Elastic Plastic Hardening Models with Critical Stretch Damage Modell. If I understand correctly, СS damade model has a linear dependence "Force - Stretch", and in models with plasticity this is no longer valid.
If I can't use СS model, then which damage model is recomendet to use?

Thank you in advance for your answer. It would help me a lot!

Best regards
Anna

**Comment by jritta** [comment]
@Annaovgu 
I know their is a damage model which is based on the energy ([A mode-dependent energy-based damage model for peridynamics and its implementation.](https://elib.dlr.de/127647/1/EnergyCriterion.pdf)) It was implemented by @CWillberg of DLR. As it is based on the energy I can image that it also works for plasticity models, maybe @CWillberg can give you more details about it and the use of it. 
**But I have to say I NEVER worked with it so far and thus I can NOT assure you that it is also valid for plasticity material models!**

The implementation in Peridigm you find under the following [Link](https://github.com/PeriDoX/PeriDoX/tree/master/Peridigm/Code/Energy_damage_criterion).

Hope that helps!
Best
Jonas

**Comment by oldninja** [comment]
@Annaovgu and @jritta, I tried to use the critical energy damage model referenced above, but I had some issues trying to duplicate some of the curves/plots on the presentations by the DLR, this is the [link to the issue](https://github.com/PeriDoX/PeriDoX/issues/4#issue-793610446). Like I mentioned there, I definitely cannot rule out user errors on my end trying to implement the DLR code into the Peridigm 1.5.0 version.

**Comment by CWillberg** [comment]
@oldninja @Annaovgu @jritta 
The damage model I implemented won't work for plasticity because it suffers from the same problems as the critical stretch. I update it to the current version right now and added some things for the correspondence formulation as well (anisotropy, angles, damage model).
