### ISSUE TITLE
NOXQuasiStatic solver fails with 'Caught unknown exception!' for large model

### ISSUE THREAD

**Issue by jritta** [peridigm/peridigm#144]
**Description**
I want to simulate a model with 2,418,880 discretization points under quasi-static conditions. For this purpose I use the NOX solver. When I run the simulation the tangent matrix is successfully allocated followed by the start of the NOX solver. Than the simulation "crashes" with throwing the exception `Caught unknown exception!`. The MPI processes continue to run, but there is no output to the command line, nor is there any writing to the output files.

**System**
* CentOS 7.9.2009
* Trilinos 12.14.1
* Intel compiler 17.0.5 (and MKL)

**Error Message**
 `Caught unknown exception!`

**Additional context**
I tried to isolate the error in the code. It is likely that the problem arises at the point of the '[NOX step call](https://github.com/peridigm/peridigm/blob/cb9979dd5c83e842b130b147c44714be2dce28b3/src/core/Peridigm.cpp#L2536)' in the while-loop. Furthermore, an integer overflow emerges (I have 11,689,514,856 nonzeros) when the data about the allocated tangent matrix is [dumped](https://github.com/peridigm/peridigm/blob/cb9979dd5c83e842b130b147c44714be2dce28b3/src/core/Peridigm.cpp#L776) to the command line. This can easily be fixed by using the 64bit call of `NumGlobalNonzeros()`.

@djlittl: Since you know the code very well, do you may have an idea where the problem could be? I thought of an internal integer overflow but I have not been able to identify one so far. All counters in the loops I checked were far from the `MAX_INT` value, this is because the single MPI processes operate only on their local index range. Can you think about a variable or a part in the Peridigm code where an integer overflow could happen? Or could it be, that the NOX solver has an internal problem with the amount of nonzeros? I just found 64bit support in Trlinos for the [Epetra package](https://trilinos.github.io/pdfs/Epetra64HowTo.pdf).

I would appreciate any help and suggestion!

Best
Jonas

**Comment by djlittl** [comment]
That’s a lot of nonzeros, Jonas.

I suspect that you’re correct about an integer overflow.  The difficulty is, it could be buried deep within one of the Trilinos packages.  Strikes me as potentially quite difficult to debug.

A pretty obvious thing that you’ve probably already tried is to cut the problem size by an order of magnitude and see if it runs, and then slowly ramp it up.  You could at least monitor memory usage this way as the problem size increases.  It’s conceivable that you’re simply running out of memory, at least this way you’d see it coming.  And I’d keep the horizon pretty small, maybe two times the mesh spacing, just to keep the number of neighbors as low as possible.

Have you tried the Matrix Free solver option in NOX?  It might be your best bet here.

Here’s an example.  The formatting is copy-and-pasted from an old input deck with the *.peridigm format, you’ll need to convert to *.yaml.
Solver
    Verbose "false"
    Initial Time 0.0
    Final Time 1.0
    Peridigm Preconditioner "None"
    NOXQuasiStatic
        Nonlinear Solver "Line Search Based"
        Number of Load Steps 1
        Max Solver Iterations 100
        Relative Tolerance 1.0e-6
        Max Age Of Prec 100
        Direction
            Method "Newton"
            Newton
              Linear Solver
                  Jacobian Operator "Matrix-Free"
                  Preconditioner "None"
        Line Search
            Method "Polynomial”

See also the various input decks in peridigm/test/regression/NOX_QS/

As the name implies, this option does not form the matrix, so if the issue you’re seeing is tied to the matrix this should help.  I never got a chance to test the matrix free option thoroughly, but all my initial results were very promising.  Huge speed-ups in some cases.

Dave

**Comment by jritta** [comment]
@djlittl Thank you so much for your suggestions!

Since the classical Newton approach did not converge on a similar, but far smaller (363,120 discretization points) problem, I dug into the possible NOX solver options and end up with a Trust-Region Method. First, I thought it is related to the not "officially" supported solver by Peridigm. Thus, for testing purposes, I used the following set of solver options:
```code
Initial Time: 0.0
Final Time: 1.0
Jacobian Diagnostics: false
NOXQuasiStatic:
    Verbose: false
    Nonlinear Solver: "Line Search Based"
    Number of Load Steps: 1000
    Max Solver Iterations: 100
    Relative Tolerance: 1.0e-5
    Printing:
        Output Precision: 20
        Output Processor: 0
    Line Search:
        Method: "Polynomial"
    Direction:
        Method: "Newton"
        Newton:
            Linear Solver:
                Aztec Solver: "GMRES"
                Preconditioner: "AztecOO"
                AztecOO Preconditioner Iterations: 15
                Max Iterations: 40
                Aztec Preconditioner: "Jacobi"
                Max Age Of Prec: 1
```
But even then the same problem occurred.
The memory I already checked and non of the computation nodes I use run out of memory during computation.
Now, I will test your suggested solver options on the problem. Then I will also decrease the size of the problem (starting with the size I know it works) and slowly increase it to get the nonzeros-value as close as possible to the `MAX_INT` value. This should perhaps give me and indication whether the problem is related to the number of nonzeros.

I will keep you informed!

Cheers
Jonas

**Comment by jritta** [comment]
@djlittl I tested your mentioned solver options and it worked with those. So I deduce the problem is likely tied to the matrix.
Nevertheless, I will try to investigate that in more detail by getting close to the `MAX_INT` value as I think that could be maybe interesting for others or also helpful for further development.

**Comment by jritta** [comment]
I did some more investigations on the problem. It is somehow mysterious since it seems not to follow strictly the direction of a higher number of nonzeros the more likely causes in a crash (`Caught unknown exception!`).
I have a simulation setup with 1,901,763,127 nonzeros which works with the following solver options:
```code
Initial Time: 0.0
Final Time: 1.0
Jacobian Diagnostics: false
NOXQuasiStatic:
    Verbose: false
    Nonlinear Solver: "Trust Region Based"
    Number of Load Steps: 1000
    Max Solver Iterations: 1000
    Relative Tolerance: 1.0e-5
    Printing:
        Output Precision: 20
        Output Processor: 0
    Direction:
        Method: "Newton"
        Newton:
            Linear Solver:
                Aztec Solver: "GMRES"
                Size of Krylov Subspace: 500
                Orthogonalization: "Modified"
                Jacobian Operator: "Matrix-Free"
    Cauchy Direction:
        Method: "Steepest Descent"
        Steepest Descent:
            Scaling Type: "Quadratic Model Min"
    Solver Options:
        Status Test Check Type: "Minimal"
```
the same setup with just a bond filter (which causes less nonzeros, i.d. 1,773,927,991 number of nonzeros) crashes with `Caught unknown exception!`. For both simulations the number of nonzeros is less than the value of `MAX_INT`. I have absolutely no clue were the problem comes from... It seems that is is somehow related to the size of the tangent matrix, but not like that that I can determine a size where it suddenly fails.

@djlittl Your proposed solver setup works on the problem (both with and without a bond filter) but it just works because of the following option: `Peridigm Preconditioner: "None"`. This sets internally a flag so that not the full tangent is allocated, rather than a block diagonal jacobian (which causes a less value of nonzeros). If this option is not set in your proposed solver setup, the full tangent is allocated and the simulation crashes as well. I tried to use this option with my solver setup (using a Trust Region Based solver). 
```code
Initial Time: 0.0
Final Time: 1.0
Jacobian Diagnostics: false
Peridigm Preconditioner: "None"
NOXQuasiStatic:
    Verbose: false
    Nonlinear Solver: "Trust Region Based"
    Number of Load Steps: 1000
    Max Solver Iterations: 100
    Relative Tolerance: 1.0e-5
    Printing:
        Output Precision: 20
        Output Processor: 0
    Direction:
        Method: "Newton"
        Newton:
            Linear Solver:
                Aztec Solver: "GMRES"
                Size of Krylov Subspace: 500
                Orthogonalization: "Modified"
                Jacobian Operator: "Matrix-Free"
    Cauchy Direction:
        Method: "Steepest Descent"
        Steepest Descent:
            Scaling Type: "Quadratic Model Min"
    Solver Options:
        Status Test Check Type: "Minimal"
```
Unfortunately, this did not work because I get the following error message `ERROR: NOX::Epetra::MatrixFree::SetUseTranspose() - Transpose is unavailable in Matrix-Free mode!` and in addtion from every MPI process a `Caught unknown exception!`. Do you may have an idea how I can fix that? I want to stick to the Trust Region Based solver because the Line Search Based algorithm does not convert on my problem after a few load steps.

**Comment by jritta** [comment]
The problem rises from the discretization I used. I had 'isolated' discretization points in my geometry which are problematic when a stiffness matrix will be calculated since no forces are exerted on it. In consequence the calculation of the corresponding tangent matrix entry breaks down. For explicit solver this is irrelevant because a discretization point on which no force acts does simply not move until a force acts on it.

Thanks for all your contributions to identify the issue! :+1: 

Best,
Jonas
