### ISSUE TITLE
NaN exception

### ISSUE THREAD

**Issue by CWillberg** [peridigm/peridigm#148]
TEUCHOS_TEST_FOR_EXCEPT_MSG does not work properly if NaN error occurs only on one core.

A solution is to change TEUCHOS_TEST_FOR_EXCEPT_MSG 

to 

TEUCHOS_TEST_FOR_TERMINATION(terminate_test, msg)

**Comment by jritta** [comment]
@CWillberg very interesting and good to know. 
Can you please describe how this manifests itself when this happens?
Because I think when one MPI process fails all other fail as well, right? And I expect, if one `NaN` occurs and is 'not detected' by this MPI process it will 'propagate' throughout the domain and finally the simulation crash, or?

**Comment by CWillberg** [comment]
@jritta It happens on our cluster if NaN occurs not on all CPUs. This CPU is stopped by the Teuchos call and the others wait. I had to stop the analysis manually. The Termination call by Teuchos kills all MPI processes.

**Comment by jritta** [comment]
@CWillberg ok I see, thank you for your explanation.
@djlittl I think this behavior should be changed in favor of a more robust code, right?

**Comment by djlittl** [comment]
I certainly have no objections if someone would like to change this.  The suggestion seems like a good one.

Dave

From: Jonas ***@***.***>
Reply-To: peridigm/peridigm ***@***.***>
Date: Thursday, March 25, 2021 at 4:01 AM
To: peridigm/peridigm ***@***.***>
Cc: "Littlewood, David John" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [peridigm/peridigm] NaN exception (#148)


@CWillberg<https://github.com/CWillberg> ok I see, thank you for your explanation.
@djlittl<https://github.com/djlittl> I think this behavior should be changed in favor of a more robust code, right?

**Comment by jritta** [comment]
I won't have the time to fix this in the near future. Maybe it would be a good idea to collect somewhere all the tasks that have to be done.
For this particular problem: The exception call must be changed for all cases where state variables are tested (like force, displacement, contact force etc.), right?
