### ISSUE TITLE
Getting error when doing the "make -j 12" command. 

### ISSUE THREAD

**Issue by bdas123** [peridigm/peridigm#150]
I am getting the following error when doing the "make -j 12" command. I turned Adelus on inside my Trilinos file. 

`make[1]: *** [src/CMakeFiles/PeridigmLib.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/pdneigh/unit_test/ut_kdtree_rectangular_search] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_kdtree_rectangular_search.dir/all] Error 2
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_Q2CylinderRingHorizon] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_Q2CylinderRingHorizon.dir/all] Error 2
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_QuickGrid_solidCylinder_np2] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_QuickGrid_solidCylinder_np2.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/pdneigh/unit_test/ut_kdtree_spherical_search] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_kdtree_spherical_search.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_QuickGrid_solidCylinder_np1] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_QuickGrid_solidCylinder_np1.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_QuickGridMPI_np3] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_QuickGridMPI_np3.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_SmallMeshCylinder_np4] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_SmallMeshCylinder_np4.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/mesh_input/quick_grid/unit_test/ut_QuickGridHorizon] Error 1
make[1]: *** [src/io/mesh_input/quick_grid/unit_test/CMakeFiles/ut_QuickGridHorizon.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/pdneigh/unit_test/ut_point] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_point.dir/all] Error 2
make: *** [all] Error 2`

**Comment by oldninja** [comment]
@bdas123 do you need Adelus on Trilinos? Could you try deactivating it and recompile trilinos and then peridigm?

**Comment by bdas123** [comment]
@oldninja I deactivated Adelus and got further ahead in my make -j 12. (13% to 22%)

**Comment by oldninja** [comment]
@bdas123 did you clean both directories? `make clean` or simply delete the build directories.
Which version of trilinos are you using?

**Comment by bdas123** [comment]
@oldninja How do I check the version of Trilinos?

Here is what I did. 
1) Go into Trilinos/build folder
2) `make clean`
3) bash shell script
4) `make -j 12`
5) `make`
6) Go into peridigm/build folder
7) bash shell script
8) `make -j 12`

However, I received the following error after implementing the `make -j 12` command. 

`[ 27%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_DataManager.cpp.o
compilation aborted for /home1/07571/barundas/Scratch/peridigm/src/core/Peridigm_BoundaryAndInitialConditionManager.cpp (code 2)
make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm_BoundaryAndInitialConditionManager.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
compilation aborted for /home1/07571/barundas/Scratch/peridigm/src/core/Peridigm_BoundaryCondition.cpp (code 2)
make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm_BoundaryCondition.cpp.o] Error 2
compilation aborted for /home1/07571/barundas/Scratch/peridigm/src/core/Peridigm.cpp (code 2)
make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm.cpp.o] Error 2
[ 27%] Built target ut_point
make[1]: *** [src/CMakeFiles/PeridigmLib.dir/all] Error 2
[ 27%] Built target ut_kdtree_spherical_search
[ 27%] Built target ut_kdtree_rectangular_search`

**Comment by bdas123** [comment]
Never mind, I found it. I am using Trilinos version 13.1

**Comment by oldninja** [comment]
I've used only older versions of trilinos to install peridigm- I haven't tested 13.1 for sure. 
Could you try [trilinos-12.12.1](https://github.com/trilinos/Trilinos/archive/refs/tags/trilinos-release-12-12-1.tar.gz) and follow the installation guide from the [PeriDoX](https://github.com/PeriDoX/PeriDoX/blob/master/Doc/Peridigm_Installation_Guide/Peridigm_Installation_Guide.pdf) repository?

**Comment by bdas123** [comment]
Getting errors with trilinos-12.12.1

**Comment by bdas123** [comment]
```
compilation aborted for /home1/07571/barundas/Scratch/peridigm/src/core/Peridigm_BoundaryAndInitialConditionManager.cpp (code 2)
make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm_BoundaryAndInitialConditionManager.cpp.o] Error 2
make[2]: *** Waiting for unfinished jobs....
compilation aborted for /home1/07571/barundas/Scratch/peridigm/src/core/Peridigm_BoundaryCondition.cpp (code 2)
make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm_BoundaryCondition.cpp.o] Error 2
compilation aborted for /home1/07571/barundas/Scratch/peridigm/src/core/Peridigm.cpp (code 2)
make[2]: *** [src/CMakeFiles/PeridigmLib.dir/core/Peridigm.cpp.o] Error 2
make[1]: *** [src/CMakeFiles/PeridigmLib.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/pdneigh/unit_test/ut_point] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_point.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/pdneigh/unit_test/ut_kdtree_rectangular_search] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_kdtree_rectangular_search.dir/all] Error 2
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_row'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::nprocs_col'
/home1/07571/barundas/projects/trilinos/lib/libzadelus.so.13.1: undefined reference to `Adelus::me'
make[2]: *** [src/io/pdneigh/unit_test/ut_kdtree_spherical_search] Error 1
make[1]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_kdtree_spherical_search.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by oldninja** [comment]
It looks like Adelus is the issue again? Could you share your cmake file? To see what's going on...  Did you follow the instructions on the pdf file I referenced?

**Comment by jritta** [comment]
The Adelus package does not exist in version 12.12.1...
Peridigm with the Trilinos version 13.0.0 works for me without any problems.

I  suggest to send us full log, may be the problem occurs already earlier...

**Comment by bdas123** [comment]
@oldninja , is this what you are referring to?

```
# Install script for directory: /home1/07571/barundas/Scratch/peridigm

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home1/07571/barundas/projects/Peridigm")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "0")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/opt/apps/gcc/6.3.0/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home1/07571/barundas/Scratch/peridigm/build/src/cmake_install.cmake")
  include("/home1/07571/barundas/Scratch/peridigm/build/test/regression/cmake_install.cmake")
  include("/home1/07571/barundas/Scratch/peridigm/build/test/verification/cmake_install.cmake")
  include("/home1/07571/barundas/Scratch/peridigm/build/test/performance/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/home1/07571/barundas/Scratch/peridigm/build/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")

```

**Comment by oldninja** [comment]
@bdas123  not really. Could you open the *.pdf from [Peridox repo](https://github.com/PeriDoX/PeriDoX/blob/master/Doc/Peridigm_Installation_Guide/Peridigm_Installation_Guide.pdf) and go to section 3.4.4. Trilinos?

**Comment by bdas123** [comment]
@oldninja Just went to the section you are talking about.

**Comment by oldninja** [comment]
I want to see these files: cmake_trilinos.cmake & cmakeopts.log

**Comment by jritta** [comment]
@bdas123 Do you compile with C++11 standard!?

**Comment by bdas123** [comment]
@jritta I'm still new to this. How do I check the version of C++?

**Comment by oldninja** [comment]
Type this on your bash: ``gcc --version``
But then you need to supply the information on your CMake file in the form of a cxx flag:
``-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \``

**Comment by jritta** [comment]
Ok, no problem. This depends on the compiler you use, e.g. for the gcc compiler you can set the standard by the command line flag `-std=c++11` (see [here](https://gcc.gnu.org/projects/cxx-status.html#cxx11) for details)

**Comment by jritta** [comment]
Maybe you can also provide us more details about your system (OS, compiler you use, versions etc.)

**Comment by bdas123** [comment]
> I want to see these files: cmake_trilinos.cmake & cmakeopts.log

@oldninja , I have attached the shell script and the cmakeopts.log file. 

[cmakeopts.log](https://github.com/peridigm/peridigm/files/6436357/cmakeopts.log)
[trilinos-stampede-intel-cmake.docx](https://github.com/peridigm/peridigm/files/6436359/trilinos-stampede-intel-cmake.docx)

**Comment by bdas123** [comment]
So @oldninja and @jritta , Here is what I get when I command `gcc --version`.

```
login3.stampede2(1067)$ gcc --version
gcc (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by bdas123** [comment]
> Maybe you can also provide us more details about your system (OS, compiler you use, versions etc.)

@jritta , I am using the Stampede2 supercomputer at UT Austin. If you want, I can ask the admins the specifications of Stampede2.

**Comment by jritta** [comment]
Ok that is a relatively old version of gcc, you have definitely set the `-std=c++11` flag manually as mentioned by @oldninja 

You can provide us details about the system by calling `uname -a`.

**Comment by bdas123** [comment]
@jritta, here you go. 

```
login3.stampede2(1068)$ uname -a
Linux login3.stampede2.tacc.utexas.edu 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jritta** [comment]
It is a Red Hat 7 system and it seems you have also other versions of gcc [available](https://portal.tacc.utexas.edu/user-guides/stampede2#using-modules) if you need...

**Comment by oldninja** [comment]
@bdas123 it looks like you may be mixing Intel and gcc compilers... From your cmakeopts.txt ``-- Leaving current CMAKE_CXX_COMPILER=/opt/apps/intel18/impi/18.0.2/bin/mpicxx since it is already set!``
Maybe we need to make sure everything is installed with the same compiler - either intel or gcc.

**Comment by bdas123** [comment]
@oldninja , sounds good, mate.

**Comment by bdas123** [comment]
> It is a Red Hat 7 system and it seems you have also other versions of gcc [available](https://portal.tacc.utexas.edu/user-guides/stampede2#using-modules) if you need...

@ So @jritta , which gcc version do you suggest I switch to?

**Comment by jritta** [comment]
I suggest also to compile Trilinos with only the packages mentioned by the [PeriDoX](https://github.com/PeriDoX/PeriDoX/blob/master/Doc/Peridigm_Installation_Guide/Peridigm_Installation_Guide.pdf) guide.

Your list is quit comprehensive: 
```
Gtest KokkosCore KokkosContainers KokkosAlgorithms Kokkos TeuchosCore 
TeuchosParser TeuchosParameterList TeuchosComm TeuchosNumerics 
TeuchosRemainder TeuchosKokkosCompat TeuchosKokkosComm Teuchos 
KokkosKernels RTOp Sacado MiniTensor Epetra Zoltan Shards Triutils EpetraExt 
TpetraClassic TpetraTSQR TpetraCore Tpetra TrilinosSS Domi ThyraCore 
ThyraEpetraAdapters ThyraEpetraExtAdapters ThyraTpetraAdapters Thyra Xpetra 
Isorropia Pliris AztecOO Galeri Amesos Pamgen Zoltan2Core Ifpack ML Belos 
ShyLU_NodeHTS ShyLU_NodeTacho ShyLU_Node Amesos2 SEACASExodus 
SEACASExodus_for SEACASExoIIv2for32 SEACASNemesis SEACASIoss 
SEACASChaco SEACASAprepro_lib SEACASSupes SEACASSuplib 
SEACASSuplibC SEACASSuplibCpp SEACASSVDI SEACASPLT SEACASAlgebra
 SEACASAprepro SEACASBlot SEACASConjoin SEACASEjoin SEACASEpu 
SEACASExodiff SEACASExomatlab SEACASExotxt SEACASExo_format 
SEACASEx1ex2v2 SEACASFastq SEACASGjoin SEACASGen3D 
SEACASGenshell SEACASGrepos SEACASExplore SEACASMapvarlib 
SEACASMapvar SEACASMapvar-kd SEACASNas2exo SEACASZellij 
SEACASNemslice SEACASNemspread SEACASNumbers SEACASTxtexo 
SEACASEx2ex1v2 SEACAS Komplex Anasazi Ifpack2 Stratimikos Teko Intrepid 
Intrepid2 Phalanx NOX Moertel MueLu Zoltan2Sphynx Zoltan2 ShyLU_DDBDDC 
ShyLU_DDFROSch ShyLU_DDCommon ShyLU_DD ShyLU Rythmos Tempus 
Stokhos ROL Piro Adelus TrilinosCouplings PikeBlackBox PikeImplicit Pike 118
```

**Comment by oldninja** [comment]
@bdas123  Also, watch out for BLAS/LAPACK and other libraries (no need boost anymore) - those may be compiled with Intel on the system and you may need to recompile with gcc on your own directories. 
When I installed peridigm on the HPC at my university, I recompiled everything at the same gcc compiler to avoid issues.

**Comment by jritta** [comment]
> So @jritta , which gcc version do you suggest I switch to?

The newest which is available. I use `gcc (GCC) 10.2.1 20201125`, but that shouldn't cause in a problem. More important is, that you compile with the *C++11* standard.

**Comment by jritta** [comment]
> those may be compiled with Intel on the system and you may need to recompile with gcc on your own directories.

Or you just compile trilinos with the IntelMKL if you use an intel compiler

**Comment by bdas123** [comment]
@jritta So here is the versions of gcc that are available. 

```
login3.stampede2(1073)$ module spider gcc

------------------------------------------
  gcc:
------------------------------------------
     Versions:
        gcc/5.4.0
        gcc/6.3.0
        gcc/7.1.0
        gcc/7.3.0
        gcc/9.1.0
```

**Comment by oldninja** [comment]
No, the list of installed packages inside trilinos. It should be on your cmake_trilinos.cmake

**Comment by bdas123** [comment]
@oldninja , okay. Looking at it right now.

**Comment by oldninja** [comment]
A.4. Trilinos on the Peridox pdf.

**Comment by jritta** [comment]
On page 58 of the PeriDoX Guide you will find a build script for Trilinos

**Comment by bdas123** [comment]
By the way, here is what I got when I loaded gcc/9.1.0. 

l```
login3.stampede2(1075)$ module load gcc/9.1.0

Lmod is automatically replacing
"intel/18.0.2" with "gcc/9.1.0".


Inactive Modules:
  1) boost     2) netcdf     3) python2

The following have been reloaded with a version change:
  1) impi/18.0.2 => impi/19.0.9
```

**Comment by jritta** [comment]
This just informs you that the module IntelMPI version 19.0.9 is loaded. This likely caused by an incompatibility of the gcc 9.1.0 with the IntelMPI version 18.0.2.
Please follow now first the PeriDoX guide as mentioned several times and then we can discuss further emerging problems. In this guide Martin Rädel nicely describes the installation process with all dependences and even provided build scripts which you might just have to adapt to your needs but they serves as a very good starting point.
When you have questions to the guide you can ask us and we might can help you.

**Comment by bdas123** [comment]
Cool, thanks. I'll follow the guide. 

I'm actually trying to create a guide for installing Peridigm onto Stampede 2 at UT Austin. I hope to create this guide 3x a year (Spring, Summer, and Fall).

**Comment by jritta** [comment]
Great! This will be a big help for upcoming users of Peridigm on the cluster :blush: 
When you once figure it out you just have to adapt it, what won't be that time consuming :+1:

**Comment by bdas123** [comment]
I am getting this error when I'm following the Peridigm guide you provided
` The system is: Linux - 3.10.0-957.5.1.el7.x86_64 - x86_64`

**Comment by oldninja** [comment]
@bdas123 when does this occurs? At what point on the installation or run?

**Comment by jritta** [comment]
Ok, this seems for me not to be an error message.
I think you should provide us much more information. At which point of the installation process do you get this message? Is this the only text of the error message? What did you exactly do?

**Comment by bdas123** [comment]
So here is what I did. 

1) I created the file cmake_trilinos.cmake by copy and pasting the code on Page 58 of the Peridigm guide. I made some modifications. I attached the file to this comment. 

2) `chmod u+x cmake_trilinos.cmake`

3) `./cmake_trilinos.cmake`

4) Got the error, which is found in CMakeOutput. 
[cmake_trilinos.pdf](https://github.com/peridigm/peridigm/files/6446192/cmake_trilinos.pdf)
[CMakeOutput.txt](https://github.com/peridigm/peridigm/files/6446193/CMakeOutput.txt)

**Comment by jritta** [comment]
Look at page 60 of the guide. Your `cmake_trilinos.cmake` is not complete, the path to the source files is missing...

**Comment by oldninja** [comment]
Also, you don't need to load the modules.
