### ISSUE TITLE
Error: computeShapeTensorInverseAndApproximateVelocityGradient: Non-invertible matrix

### ISSUE THREAD

**Issue by bdas123** [peridigm/peridigm#152]
What are some reasons you all have seen that explain this error?

**Comment by johntfoster** [comment]
Likely because too many bonds have been broken and the Shape Tensor becomes
singular.

**Comment by djlittl** [comment]
I agree with John.  Too few bonds results in a singular shape tensor.  This could also result from setting the horizon too small, which would cause the simulation to fail immediately.  If the failure occurs in the middle of the simulation, then it's probably bond failure, as John said.

A workaround would be to decay the stress as the percentage of broken bonds increases, and then when you reach the point of having too few bonds, just set the stress to zero.  This is obviously hackish, but might yield reasonable results.  Note that the general reliability of the shape tensor decreases as bonds break.  Point being, even if the matrix is not singular, the resulting approximate deformation gradient might be nonsense if many bonds are broken and the deformation field varies a lot over the neighborhood.
