### ISSUE TITLE
Parallele Issue

### ISSUE THREAD

**Issue by Juliendu33** [peridigm/peridigm#16]
Hello, 

I currently work on the establishment of your Peridigm code. 

I will wish to carry out calculations in parallels. However, voice the error message which I obtain when I launch a calculation in parallel:

-- Peridigm
-- version 1.4.1

MPI initialized on 2 processors.
/users/sherpa/appli/peridigm/Peridigm/src/io/discretization/Peridigm_TextFileDiscretization.cpp:171:
Throw number = 1
Throw test that evaluated to true: !inFile.is_open()
***\* Error opening discretization text file.
[molx1210:9368] **\* An error occurred in MPI_Allreduce
[molx1210:9368] **\* reported by process [3607494657,47145856008193]
[molx1210:9368] **\* on communicator MPI_COMM_WORLD
[molx1210:9368] **\* MPI_ERR_IN_STATUS: error code in status
[molx1210:9368] **\* MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[molx1210:9368] **\*    and potentially your MPI job)

This example comes from the example "Fragmenting_Cylinder". 

What must I make to solve the problem, which seems to come from file « discretization text file »? 
I thank you by advance.
Cordially

**Comment by MDBrothers** [comment]
@Juliendu33 
This looks like what happens when you put the wrong filename for your discretization into the input deck.

Please post the output of the "ls" command in the directory your input deck and mesh files are in. Also post your input deck.

**Comment by Juliendu33** [comment]
Hello, 

Thank you for your answers.
I have, after the installation makes turn the various cases test (verification/regression/performance).
Individually and without paralleling calculations, these various cases function very well. 

Because I do not see how the routine launch "make check" (I started in computation and programming), that's why I did the test cases one by one.

On the other hand as soon as I want to launch calculations in parallel, I have a problem.
I use the following routine: 

source /appli/gcc/4.8.4/conf_gcc4.8.4
source /appli/intel/conf_v16.3.csh
setenv LD_LIBRARY_PATH /appli/mpi/openmpi/1.8.5_SMP/lib:/appli/peridigm/linuxo/boost/lib:/appli/peridigm/linuxo/hdf5/lib:/appli/peridigm/linuxo/matio/lib:/appli/peridigm/linuxo/netcdf/lib:/appli/peridigm/linuxo/trilinos/lib:$LD_LIBRARY_PATH
setenv PATH /appli/mpi/openmpi/1.8.5_SMP/bin:$PATH

mpirun -n 1 /appli/peridigm/linuxo3/peridigm/bin/Peridigm PERIDYGM_DATA/test/regression/Contact_Perforation/Contact_Perforation.xml
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
For example, if I want to start the test “ElasticPlasticCorrespondenceFullyPrescribedTension “ with 4 processors here the error message which I obtain. However in the repertoire there is well the whole of the files necessary:
mpirun -n 4 /appli/peridigm/linuxo3/peridigm/bin/Peridigm PERIDYGM_DATA/test/verification/ ElasticPlasticCorrespondenceFullyPrescribedTension/ElasticPlasticCorrespondenceFullyPrescribedTension.xml

molx1210 {a002271} 535: cd ElasticPlasticCorrespondenceFullyPrescribedTension/
molx1210 {a002271} 536: ls
ElasticPlasticCorrespondenceFullyPrescribedTension.comp*
ElasticPlasticCorrespondenceFullyPrescribedTension.e
ElasticPlasticCorrespondenceFullyPrescribedTension.g*
ElasticPlasticCorrespondenceFullyPrescribedTension.g.4.0*
ElasticPlasticCorrespondenceFullyPrescribedTension.g.4.1*
ElasticPlasticCorrespondenceFullyPrescribedTension.g.4.2*
ElasticPlasticCorrespondenceFullyPrescribedTension.g.4.3*
ElasticPlasticCorrespondenceFullyPrescribedTension.h*
ElasticPlasticCorrespondenceFullyPrescribedTension.jou*
ElasticPlasticCorrespondenceFullyPrescribedTension.xml*
ElasticPlasticCorrespondenceFullyPrescribedTension_gold.e*
Solution Test-Solution Gold-Step 1-Unrotated Rate of deformation X.PNG*
exoplot.py*
np1/
np4/
plots.ipynb*
molx1210 {a002271} 537:

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
And here the error message which I obtain:
molx1210 {a002271} 515: ls                                            
Desktop/  PERIDYGM_DATA/  peridigm*  peridigm~*  peridigm~~*          
molx1210 {a002271} 516: peridigm~                                     

-- Peridigm
-- version 1.4.1

MPI initialized on 4 processors.

****Error on processor 3: unable to open file ElasticPlasticCorrespondenceFullyPrescribedTension.g.4.3                                                          

****Error on processor 1: unable to open file ElasticPlasticCorrespondenceFullyPrescribedTension.g.4.1                                                          

****Error on processor 2: unable to open file ElasticPlasticCorrespondenceFullyPrescribedTension.g.4.2                                                          

****Error on processor 0: unable to open file ElasticPlasticCorrespondenceFullyPrescribedTension.g.4.0                                                          

/users/sherpa/appli/peridigm/Peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1130:                                                             

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #3: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)                                             
/users/sherpa/appli/peridigm/Peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1130:                                                             

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #1: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)
/users/sherpa/appli/peridigm/Peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1130:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #0: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)
/users/sherpa/appli/peridigm/Peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1130:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #2: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)
Wallclock Time (seconds):
                     Min            Max            Ave
  Total            0.037          0.037          0.037

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[64011,1],3]
  Exit code:    10

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Hoping that enables you to help me.

Thank you

**Comment by djlittl** [comment]
You can run the entire test suite from the build directory with “make test”.

As for your parallel run, it appears that the job manager isn’t able to find the mesh files.  Perhaps it would work if you put the full path to the mesh file in your input deck.  That is, replace

<Parameter name="Input Mesh File" type="string" value="ElasticPlasticCorrespondenceFullyPrescribedTension.g"/>

with

<Parameter name="Input Mesh File" type="string" value="PERIDYGM_DATA/test/verification/ElasticPlasticCorrespondenceFullyPrescribedTension/ElasticPlasticCorrespondenceFullyPrescribedTension.g"/>

I’m assuming that PERIDYGM_DATA is a variable that your job manager will be able to decipher.  You might want to just put in the full path without any variables to avoid possible glitches with that.

Either that, or you need to figure out how to change the working directory in your job submission script.  This is something that’s specific to the job manager on your system.  I suppose you might be able to just put “cd PERIDYGM_DATA/test/verification/” in the script.

Best,
Dave

**Comment by Juliendu33** [comment]
Hello 

Thank you for your answers. The problem of parallelization is solved. It was indeed a problem of access path to find the files of mesh.

Thanks
Best
Julien

**Comment by anhvt2** [comment]
Dear Dr. Littlewood,

I also have an issue in parallelization. For example, in the twist_and_pull example, if I use the `mpirun` command, then it will produce an error. No problem is found for sequential run, i.e. `mpirun -np 1 Peridigm twist_and_pull.peridigm`.

I did try to put the whole path into the input deck, but it doesn't work. Please kindly advise or let me know if you have any further question.

Many thanks,
Anh 

```

twist_and_pull$ mpirun -np 4 Peridigm twist_and_pull.peridigm 

-- Peridigm
-- version 1.5.0 (Dev)

MPI initialized on 4 processors.

WARNING!! Peridigms text file input is deprecated and will be 
 removed in a future version.  You may consider installing Trilinos 
 with the optional TPL_ENABLE_yaml-cpp and convert the *.peridigm input 
 to *.yaml, for a similar markup.  Otherwise use the XML input format.


****Error on processor 1: unable to open file twist_and_pull.g.4.1


****Error on processor 0: unable to open file twist_and_pull.g.4.0


****Error on processor 3: unable to open file twist_and_pull.g.4.3

/media/anhvt89/seagateRepo/Peridigm/peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1131:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #3: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)
/media/anhvt89/seagateRepo/Peridigm/peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1131:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #0: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)

****Error on processor 2: unable to open file twist_and_pull.g.4.2

/media/anhvt89/seagateRepo/Peridigm/peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1131:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #1: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)
/media/anhvt89/seagateRepo/Peridigm/peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1131:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #2: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)
Wallclock Time (seconds):
                     Min            Max            Ave
  Total            0.022          0.024          0.023

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[52928,1],0]
  Exit code:    10
--------------------------------------------------------------------------

```

**Comment by anhvt2** [comment]
i think i found the problem. the solution is described here: https://peridigm.sandia.gov/content/running-simulations-peridigm

need to `decomp -p 4 my_mesh.g` where `decomp` is somewhere in `/usr/local/trilinos/bin/decomp`
