### ISSUE TITLE
How to use peridigm to get model's discretization file

### ISSUE THREAD

**Issue by Coooooco** [peridigm/peridigm#167]
I read the  2018 users guide but still don't get it.

Does anyone know?

Thanks a lot!

**Comment by Coooooco** [comment]
Thanks for replying me!

After I read the 2018 users guide, I tried to use Peridigm to get a text discretization file,but didn‘t find the proper way. 

Could you please tell me how to create a  text discretization file?

By the way, I notice that the Cubit is for Sandia users only, are there any alternative software you recommand?

Thank again :-)

**Comment by oldninja** [comment]
Hi @Coooooco , you can create a text discretization in whichever way you want (using MATLAB, python, or even by hand). You only need to supply the x,y,z coordinates of the point, the ID of the block it will pertain to, and the volume (if I recall correctly). A simple example is provided here: [Wave in Bar example](https://github.com/peridigm/peridigm/blob/master/examples/wave_in_bar/wave_in_bar.txt)

You, as the user, have to create this file and make it available to Peridigm.
