### ISSUE TITLE
Peridigm Installation on Cluster

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#180]
I am trying to install peridigm using the installation guide given by  @diehlpk on his blog for Ubuntu 16 but I am installing it on Ubuntu 20.04 and after following all the steps I witnessed following error while building Peridigm:

-- Performance testing is NOT enabled.

-- LCM is NOT enabled.

-- CJL is NOT enabled.

-- SANDIA_INTERNAL is NOT enabled.

-- PV is NOT enabled.

And finally there is no makefile in order to install in the build directory.Any help in this regard will be helpful.

**Comment by ppandit95** [comment]
Actually I had not compiled Trilinos with YAML Reader as well as I must have changed the order of installation of third part applications due to which I faced such an issue but when I recompiled all the required dependencies I managed to successfully install peridigm .Thanks @diehlpk  for providing an elaborate step by step guide to installation.But to my surprise whenever Peridigm starts it says "No Protocol found" and then lists "Peridigm Version 1.5(dev)" although all the tests are passing and example simulations are working fine.

**Comment by sfeister** [comment]
I just want to add that @diehlpk your guide was *very* helpful even in 2022 -- especially the part with decomp for parallel processing! Here's a direct link to that guide: https://www.diehlpk.de/blog/builing-peridigm/

**Comment by sfeister** [comment]
@ppandit95 My installation does the same thing with:

```
No protocol specified

-- Peridigm
-- version 1.5.0 (Dev)
```

**Comment by sfeister** [comment]
For posterity, here are the packages I used in Ubuntu 20.04:
- build-essential
- cmake
- libboost-all-dev
- libopenmpi-dev
- liblapack-dev
- libblas-dev
- libyaml-cpp-dev
- python     (which is actually python2)

I built HDF5 v1.10.8 with the "--enable-parallel" option.

I built NetCDF-C v4.7.4, first making the source code modifications specified by the "third party" instructions. I configured cmake with the following bash script (points to my prior installation of hdf5):
```bash
#!/bin/bash

export CFLAGS="-I/home/scott/pkg/hdf5-1.10.8-install/include -I/usr/lib/x86_64-linux-gnu/openmpi/include"
export LDFLAGS="-L/home/scott/pkg/hdf5-1.10.8-install/lib"

./configure --prefix=/home/scott/pkg/netcdf-c-4.7.4-modified-install --enable-parallel --enable-netcdf-4 --disable-v2 --disable-fsync --disable-dap
```

And then I configured cmake for Trilinos 13.0.1 with the following bash script (points to my prior installations of netcdf and hdf5):

```bash
#!/bin/bash

MYPREFIX="/home/scott/pkg/trilinos-13-0-1-install" # installation directory
MYSOURCE="/home/scott/pkg/Trilinos-trilinos-release-13-0-1" # trilinos source directory
MYMPI="/usr/lib/x86_64-linux-gnu/openmpi"
MYHDF5="/home/scott/pkg/hdf5-1.10.8-install"
MYNETCDF="/home/scott/pkg/netcdf-c-4.7.4-modified-install"
MYBOOST=""

rm -f CMakeCache.txt

cmake -D CMAKE_INSTALL_PREFIX:PATH="${MYPREFIX}" \
-D MPI_BASE_DIR:PATH="${MYMPI}" \
-D CMAKE_CXX_FLAGS:STRING="-O2 -std=c++11 -pedantic -ftrapv -Wall -Wno-long-long" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Sacado:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_ML:BOOL=ON \
-D Trilinos_ENABLE_Phalanx:BOOL=ON \
-D Trilinos_ENABLE_Intrepid:BOOL=ON \
-D Trilinos_ENABLE_NOX:BOOL=ON \
-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Trilinos_ENABLE_Rythmos:BOOL=ON \
-D Trilinos_ENABLE_MOOCHO:BOOL=ON \
-D Trilinos_ENABLE_TriKota:BOOL=OFF \
-D Trilinos_ENABLE_Stokhos:BOOL=ON \
-D Trilinos_ENABLE_Zoltan:BOOL=ON \
-D Trilinos_ENABLE_Piro:BOOL=ON \
-D Trilinos_ENABLE_Teko:BOOL=ON \
-D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
-D Trilinos_ENABLE_SEACAS:BOOL=ON \
-D Trilinos_ENABLE_SEACASBlot:BOOL=OFF \
-D Trilinos_ENABLE_Pamgen:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D TPL_ENABLE_HDF5:BOOL=ON \
-D HDF5_INCLUDE_DIRS:PATH="${MYHDF5}/include" \
-D HDF5_LIBRARY_DIRS:PATH="${MYHDF5}/lib" \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D TPL_Netcdf_Enables_Netcdf4:BOOL=ON \
-D Netcdf_INCLUDE_DIRS:PATH="${MYNETCDF}/include" \
-D Netcdf_LIBRARY_DIRS:PATH="${MYNETCDF}/lib" \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_BLAS:BOOL=ON \
-D TPL_ENABLE_LAPACK:BOOL=ON \
-D TPL_ENABLE_Boost:BOOL=ON \
-D TPL_ENABLE_Matio:BOOL=OFF \
-D TPL_ENABLE_X11:BOOL=OFF \
-D TPL_ENABLE_yaml-cpp:BOOL=ON \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
${MYSOURCE}
```

For some reason, I had to call make twice on this one. The first time it ended with "Error 2" on 100%.

Finally, I built peridigm. I configured cmake with the following bash script (which points to installations of hdf5, netcdf, and trilinos from prior steps).
```bash
#!/bin/bash

MYPREFIX="/home/scott/pkg/peridigm-install" # installation directory
MYSOURCE="/home/scott/pkg/peridigm" # peridigm source directory
MYMPI="/usr/lib/x86_64-linux-gnu/openmpi"
MYHDF5="/home/scott/pkg/hdf5-1.10.8-install"
MYNETCDF="/home/scott/pkg/netcdf-c-4.7.4-modified-install"
MYBOOST=""
MYTRILINOS="/home/scott/pkg/trilinos-13-0-1-install"

rm -f CMakeCache.txt

cmake -D CMAKE_INSTALL_PREFIX:PATH="${MYPREFIX}" \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Trilinos_DIR:PATH="${MYTRILINOS}/lib/cmake/Trilinos/" \
-D CMAKE_C_COMPILER:STRING=/usr/bin/mpicc \
-D CMAKE_CXX_COMPILER:STRING=/usr/bin/mpicxx \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
${MYSOURCE}
```

And once built, I tested out by decomposing the disk_impact example into 16 parts and running! It seems to work.
