### ISSUE TITLE
Tensile Test with Elastic Plastic Correspondence Material Model

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#182]
Dear Peridigm Community,

I wish to get the stress-strain curve in the tensile test up to fracture but from the given example "Elastic Correspondence" material model is used with a quasistatic solver and when I tried to implement "Elastic-Plastic Correspondence" model the simulation fails with Quasistatic Solver although it is working perfectly with the explicit solver. So in this regard any header will be beneficial .

Many Thanks
Pushkar

**Comment by johntfoster** [comment]
There is not a robust implementation of using the quasistatic solver with fracture.  We've had some success using the MatrixFree solver from NOX, but it usually requires some modifications to the code to use an adaptive load-stepping algorithm.  For example, a naive implementation would be to attempt a load step, if the solver fails to converge, cut the time step in half and try again.

To see how to extract stress strain curves, you might [find this](https://github.com/peridigm/peridigm/tree/master/test/verification/IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw/) test useful.

**Comment by ppandit95** [comment]
Thanks @johntfoster for a quick and insightful reply I will look into the implementation ....
