### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#186]
I received the following errors when I was trying to build peridigm on an HPC cluster:

Peridigm_ZoltanSearchTree.cpp:123:3: error: ‘TEUCHOS_TEST_FOR_TERMINATION’ was not declared in this scope
   TEUCHOS_TEST_FOR_TERMINATION(ierr != 0, "Error in ZoltanSearchTree::ZoltanSearchTree(), call to Zoltan_LB_Partition() returned a nonzero error code.");

Peridigm_Compute_Energy.cpp:165:13: error: ‘TEUCHOS_TEST_FOR_TERMINATION’ was not declared in this scope
             TEUCHOS_TEST_FOR_TERMINATION(neighborID < 0, "Invalid neighbor list\n");

/Peridigm_Compute_Error.cpp:182:9: error: ‘TEUCHOS_TEST_FOR_TERMINATION’ was not declared in this scope
         TEUCHOS_TEST_FOR_TERMINATION(!isRectangular, ss.str());

Peridigm_Compute_Error.cpp:250:3: error: ‘TEUCHOS_TEST_FOR_TERMINATION’ was not declared in this scope
   TEUCHOS_TEST_FOR_TERMINATION(std::abs(y2 - y1 - h) > 1.0e12, "**** Error:  Error compute class detected non-square element.");

Any help would be appreciated. Thanks!

**Comment by jritta** [comment]
Hi rbh007720,

It sounds for me like you are using an old version of Trilinos. Try a newer version or compile Peridigm with the commit ea11b954e79431099bbfeed9b7102c54c5857367.

Best
Jonas

**Comment by rbh007720** [comment]
Hi Jonas,

Thanks for the help. I have compiled Peridigm with the commit ea11b95. It worked, however, in the "make test":

53% tests passed, 89 tests failed out of 190

Total Test time (real) = 957.27 sec

The following tests FAILED:
         54 - BodyForce_Implicit_np1 (Failed)
         55 - BodyForce_Implicit_np4 (Failed)
         56 - BodyForce_Explicit_np1 (Failed)
         57 - BodyForce_Explicit_np4 (Failed)
         58 - BodyForce_QS_np1 (Failed)
         59 - BodyForce_QS_np4 (Failed)
         60 - BodyForce_QS_NOX_np1 (Failed)
         61 - BodyForce_QS_NOX_np4 (Failed)
         62 - CentrifugalLoad_np1 (Failed)
         63 - CentrifugalLoad_np4 (Failed)
         66 - Contact_Cubes_np1 (Failed)
         67 - Contact_Cubes_np4 (Failed)
         68 - Contact_Cubes_Interaction_Blocks_np1 (Failed)
         69 - Contact_Cubes_Interaction_Blocks_np4 (Failed)
         70 - Contact_Ring_np1 (Failed)
         71 - Contact_Ring_np4 (Failed)
         72 - Contact_Perforation_np1 (Failed)
         73 - Contact_Perforation_np3 (Failed)
         84 - Compression_QS_3x2x2_Exodus_np1 (Failed)
         85 - Compression_QS_3x2x2_Exodus_np2 (Failed)
         86 - Compression_QS_3x2x2_TextFile_np1 (Failed)
         87 - Compression_QS_3x2x2_TextFile_np3 (Failed)
         88 - WaveInBar_np1 (Failed)
         89 - WaveInBar_np3 (Failed)
         90 - WaveInBar_MultiBlock_np1 (Failed)
         91 - WaveInBar_MultiBlock_np4 (Failed)
         92 - Bar_OneBlock_OneMaterial_QS_np1 (Failed)
         93 - Bar_OneBlock_OneMaterial_QS_np2 (Failed)
         94 - Bar_TwoBlocks_OneMaterial_QS_np1 (Failed)
         95 - Bar_TwoBlocks_OneMaterial_QS_np2 (Failed)
         96 - Bar_TwoBlocks_TwoMaterial_QS_np1 (Failed)
         97 - Bar_TwoBlocks_TwoMaterial_QS_np2 (Failed)
         98 - Bar_TwoBlocks_TwoDifferentMaterial_QS_np1 (Failed)
         99 - Bar_TwoBlocks_TwoDifferentMaterial_QS_np2 (Failed)
        100 - Bar_TwoBlocks_TwoDifferentMaterial_QS_np3 (Failed)
        101 - Bar_TwoDisconnectedPieces_QS_np1 (Failed)
        102 - Bar_TwoDisconnectedPieces_QS_np2 (Failed)
        103 - Bar_TwoDisconnectedPieces_QS_np3 (Failed)
        106 - MultipleOutputFiles_np2 (Failed)
        107 - DefaultBlocks_np1 (Failed)
        108 - DefaultBlocks_np4 (Failed)
        109 - PrecrackedPlate_np1 (Failed)
        110 - PrecrackedPlate_np4 (Failed)
        111 - PrecrackedPlateTwoCracks_np1 (Failed)
        112 - PrecrackedPlateTwoCracks_np4 (Failed)
        113 - DiskFilter_np1 (Failed)
        114 - DiskFilter_np4 (Failed)
        115 - DeformationGradient_PlaneStrainCompression_np1 (Failed)
        116 - DeformationGradient_PlaneStrainCompression_np4 (Failed)
        117 - DeformationGradient_SimpleShear_np1 (Failed)
        118 - DeformationGradient_SimpleShear_np4 (Failed)
        119 - DeformationGradient_PureShear_np1 (Failed)
        120 - DeformationGradient_PureShear_np4 (Failed)
        121 - DeformationGradient_SolidRotation_np1 (Failed)
        122 - DeformationGradient_SolidRotation_np4 (Failed)
        123 - DeformationGradient_NoDeformation_np1 (Failed)
        124 - DeformationGradient_NoDeformation_np4 (Failed)
        125 - DeformationGradient_NoLoad_np1 (Failed)
        126 - DeformationGradient_NoLoad_np4 (Failed)
        129 - Pals_Simple_Shear_np1 (Failed)
        130 - ShellBondFilter_np1 (Failed)
        131 - ShellBondFilter_np4 (Failed)
        132 - InitialDamage_np1 (Failed)
        133 - InitialDamage_np4 (Failed)
        144 - Contact_Friction_Time_Dependent_Coefficient_np1 (Failed)
        145 - Contact_Friction_Time_Dependent_Coefficient_np2 (Failed)
        150 - BondBreakingInitialVelocity-EP_np1 (Failed)
        151 - BondBreakingInitialVelocity-EP_np3 (Failed)
        164 - VariableHorizonParsing_np1 (Failed)
        165 - VariableHorizonParsing_np4 (Failed)
        166 - MultipleHorizons_np1 (Failed)
        167 - MultipleHorizons_np4 (Failed)
        168 - ElasticCorrespondenceQSTension_np1 (Failed)
        169 - ElasticCorrespondenceQSTension_np4 (Failed)
        170 - IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np1 (Failed)
        171 - IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np4 (Failed)
        172 - IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np1 (Failed)
        173 - IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np4 (Failed)
        180 - ElasticCorrespondenceFullyPrescribedTension_np1 (Failed)
        181 - ElasticCorrespondenceFullyPrescribedTension_np4 (Failed)
        182 - ElasticHypoelasticCorrespondenceFullyPrescribedTension_np1 (Failed)
        183 - ElasticHypoelasticCorrespondenceFullyPrescribedTension_np4 (Failed)
        184 - SimpleImplicitDiffusion_np1 (Failed)
        185 - SimpleImplicitDiffusion_np4 (Failed)
        186 - InterfaceAwareDamageModelOneBlockNP1 (Failed)
        187 - InterfaceAwareDamageModelTwoBlocksSameValuesNP1 (Failed)
        188 - InterfaceAwareDamageModelTwoBlocksDifferentValuesNP1 (Failed)
        189 - InterfaceAwareDamageModelTwoBlocksDifferentValuesNP2 (Failed)
        190 - InterfaceAwareDamageModelTwoBlocksDifferentValuesNP3 (Failed)
Errors while running CTest
make: *** [Makefile:86: test] Error 8

**Comment by jritta** [comment]
Hi rbh007720,

When you look at the test that failed, what could be the reason they were not passed? What do the test have in common?
Maybe these questions will point you in the right direction ;)

Best,
Jonas

PS: `np` = number of MPI processes

**Comment by jritta** [comment]
By the way, it is also a good option to look into the log files of the failed test. You will find them in the following directory `<BUILD_DIR>/tests`

**Comment by rbh007720** [comment]
I have looked into the log files. It failed to open the geometry files and the "gold" files. For example, in the Body_Force_Implicit.log:


-- Peridigm
-- version 1.5.0 (Dev)

MPI initialized on 4 processors.


****Error on processor 2: unable to open file Body_Force.g.4.2

/project/6002274/rbh/commit/peridigm-ea11b954e79431099bbfeed9b7102c54c5857367/peridigm-ea11b954e79431099bbfeed9b7102c54c5857367/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1136:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #2: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)

****Error on processor 3: unable to open file Body_Force.g.4.3

/project/6002274/rbh/commit/peridigm-ea11b954e79431099bbfeed9b7102c54c5857367/peridigm-ea11b954e79431099bbfeed9b7102c54c5857367/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1136:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #3: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)

****Error on processor 1: unable to open file Body_Force.g.4.1

/project/6002274/rbh/commit/peridigm-ea11b954e79431099bbfeed9b7102c54c5857367/peridigm-ea11b954e79431099bbfeed9b7102c54c5857367/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1136:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #1: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)

****Error on processor 0: unable to open file Body_Force.g.4.0

/project/6002274/rbh/commit/peridigm-ea11b954e79431099bbfeed9b7102c54c5857367/peridigm-ea11b954e79431099bbfeed9b7102c54c5857367/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1136:

Throw number = 1

Throw test that evaluated to true: 1

Error on PID #0: PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)
Wallclock Time (seconds):
                     Min            Max            Ave
  Total            0.041           0.13          0.078

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[39713,1],1]
  Exit code:    10
--------------------------------------------------------------------------
epu --  E Pluribus Unum
	(Out of Many One -- see http://www.greatseal.com/mottoes/unum.html)
	ExodusII Parallel Unification Program
	(Version: 4.22) Modified: 2017/04/25
Cannot open file './Body_Force_Implicit.e.4.0'
ERROR: (EPU) Problem initializing input and/or output files.

   *****************************************************************
              EXODIFF	(Version: 2.88) Modified: 2017-05-05
              Authors:  Richard Drake, rrdrake@sandia.gov           
                        Greg Sjaardema, gdsjaar@sandia.gov          
              Run on    2021/11/11   11:12:25 PST
   *****************************************************************

exodiff: ERROR: Couldn't open file "Body_Force_Implicit.e".
Reading first file ... 
exodiff: ERROR: exodiff: ERROR: Couldn't open file "Body_Force_Implicit.e". File does not exist.

**Comment by jritta** [comment]
Did you check if the decomposed files exist? So do the files `Body_Force.g.4.0`, `Body_Force.g.4.1`, `Body_Force.g.4.2`,  and `Body_Force.g.4.3` exist? Do all MPI processes have access to the previous mentioned decomposed files?
