### ISSUE TITLE
Some issue with MergeFiles.py

### ISSUE THREAD

**Issue by Juliendu33** [peridigm/peridigm#19]
Hello, 

After parallelisation, I have some issue to merge the différent files .e 

If I execute the follow command : 
 > /appli/peridigm/CMakeconfig/peridigm/BUILD/scripts/MergeFiles.py ThermalExpansionCube 4

I obtain this reponse : 
> /appli/peridigm/CMakeconfig/peridigm/BUILD/scripts/MergeFiles.py: Command not found

If I execute the follow command : 
> /appli/peridigm/CMakeconfig/peridigm /scripts/MergeFiles.py ThermalExpansionCube 4

I obtain this reponse : 
> Error: epu not found! Please execute this script from ‘scripts’ in your Peridigm build directory or put ‘epu’ in your path. ‘epu’ can be found in your Trilinos install ‘bin’ directory

or this message : 

Traceback (most recent call last):
File "/appli/peridigm/CMakeconfig/peridigm /scripts/MergeFiles.py " line 60, in <module>
os.remove(log_file_name)
OSError: (Errno 2) No such file or directory 'ThermalExpansionCube.log' 

or the file exist because in the file I have this message : 
epu: symbol lookup error: epu: undefined symbol: _libm_feature_flag

I thank you again for your help and the time spent answering me.

Regards
Julien

**Comment by MDBrothers** [comment]
Julien,

are the Trilinos binaries appended to your PATH environment variable?
