### ISSUE TITLE
Johnson Cook Damage Model with "Isotropic Hardening Correspondence" Model

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#194]
Dear Peridigm Community

I am trying to simulate fracture in tensile test of ductile material for which "Isotropic Hardening Correspondence" material has been used with Johnson Cook failure criteria but when plotted a stress strain graph I am not able to see the expected behavior as plotted by @djlittl in on of the manuscript named "Chapter 20 Peridynamics".Any headers in this regard will be helpful

Many Thanks 
Pushkar

**Comment by ppandit95** [comment]
Yes,I am getting expected elastic response as well as response from linear isotopic hardening([attached](https://drive.google.com/file/d/1Y2QWiPdO1tQ9l-HUkRKGJQmzA01PoOWY/view?usp=sharing)))  but when I added Johnson Cook model in order to get the later part of the stress strain curve (softening due to fracture),I am not able to get the curve even after the simulation runs without any error

**Comment by ppandit95** [comment]
Moreover,on a closer look I realized that there is a place holder for bondDamage in correspondence.cxx but its value is set to zero and is not retrieved from the Damage model so  can I retrive it using the command:
`PeridigmNS::DataManager::getData(m_bondDamageFieldId, PeridigmField::STEP_NP1)->ExtractView(&bondDamage);` the way it has been done with omega function.

**Comment by djlittl** [comment]
Yes, that should work.  You will need to specify a bond damage model in the input deck so that the bond damage quantity is calculated by a Damage model, and then you can retrieve the damage value for each bond as you suggest above.

**Comment by ppandit95** [comment]
@djlittl I tried to retrieve the bondDamage in correspondence.cc where the placeholder for damage is present but I wish to know that do I need to modify Cauchy stresses and Von Mises Stresses in order to include damage in force density

**Comment by djlittl** [comment]
I believe you have arrived at an open area of research!  Pretty sure this is why bond damage isn't fully implemented in the code.  The theory isn't fleshed out in the literature, although I know there's been some work in this area (Foster, others).  The NOSB formulation, as presented in Silling, et al., 2007, does not include a discussion of bond failure.  And the approximate deformation gradient isn't really a function of bond damage (not directly, anyway), so the change in strain energy due to bond failure will be incorrect if you just apply a critical stretch bond failure law and do nothing else.  A somewhat reasonable but not rigorous hack would be to decay the stress as a function of the percentage of broken bonds.

**Comment by ppandit95** [comment]
Moreover, @djlittl when a changed the material from elastic to isotropic Hardening Correspondence in fragmenting cylinder example the cylinder was trying to fragment but didnt break in case of isotropic hardening as opposed to the results in elastic case(viedo attached

https://user-images.githubusercontent.com/48231710/142334947-bd43409c-8b3b-421a-8b6c-3ed5ca98b13a.mp4


https://user-images.githubusercontent.com/48231710/142342611-193e2bb5-3e0e-4bf9-92e1-74ba9ef3cb83.mp4

).
One one which fragments has been simulated with elastic model while the other one has been simulated with isotropic hardening correspondence model with critical stretch damage model(although I intend to use Johnson Cook model if the implementation goes right).Lastly,I came across a documentation of Third Sandia Fracture Challenge wherein one of the team has incorporated Peridynamics with Jonson Cook Damage model which suggests that Johnson Cook model can be applied but I am not sure about whether it can be applied to correspondence model as you elaborated and I would like to know the source for implementation of "Isotropic Hardening Correspondence" model as I couldnt find damage modelling in non ordinary state based models.

Also thank @djlittl  for your time and insights on the same.

**Comment by ppandit95** [comment]
Also @djlittl is it possible to reproduce the result from tensile test given in this document(attached) using peridigm
[Peridynamics.pdf](https://github.com/peridigm/peridigm/files/7559590/Peridynamics.pdf)
