### ISSUE TITLE
Poisson's Ratio with Tensile Test Example

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#197]
Dear Peridigm Community

I wish to calculate the poisson's ratio using tensile test example . Can it be done using Compute Class or is there any other way to do the same by calculating the ratio of strains.Any header in this regard will prove beneficial.

Many Thanks
Pushkar

**Comment by djlittl** [comment]
That example uses a "virtual strain gauge" approach in which the relative displacements of two points are tracked and then used to compute (delta L)/(L) for engineering strain.  You could just add a second strain gauge in the horizontal direction for comparison against the original (vertical) strain gauge to compute Poisson's ratio.  Tracking the two points for the strain gauge calculation is done with Nearest_Point_Data compute classes.

**Comment by ppandit95** [comment]
Thanks @djlittl for elaborating on how to include a compute class which aids in calculation of Poisson's Ratio . Moreover,I wish to add kinematic Hardening Material Model but is there any guide which walks through such a process similar to one put forth by @CWilberg of DLR for adding a damage model into peridigm.Any headers in this regard will be helpful.

**Comment by djlittl** [comment]
Is the model you want to add a NOSB model that operates on deformation gradient / strain, or a standard peridynamic model that operates on individual bond stretches?

**Comment by ppandit95** [comment]
I am wish to use NOSB model for the extension from a base model "Isotropic Hardening Correspondence" model
