### ISSUE TITLE
Compiling Peridim Version 4.1

### ISSUE THREAD

**Issue by diehlpk** [peridigm/peridigm#20]
`/data/diehl/Compile/peridigm-release-1.4.1/src/io/bond_volume/quick_grid/calculators.cxx: In function ‘std::tr1::shared_ptr<MATERIAL_EVALUATION::Bond_Volume_Calculator> BOND_VOLUME::QUICKGRID::get_Bond_Volume_Calculator(const string&)’:
/data/diehl/Compile/peridigm-release-1.4.1/src/io/bond_volume/quick_grid/calculators.cxx:73:3: error: ‘cerr’ is not a member of ‘std’
   std::cerr << e.what();
`
Missing include #include <iostream> solves the problem

**Comment by johntfoster** [comment]
@diehlpk what compiler are  you using?  I cannot reproduce this on my Mac with clang++.  Are you compiling with `-DCMAKE_CXX_FLAGS:STRING="-std=c++11"`?

**Comment by diehlpk** [comment]
@johntfoster Yes, with -std=gnu++11, because I am on Ubuntu 16.04 with gcc

**Comment by pietrodantuono** [comment]
On openSUSE I had this error, too. Including iostream in calculators.cxx solves the problem.

**Comment by johntfoster** [comment]
`<iostream>` is already in `calculators.cxx`  what version are you using?
From `master`?

**Comment by pietrodantuono** [comment]
I am using the version from the bramch Release-1.4.1. If you take a look at calculators.cxx in that branch, you will note that there is no <iostream> there.

However, thanks to have pointed out that in the same file of the branch master <iostream> is declared.

**Comment by YudanJIN** [comment]
I have just follow your steps of installation Peridigm, but I can't run Peridigm after I finished.
There is a fault: segmentation fault(core dumped).
Do you have the same problem?

**Comment by djlittl** [comment]
I do not see this problem.  We'll need more information to diagnose the problem.
