### ISSUE TITLE
Elastic Hypoelastic Correspondence Model Error

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#203]
I encountered the following error when I used the "Elastic Hypoelastic Correspondence" model combined with the "Johnson Cook" damage model and other material models in one simulation:

p=0: /home/rbh/JC/peridigm/src/core/Peridigm_Field.cpp:128:

Terminate test that evaluated to true: lcLabel_ == lcLabel

**** Error:  getFieldId() found suspiciously similar field specifications.

****         Requested spec:

****           relation: ELEMENT
****           length:
****           temporal: CONSTANT
****           label:    Deformation_Gradient
****         Close match:

****           relation: ELEMENT
****           length:
****           temporal: TWO_STEP
****           label:    Deformation_Gradient

Thanks!

**Comment by djlittl** [comment]
This means that in one place in the code the variable Deformation_Gradient is defined as requiring storage for both the current and previous time steps (TWO_STEP), and somewhere else in the code the variable Deformation_Gradient is defined as requiring storage for only the current time step (CONSTANT).  You must have triggered a use case in which both of the definitions are used within a simulation.  I suspect that the definition of Deformation_Gradient in the Johnson Cook damage model needs to be changed to match the one in the base class for correspondence models.  Note that this will require a few other changes too, for example the calls to retrieve the data will need to specify which of the two values to retrieve (STEP_N or STEP_NP1).
