### ISSUE TITLE
Self Contact

### ISSUE THREAD

**Issue by masoudbehzadinasab** [peridigm/peridigm#206]
It appears that the contact model acts for a pair of materials from the same block, which are not initially neighbors, but their deformed distance becomes less than the contact radius. For example, I'm considering a problem with two blocks in contact. I use a custom name for Interactions (not Self Contact) and specify block_1 and block_2 for First and Second Block. I did not intend to include self contact for that problem. If I choose the contact radius larger than the horizon, I can clearly see that there will be contact forces in one block even when it is far from the other block of material. It seems that the contact search routine labels contact neighbors for points outside of the horizon, rather than out of the block. Is that intentional?

**Comment by johntfoster** [comment]
I'm not sure I fully understand the question, how can you have a pair of materials in a single block?

**Comment by masoudbehzadinasab** [comment]
I must clarify, what I meant was a pair of material points (PD nodes) in the same block but outside of each other’s horizon. With the current version of the code, if those points’ current distance becomes less than the contact radius, contact will become active no matter what I specify for the interactions (General Contact, Self Contact, or a custom name indicating specific contact blocks). I thought that “Self Contact” was designed to enable contact within the same block. Am I missing something or is there a problem in the code?

**Comment by sahirbutt** [comment]
I have also faced the same issue here: #107

**Comment by shan-zhong** [comment]
![Untitled](https://user-images.githubusercontent.com/56968616/152197555-c40a17c8-6c59-44f0-ac25-6a27cd6d0c34.png)
The whole material was discretized into one material block, how to detect the horizon neighbour and contact between the two points within the red circle?

**Comment by MINIAI** [comment]
I faced the same issue when i simulating the rock cutting process. The shavings contact with the rock which causes the rock to break. And when i try to set self contact and a custom name indicating specific contact blocks at the same time and choose zero stiffness for self contact, it seems that the program can only recognize contact between specific contact blocks. What should i do with this situation? Has anyone successfully solved this problems?
