### ISSUE TITLE
Make Error

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#207]
collect2: error: ld returned 1 exit status
make[2]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_QuickGrid_loadBal_np2_3x1x1.dir/build.make:252: src/io/pdneigh/unit_test/ut_QuickGrid_loadBal_np2_3x1x1] Error 1
make[1]: *** [CMakeFiles/Makefile2:2475: src/io/pdneigh/unit_test/CMakeFiles/ut_QuickGrid_loadBal_np2_3x1x1.dir/all] Error 2
make[2]: *** [src/io/pdneigh/unit_test/CMakeFiles/ut_Y-Z_crack_np4.dir/build.make:252: src/io/pdneigh/unit_test/ut_Y-Z_crack_np4] Error 1
make[1]: *** [CMakeFiles/Makefile2:2301: src/io/pdneigh/unit_test/CMakeFiles/ut_Y-Z_crack_np4.dir/all] Error 2
MPI/gcc9/openmpi4/trilinos/13.2.0/lib/libzadelus.so.13.0: error: undefined reference to 'Adelus::nprocs_row'
/MPI/gcc9/openmpi4/trilinos/13.2.0/lib/libzadelus.so.13.0: error: undefined reference to 'Adelus::me'
/MPI/gcc9/openmpi4/trilinos/13.2.0/lib/libzadelus.so.13.0: error: undefined reference to 'Adelus::nprocs_row'

Thanks!

**Comment by oldninja** [comment]
Hi @rbh007720 , looks like your trilinos library is missing the Adelus package? Could you please provide more ingor about your setup? For example, trilinos version and packages, peridigm version, gcc and others.

**Comment by rbh007720** [comment]
Hi @oldninja , I am using gcc/9.3.0, trilinos/13.2.0, netcdf/4.7.4, openmpi/4.0.3, hdf5/1.10.6, peridigm/master. Thanks!

**Comment by oldninja** [comment]
@rbh007720 , could you try to recompile an earlier trilinos build? It appears that the Adelus library is recent, as mentioned [here](https://github.com/trilinos/Trilinos/issues/6773#issuecomment-583231611). I would stick with an earlier version, I have Trilinos 12.12.1 and it works just fine.

**Comment by jritta** [comment]
Hi,

```MPI/gcc9/openmpi4/trilinos/13.2.0/lib/libzadelus.so.13.0: error: undefined reference to 'Adelus::nprocs_row'``` this sounds very much like an issue with your Trilinos installation, not Peridigm. Trilinos 13.0.0 works with Peridigm as well. The package Adelus is not needed by Peridigm --> just disable it when you compile Trilinos could already solve your problem.
You can also check similar and closed issues like #147, #110. #106 or #105 maybe it helps you to configure your Trilinos installation.

Best
Jonas

**Comment by rbh007720** [comment]
Thanks!
