### ISSUE TITLE
NOXSolver Fails after Iteration 50 !!!!

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#208]
Dear Peridigm Community

I am working with the tensile_test example application which uses a NOXQuasiStatic solver to run the simulation but my simulation fails after certain Load Step as the number of iterations reach 50 although the L2 norm is pretty much close to the convergence criteria at that step . So in this regard I was wondering if is it possible to increase the number of iterations at each step in the simulation.

Many Thanks
Pushkar

**Comment by jritta** [comment]
Hi,

use the option ```Max Solver Iterations: <NUMBER_YOU_WANT>``` and it is not possible to increase the number of solver iterations in each step, but you could implement that.

Best
Jonas

**Comment by ppandit95** [comment]
Thanks @jritta for clearing that out as I was using `Maximum Solver Iterations:` which wasn't working but I managed to mitigate that error with your suggestion.
