### ISSUE TITLE
 unable to open Exodus file 

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#212]
When I was trying to run Peridigm, there was an error:

****Error on processor 0: unable to open file 2d_2.g

/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1136:

Throw number = 1

Throw test that evaluated to true: 1

PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() -- Error code: -1 (ex_open)

Thanks!

**Comment by oldninja** [comment]
Is this mesh purely 2D? Say (x,y) coordinates only.

**Comment by rbh007720** [comment]
No, it is 3D mesh. It has (x,y,z) coordinates.

**Comment by sahirbutt** [comment]
You can also try to check if there is something wrong with the mesh file using `explore` from trilinos:
```
trilinos-install-dir/bin/explore <your-mesh-file>.g
check
```
