### ISSUE TITLE
N-dimensional BOND data

### ISSUE THREAD

**Issue by maxincrease** [peridigm/peridigm#216]
Dear developers,

Since in Peridigm a BOND data must be SCALAR, could you tell me please what points should I pay attention to in order to extend the functionality of Peridigm to the N-dimensional BOND data?

Thank you in advance!
Max

**Comment by djlittl** [comment]
That would be a brutal code change.  Can you just use N different bond fields?  In other words, instead of N-dimensional bond fields, could you use scalar bond fields and have N of them?

**Comment by maxincrease** [comment]
Thank you, it works!
