### ISSUE TITLE
RAMP boundary Conditions in Peridigm

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#222]
Dear Peridigm Community

I am trying to give a ramp displacement boundary condition  for cyclic loading but I am not able to do so although I guess this could be done using "if else " but I am not sure how that is be implemented.So any help in this regard will be beneficial.

Many Thanks
Pushkar

**Comment by jritta** [comment]
Hi Pushkar,

just look at the [perfomance tests](https://github.com/peridigm/peridigm/tree/master/test/performance). In the test [fragmenting_cylinder](https://github.com/peridigm/peridigm/tree/master/test/performance/fragmenting_cylinder) you have space varying BCs and in [tensile_test](https://github.com/peridigm/peridigm/tree/master/test/performance/tensile_test) time varying BCs and in [twist_and_pull](https://github.com/peridigm/peridigm/tree/master/test/performance/twist_and_pull) both combined also with `if-else` statements.

Best,
Jonas

**Comment by ppandit95** [comment]
Dear Jonas

Thanks alot for pointing that out I will look into the implementation.

Regards
Pushkar
