### ISSUE TITLE
How to print contents of Teuchos::RCP<Epetra_Vector>

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#223]
Dear Peridigm Community

I am trying to debug a new material model that has been developed for which I need to check output from a Teuchos::RCP<Epetra_Vector> but I am getting an error if this is printed as an array and I only need to know one element of it . Any pointers in this regard will prove beneficial.

Thanks 
Pushkar

**Comment by oldninja** [comment]
Hi @ppandit95 , could you share how you are requesting the printing statement?

**Comment by ppandit95** [comment]
Sure, I have used "std::cout << "The value of backstress is"<<backstress<<std::endl; " where backstress is the oneDimensional Mothership Vector

**Comment by jritta** [comment]
There exists a [print method](https://docs.trilinos.org/dev/packages/epetra/doc/html/classEpetra__MultiVector.html#a05574a4b99bc315f5ba760653e5d0c16) for the Epetra_Vector but you must be aware that `Teuchos::RCP<>` is a pointer to the vector and not the vector itself.

Best,
Jonas

**Comment by oldninja** [comment]
Thanks @jritta for the clarification, that's what I thought it was.

**Comment by ppandit95** [comment]
Thanks @oldninja and @jritta for pondering upon that.
