### ISSUE TITLE
Documentation for Building Peridigm: Needs Work

### ISSUE THREAD

**Issue by sfeister** [peridigm/peridigm#224]
Thanks for all your work developing Peridigm! My undergraduate and I have been working on building it from source, and we've found the documentation left out many steps. Can we improve this documentation? Would you accept a fork and pull request on the /docs folder?

Here are some items we've found helpful building on Ubuntu 20.04:

https://github.com/peridigm/peridigm/issues/180

https://www.diehlpk.de/blog/builing-peridigm/

**Comment by oldninja** [comment]
I agree several steps are missing and prevent a broader user base of Peridigm. Also, many issues in the past are "building" issues instead of bug fixes and improvements to the code. I will look forward to your PR.

**Comment by diehlpk** [comment]
@sfeister I am not sure about adding that to the doc folder, since this is 1) depending on the OS and 2) needs to be updated over time.

**Comment by diehlpk** [comment]
We might could add more details about dependencies of the dependencies to make it easier. But fell free to make some proposal and I am happy to give you feedback.

**Comment by sfeister** [comment]
Thanks for the feedback, my student and I will keep our documentation updates OS-agnostic. We will send you something soon!

**Comment by sfeister** [comment]
https://github.com/sfeister/peridigm#getting-started --> This is our working draft. I tried to spell out the various smaller dependencies in the build process, and add a bit more context to each step of the build process. We'd like to get more familiar with the build process before submitting the pull request. However, do let us know what you think at this stage! I'm a bit fuzzy on the "yaml-cpp" dependency and where in the process it fits, as well as which Trilinos packages were actually required in the Trilinos step.

**Comment by adityakavalur** [comment]
@sfeister thanks for working on this, I came to submit a simple fix to the build instructions, I am glad that you are working on something more substantial. A quick point, I am wondering are you able to build with c++11 ? I had to move to c++14 to fix `error: enable_if_t in namespace std does not name a template type; did you mean enable_if`

**Comment by jritta** [comment]
> @sfeister thanks for working on this, I came to submit a simple fix to the build instructions, I am glad that you are working on something more substantial. A quick point, I am wondering are you able to build with c++11 ? I had to move to c++14 to fix `error: enable_if_t in namespace std does not name a template type; did you mean enable_if`

Maybe it is the same as in issue #211 discussed.

Best,
Jonas

**Comment by sfeister** [comment]
@jritta I haven't hit that particular problem yet when building Peridigm

**Comment by diehlpk** [comment]
> https://github.com/sfeister/peridigm#getting-started --> This is our working draft. I tried to spell out the various smaller dependencies in the build process, and add a bit more context to each step of the build process. We'd like to get more familiar with the build process before submitting the pull request. However, do let us know what you think at this stage! I'm a bit fuzzy on the "yaml-cpp" dependency and where in the process it fits, as well as which Trilinos packages were actually required in the Trilinos step.

It looks good. Let me know when I should have a closer look.

**Comment by jritta** [comment]
@sfeister Me too. I never had any problems either but the issue @adityakavalur pointed out we already partly discussed in the issue #211

**Comment by adityakavalur** [comment]
Yes, but the solution there and what I noticed was to use c++14, but @sfeister [build document](https://github.com/sfeister/peridigm/blob/master/doc/BuildingPeridigm.md) says c++11 which is what I was trying to highlight

**Comment by ppandit95** [comment]
Apart from this, while building Peridigm one needs to build Trilinos with YAML reader which is not listed in the building instructions provided by @diehlpk
