### ISSUE TITLE
Cannot read Restart files for problem as number of processors grows

### ISSUE THREAD

**Issue by shaunakshende** [peridigm/peridigm#228]
For a problem that I am working with with around 4000 particles, the restart functionality works when writing for any mpi_size that I have tried (up to 800 cores on 13 icx nodes on stampede). However, reading the restarts that are successfully written causes an error if the number of processors exceeds 240 cores and 6 icx nodes. Does anyone know what could cause this?

Thanks,
Shaunak

**Comment by shaunakshende** [comment]
The reason that I am using 800+ cores for only 4000 nodes is that this is an FSI code that is a coupling between peridigm and a PetIGA code. 800+ ranks are required to handle the fluid.

**Comment by oldninja** [comment]
I don't have any idea about the issue with the restarts... But just got interested on that coupling you mentioned. Could you share more information about it?

**Comment by shaunakshende** [comment]
Sure, the code is up on my github under IGA-Flow-Peridigm. I am using a modified version of peridigm as a library, and coupling that to a PetIGA code which solves the compressible flow equations to model blast loading on solids modeled in Peridigm.
