### ISSUE TITLE
Publish Release for Installation with EasyBuild?

### ISSUE THREAD

**Issue by fontanj** [peridigm/peridigm#229]
Hi, 

I'm trying to install Peridigm on our university's HPC by using EasyBuild. If you are not familiar with EasyBuild, it is really a very handy open-source tool for installing scientific software in HPC environments, accounting for all dependencies etc.
( [https://github.com/easybuilders/easybuild] )

In order build Peridigm with EasyBuild, I need to make an EasyBuild configuration file for it (called an easyconfig) so that EasyBuild knows how to install the software. Once this is done, the configuration file can be made available to everyone on the EasyBuild GitHub page, and your software will ideally be very accessible and easy for everyone to install.

However, EasyBuild requires that the software be available in a static downloadable package, with a version number to identify it. Can you please publish a GitHub "Release" of your software, with a version number?

Thanks,
Josh

**Comment by johntfoster** [comment]
Can you not not use [this](https://github.com/peridigm/peridigm/archive/refs/heads/master.zip)?

**Comment by fontanj** [comment]
I don't think so. Will the package provided by that that link change as Peridigm is updated? I'm looking for something that is _static_ and _versioned_, a package that defines a certain version of the code, which will always be that version of the code. The kind of things I would find under "Releases" at the right-hand side of the GitHub page.
