### ISSUE TITLE
Problem with Time-dependent Prescribed Displacement and Implicit Solver

### ISSUE THREAD

**Issue by raedma** [peridigm/peridigm#23]
Hello,

recently, I wanted to perform a simulation of a tensile test with a constant velocity boundary condition. Here is only the specific boundary condition part of the input deck:

```
Boundary Conditions
    …
    Displacement-1-V-x
        Type "Prescribed Displacement"
        Node Set "bc_load"
        Coordinate "x"
        Value "value=10.0*t"
```

on one end of the model. The calculation works fine as long as I use the Verlet or QuasiStatic solver. However, whenever I try to use to Implicit time integration, nothing happens, specifically, no displacement is applied.

I tried to cross-check if this behavior is specific to my problem. Therefore I used the “Twist_and_Pull” model from the examples folder because it also uses time-dependent boundary conditions. I switched the time integration scheme in Solver1 from

```
Solver1
  Verbose "false"
  Initial Time 0.0
  Final Time {TWIST_FINAL_TIME}
  QuasiStatic
    Number of Load Steps {NUMBER_OF_QS_STEPS}
    Absolute Tolerance 1.0
    Maximum Solver Iterations 100
```

to 

```
Solver1
  Verbose "false"
  Initial Time 0.0
  Final Time {TWIST_FINAL_TIME}
  Implicit
    Fixed dt {TWIST_FINAL_TIME/NUMBER_OF_QS_STEPS}
    Absolute Tolerance 1.0
    Maximum Solver Iterations 100
```

While the QuasiStatic result is as expected, again, nothing happens for the Implicit time integration (residual=0). Here is a part of the log file:

```
-- Peridigm
-- version 1.4.1

MPI initialized on 16 processors.

Allocating global tangent matrix...
  number of rows = 53760
  number of nonzeros = 59708916

Load step 0, initial time = 0, final time = 0.1
  iteration 0: residual = 0

Load step 1, initial time = 0.1, final time = 0.2
  iteration 0: residual = 0

Time step (seconds):
  Stable time step    5.25035e-08
  User time step      not provided
  Safety factor       0.8
  Time step           4.20028e-08

Total number of time steps 11903

Explicit time integration [0% Complete=====================]
Explicit time integration [1% Complete=====================]
…
```

Is is possible that there is a bug in the treatment of time in the application of boundary conditions in PeridigmNS::Peridigm::executeImplicit from Peridigm.cpp or am I missing something in the definition?

Regards
Martin

**Comment by LasseSH** [comment]
It seems like there is an error in the calculation of the forces, because all vectors for the calculation of the residuals are 0 (a, force and externalForce) in line 3372 in Peridigm.cpp.

**Comment by Sgsiku** [comment]
@raedma: Did you solve the problem? I have the same issue. Is there probably an example how to use the implicit solver in Peridigm?

**Comment by raedma** [comment]
I did not have time to look at the problem in detail yet.

**Comment by twagnert** [comment]
I experienced the same problem, but with all kind of solvers. 
A switch to XML inputs solved the problem for me.
