### ISSUE TITLE
Runtime error message from Peridigm

### ISSUE THREAD

**Issue by ebm954** [peridigm/peridigm#230]
Dear Sirs,

Could you kindly help me to understand the following error message:

-- Peridigm
MPI initialized on 8 processors.
Time step (seconds):
  Stable time step    7.41268e-07
  User time step      not provided
  Safety factor       0.7
  Time step           5.18888e-07
Total number of time steps 9635
Explicit time integration [0% Complete=====================] p=2: /home/kavalurav/Downloads/sw/peridigm/src/core/Peridigm.cpp:1552:
Terminate test that evaluated to true: !std::isfinite((*force)[i])
**** NaN returned by force evaluation.              ?

This case is similar to the disk impact example you supply (some changes in geometry / mesh were introduced). A version of the yaml file is enclosed (in the docx file) and a picture of the problem. 

Just need your guidance on how to correct the problem. Hope you will have a few minutes to look into this issue.

Thanks very much for your help.
-Esteban

![screen_shot](https://user-images.githubusercontent.com/105565808/168447936-6dd87f89-2363-4740-8387-88b8f1c8f952.jpg)
[impact_example.docx](https://github.com/peridigm/peridigm/files/8693873/impact_example.docx)

**Comment by jritta** [comment]
Dear Esteban,

As the error messages says the evaluation of the forces result in a non finite force. This can have multiple reasons and I can not tell you the reason off the top of my head.

Could you please send the yaml file as a simple text file rather than a docx file? And if possible maybe also the discretization such that we can reproduce the problem?

When does the error appears? Directly after the start of the simulation or after some time steps were already calculated?

Best,
Jonas

**Comment by oldninja** [comment]
Hi Esteban, as @jritta mentioned, it is difficult to know why this is happening without having a model to evaluate. I recall experiencing some issues with the contact (combination of search radius, contact radius, and spring constant).

**Comment by jritta** [comment]
> Hi Esteban, as @jritta mentioned, it is difficult to know why this is happening without having a model to evaluate. I recall experiencing some issues with the contact (combination of search radius, contact radius, and spring constant).

Thank you for pointing out a possible cause of the problem! Nevertheless I do not think the problem is related to the contact because the error seems to arise from the `force` vector rather than the `contactForce` vector. So it seems while the material model is evaluated the force of at least one discretization point growth to a non-finite value.

**Comment by djlittl** [comment]
Running the simulation with contact turned off would be useful for troubleshooting.  The two bodies should just pass right through each other.  Certainly there should be no issue with the force calculation returning infinite values in that case, because the deformations should be essentially zero.  If the forces are still coming back infinite, then that confirms that you have some other problem going on.

Is the only difference between this simulation and the disk_impact simulation the shape of the projectile?

If the only difference is the mesh, then I suspect you have a flawed discretization.  For example, if you mistakenly have nodes that are right on top of each other, that will almost certainly result in invalid force calculations (e.g., division by zero due to a zero-length bond).  I've made that mistake several times myself.

**Comment by ebm954** [comment]
Jonas,

  Email did not go through … so re-sending a zip file with the input file and discretization.

Thanks,
-Esteban

From: Marin, Esteban B
Sent: Sunday, May 15, 2022 10:19 PM
To: peridigm/peridigm ***@***.***>; peridigm/peridigm ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [EXTERNAL]--Re: [peridigm/peridigm] Runtime error message from Peridigm (Issue #230)

Jonas,

    Enclosing input file and discretization. Error message below indicates that the error happens after 9635 time steps.

    The elastic material properties for the disk were obtained from a tensile stress-strain curve for Polycarbonate at (RT, 50 mm/min). I would like to use Peridigm to model impact in polymers. In this respect, I would appreciate any suggestion regarding an elastoplastic model / failure model already implemented in the software that I could use.

Thanks very much for your help,
-Esteban

------------------------------------------------------------------------------------
MPI initialized on 8 processors.
Time step (seconds):
  Stable time step    7.41268e-07
  User time step      not provided
  Safety factor       0.7
  Time step           5.18888e-07

Total number of time steps 9635
Explicit time integration [0% Complete=====================] p=5: /home/kavalurav/Downloads/sw/peridigm/src/core/Peridigm.cpp:1552:

Terminate test that evaluated to true: !std::isfinite((*force)[i])

**** NaN returned by force evaluation
---------------------------------------------------------------------------------------------

From: Jonas ***@***.******@***.***>>
Sent: Sunday, May 15, 2022 11:41 AM
To: peridigm/peridigm ***@***.******@***.***>>
Cc: Marin, Esteban B ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [EXTERNAL]--Re: [peridigm/peridigm] Runtime error message from Peridigm (Issue #230)


Hi Esteban, as @jritta<https://github.com/jritta> mentioned, it is difficult to know why this is happening without having a model to evaluate. I recall experiencing some issues with the contact (combination of search radius, contact radius, and spring constant).

Thank you for pointing out a possible cause of the problem! Nevertheless I do not think the problem is related to the contact because the error seems to arise from the force vector rather than the contactForce vector. So it seems while the material model is evaluated the force of at least one discretization point growth to a non-finite value.

**Comment by andrisfreimanis** [comment]
If you look at the error message, it says "NaN returned by force evaluation". That error is thrown when the material model returns a NaN. Could be a problem in the material model, could be an issue with the material properties, but often it means that the time step is too large leading to numerical instability. A smaller time step could help.

Best
Andris


MPI initialized on 8 processors.
Time step (seconds):
Stable time step 7.41268e-07
User time step not provided
Safety factor 0.7
Time step 5.18888e-07

Total number of time steps 9635
Explicit time integration [0% Complete=====================] p=5: /home/kavalurav/Downloads/sw/peridigm/src/core/Peridigm.cpp:1552:

Terminate test that evaluated to true: !std::isfinite((*force)[i])

**** NaN returned by force evaluation
________________________________

**Comment by djlittl** [comment]
Quick comment, it look to me that the error is being thrown at the first time step.  The output line that says “Total number of time steps 9635” means that the simulation will have that many time steps.  But the progress bar shows 0% complete.  This suggests to me that there might be an issue with the discretization.  For example, if a node has zero bonds, then some material models will run into numerical errors.  You should double check your horizon to make sure it’s a sane value.

Dave

From: Andris Freimanis ***@***.***>
Reply-To: peridigm/peridigm ***@***.***>
Date: Tuesday, October 11, 2022 at 3:37 AM
To: peridigm/peridigm ***@***.***>
Cc: "Littlewood, David" ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [peridigm/peridigm] Runtime error message from Peridigm (Issue #230)

If you look at the error message, it says "NaN returned by force evaluation". That error is thrown when the material model returns a NaN. Could be a problem in the material model, could be an issue with the material properties, but often it means that the time step is too large leading to numerical instability. A smaller time step could help.

Best
Andris


MPI initialized on 8 processors.
Time step (seconds):
Stable time step 7.41268e-07
User time step not provided
Safety factor 0.7
Time step 5.18888e-07

Total number of time steps 9635
Explicit time integration [0% Complete=====================] p=5: /home/kavalurav/Downloads/sw/peridigm/src/core/Peridigm.cpp:1552:

Terminate test that evaluated to true: !std::isfinite((*force)[i])

**** NaN returned by force evaluation
________________________________
