### ISSUE TITLE
Multiple Block Names in Compute Class "Block_Data"

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#231]
Dear Peridigm Community

I wish to know whether is it possible to give multiple block names with compute class "Block_Data" because tensile_test example has only one entry under this compute class header . Any help regarding this will be appreciated.

Many Thanks
Pushkar

**Comment by jritta** [comment]
Hi,

As far as I know, this is not implemented yet. The only possibility is to create a compute class for each block and combine these results in the post-processing. 

Best,
Jonas

**Comment by ppandit95** [comment]
Thanks @jritta for informing that which suggests I need to find a work around in order to calculate force from multiple blocks having different material properties.

Regards
Pushkar

**Comment by jritta** [comment]
@ppandit95 
I think it is also not that difficult to extend the code in this direction. The computation is done in the file [Peridigm_Compute_Block_Data.cpp](https://github.com/peridigm/peridigm/blob/96e2a8f0c930367fb1aafb7577baa6ae4a4a07c7/src/compute/Peridigm_Compute_Block_Data.cpp) and in [Peridigm_HorizonManager.cpp](https://github.com/peridigm/peridigm/blob/96e2a8f0c930367fb1aafb7577baa6ae4a4a07c7/src/core/Peridigm_HorizonManager.cpp) you can find how a list of blocks given in the input deck can be processed.

Best,
Jonas
