### ISSUE TITLE
Unable to run supplementary scripts provided!!!

### ISSUE THREAD

**Issue by ppandit95** [peridigm/peridigm#232]
Dear Peridigm Community

I wish to convert my text file geometry to genesis file in order to visualise but when I run 
`python text_to_genesis.py ../../NewGeometryPeridigm/NewMesh/txtMesh.txt ../../NewGeometryPeridigm/NewMesh/Nodeset_bottom.txt ../../NewGeometryPeridigm/NewMesh/Nodeset_Top.txt ../../NewGeometryPeridigm/NewMesh/Nodelist_RBMX_bottom.txt ../../NewGeometryPeridigm/NewMesh/Nodeset_RBMZ_bottom.txt ../../NewGeometryPeridigm/NewMesh/Nodelist_RBMX_top.txt ../../NewGeometryPeridigm/NewMesh/Nodeset_RBMZ_top.txt 
`
I get the following output as -
`Traceback (most recent call last):
  File "/media/pushkar/Data/Cluster_files/peridigm/scripts/text_to_genesis.py", line 64, in <module>
    import exodus as exodus
  File "/home/pushkar/miniconda3/lib/python3.9/site-packages/exodus/__init__.py", line 5, in <module>
    from blist import sortedlist
  File "/home/pushkar/miniconda3/lib/python3.9/site-packages/blist/__init__.py", line 2, in <module>
    from blist._blist import *
ImportError: /home/pushkar/miniconda3/lib/python3.9/site-packages/blist/_blist.cpython-39-x86_64-linux-gnu.so: undefined symbol: _PyObject_GC_IS_TRACKED`

Any headers in this regard will be helpful.

Thanks in Advance
Pushkar

**Comment by ppandit95** [comment]
Also when I ran the same command after using "conda deactivate" I got the following output -
`Traceback (most recent call last):
  File "text_to_genesis.py", line 64, in <module>
    import exodus as exodus
ModuleNotFoundError: No module named 'exodus'`

**Comment by ppandit95** [comment]
After installing the exodus module, the script seems to run but I do have certain issues which I am sure I can take care of

**Comment by ppandit95** [comment]
After installing the exodus module,I was able to run the script but I encountered an AttributeError as -
`Traceback (most recent call last):
  File "text_to_genesis.py", line 255, in <module>
    main()
  File "text_to_genesis.py", line 244, in main
    write_exodus_file(textFileName, X, Y, Z, vol, blocks, nodeSets)
  File "text_to_genesis.py", line 141, in write_exodus_file
    exodusFile = exodus.exodus( exodusFileName,
AttributeError: module 'exodus' has no attribute 'exodus'
`
Any headers in this regard will provebeneficial.

Many Thanks 
Pushkar

**Comment by djlittl** [comment]
This is a result of changes that were made to the exodus.py module.  To get past this error, go into text_to_genesis.py and change the import statement to:

import exodus2 as exodus

**Comment by jritta** [comment]
> This is a result of changes that were made to the exodus.py module. To get past this error, go into text_to_genesis.py and change the import statement to:
> 
> import exodus2 as exodus

By executing the script with explicitly Python 2 should may fix this problem, see #132

**Comment by ppandit95** [comment]
As suggested by @djlittl ,I tried to make changes in import statement but still the their is an error as -
`Traceback (most recent call last):
  File "text_to_genesis.py", line 64, in <module>
    import exodus2 as exodus
ModuleNotFoundError: No module named 'exodus2'
`
Secondly,as @jritta suggested I tried to run the command explicitly with python2 I got the following error - 
`Traceback (most recent call last):
  File "text_to_genesis.py", line 66, in <module>
    import exodus as exodus
ImportError: No module named exodus
` 
Upon trying to resolve it using pip2,I failed to install exodus module with pip2.Any headers in this regard will be helpful

Many Thanks
Pushkar

**Comment by jritta** [comment]
Did you adapt the path to your trilinos installation!?
```python
# The following points to the location of exodus.py
path_to_exodus_py = 'trilinos_install_path/lib'

# The path above must also point to the netcdf libraries.  These libraries are not generally included in
# the Trilinos install.  One solution is to create symbolic links in this directory that point to the
# netcdf libraries (which you built as a TPL for Trilinos)
```
see [this line ](https://github.com/peridigm/peridigm/blob/96e2a8f0c930367fb1aafb7577baa6ae4a4a07c7/scripts/text_to_genesis.py#L55).

**Comment by ppandit95** [comment]
@jritta I didnt get by what you mean to "adapt to path" as I have installed peridigm by making all the sym links so I suppose I have done that and it it taking in the path but how do I debug it in case it is not.

**Comment by jritta** [comment]
No this is not the case, you manually have to provide the folder path to your trilinos installation. The value `'trilinos_install_path/lib'` of the variable `path_to_exodus_py` is just a dummy for the path to the `exodus.py` file. Usually it is in your trilinos installation in the subfolder `lib`.

**Comment by ppandit95** [comment]
Also,surprisingly I dont have exodus.py file in my trilinos installation although libexodus.a exists in trilinos installation

**Comment by jritta** [comment]
> see #132

**Comment by ppandit95** [comment]
Compiling with -D BUILD_SHARED_LIBS=ON I was able to find exodus2.py and exodus3.py but still libexodus.so is missing for which I am getting error and moreover in the script text_to_genesis.py it says one needs to have symbolic link with netcdf libraries as well .So the error I am getting is -
`Traceback (most recent call last):
  File "./text_to_genesis.py", line 64, in <module>
    import exodus3 as exodus
  File "/home/cmslab/pushkar/Trilinos/build/packages/seacas/scripts/exodus3.py", line 168, in <module>
    EXODUS_LIB = ctypes.cdll.LoadLibrary(EXODUS_SO)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 451, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/cmslab/pushkar/local/trilinos-12.0.1/lib/libexodus.so: cannot open shared object file: No such file or directory
`
And the configuration of Trilinos that I have used with CMake is -
`cmake \
-D CMAKE_INSTALL_PREFIX:PATH=/home/cmslab/pushkar/local/trilinos-12.0.1 \
-D CMAKE_CXX_FLAGS:STRING="-O2 -ansi -pedantic -ftrapv -Wall -Wno-long-long" \
-D CMAKE_BUILD_TYPE:STRING=RELEASE \
-D Boost_NO_SYSTEM_PATHS=ON \
-D TPL_ENABLE_MPI=ON \
-D CMAKE_CXX_COMPILER=/home/cmslab/pushkar/local/openmpi-4.1.1/bin/mpicxx \
-D CMAKE_C_COMPILER=/home/cmslab/pushkar/local/openmpi-4.1.1/bin/mpicc \
-D Trilinos_WARNINGS_AS_ERRORS_FLAGS:STRING="" \
-D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-D Trilinos_ENABLE_Teuchos:BOOL=ON \
-D Trilinos_ENABLE_Shards:BOOL=ON \
-D Trilinos_ENABLE_Sacado:BOOL=ON \
-D Trilinos_ENABLE_Epetra:BOOL=ON \
-D Trilinos_ENABLE_EpetraExt:BOOL=ON \
-D Trilinos_ENABLE_Ifpack:BOOL=ON \
-D Trilinos_ENABLE_AztecOO:BOOL=ON \
-D Trilinos_ENABLE_Amesos:BOOL=ON \
-D Trilinos_ENABLE_Anasazi:BOOL=ON \
-D Trilinos_ENABLE_Belos:BOOL=ON \
-D Trilinos_ENABLE_ML:BOOL=ON \
-D Trilinos_ENABLE_Phalanx:BOOL=ON \
-D Trilinos_ENABLE_Intrepid:BOOL=ON \
-D Trilinos_ENABLE_NOX:BOOL=ON \
-D Trilinos_ENABLE_Stratimikos:BOOL=ON \
-D Trilinos_ENABLE_Thyra:BOOL=ON \
-D Trilinos_ENABLE_Rythmos:BOOL=ON \
-D Trilinos_ENABLE_MOOCHO:BOOL=ON \
-D Trilinos_ENABLE_TriKota:BOOL=OFF \
-D Trilinos_ENABLE_Stokhos:BOOL=ON \
-D Trilinos_ENABLE_Zoltan:BOOL=ON \
-D Trilinos_ENABLE_Piro:BOOL=ON \
-D Trilinos_ENABLE_Teko:BOOL=ON \
-D Trilinos_ENABLE_SEACASIoss:BOOL=ON \
-D Trilinos_ENABLE_SEACAS:BOOL=ON \
-D Trilinos_ENABLE_SEACASBlot:BOOL=ON \
-D Trilinos_ENABLE_Pamgen:BOOL=ON \
-D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
-D Trilinos_ENABLE_TESTS:BOOL=ON \
-D TPL_ENABLE_Matio=OFF \
-D TPL_ENABLE_HDF5:BOOL=ON \
-D TPL_ENABLE_yaml-cpp:BOOL=ON \
-D yaml-cpp_INCLUDE_DIRS:PATH="/home/cmslab/pushkar/yaml-cpp/include" \
-D yaml-cpp_LIBRARY_DIRS:PATH="/home/cmslab/pushkar/yaml-cpp/build" \
-D HDF5_INCLUDE_DIRS:PATH="/home/cmslab/pushkar/local/hdf5-1.12.1/include" \
-D HDF5_LIBRARY_DIRS:PATH="/home/cmslab/pushkar/local/hdf5-1.12.1/lib" \
-D TPL_ENABLE_Netcdf:BOOL=ON \
-D Netcdf_INCLUDE_DIRS:PATH="/home/cmslab/pushkar/local/netcdf-4.8.1/include" \
-D Netcdf_LIBRARY_DIRS:PATH="/home/cmslab/pushkar/local/netcdf-4.8.1/lib" \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_BLAS:BOOL=ON \
-D TPL_ENABLE_LAPACK:BOOL=ON \
-D TPL_ENABLE_Boost:BOOL=ON \
-D Boost_INCLUDE_DIRS:PATH="/home/cmslab/pushkar/boost_1_77_0" \
-D Boost_LIBRARY_DIRS:PATH="/home/cmslab/pushkar/boost_1_77_0/stage/lib" \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D Trilinos_VERBOSE_CONFIGURE:BOOL=OFF \
-D Trilinos_ENABLE_TESTS=OFF \
-D BUILD_SHARED_LIBS=ON \
..
`
Any headers in this direction will be helpful.

Many Thanks
Pushkar

**Comment by ppandit95** [comment]
Do I need to compile peridigm as well because trilinos has been configured and compiled with shared libraries flag.Any suggestions in this regard will prove beneficial.

Many Thanks
Pushkar

**Comment by oldninja** [comment]
> Do I need to compile peridigm as well

I don't think so. That should only pertain to Trilinos. Can you try running it with `python2 text_to_genesis.py`?
