### ISSUE TITLE
How do I extract coordinate and volume of each material point from the model?

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#272]
Hi,

I am wondering how to extract coordinate and volume of each material point at every time step from the output. Is it possible to obtain the information through postprocessing in ParaView?

Thanks very much!

**Comment by diehlpk** [comment]
Hi, 

you can add the volume to the output file, e.g. `Weighted_Volume: true` and visualize it in Paraview. In addition, you can store the displacement field of each node in the output. So displacement + initial position = current position.
