### ISSUE TITLE
YAML error in peridigm 

### ISSUE THREAD

**Issue by suaid94** [peridigm/peridigm#284]
Hello everyone, 

I compiled Trilinos and Peridigm then I noticed that I do not have the yaml support in Trilinos. I added that then recompiled Trilinos. 
However, when I recompile peridigm, I still get the following error: 

"**** Error, YAML reader not available.  Trilinos must be compiled with YAML support to enable this feature.\n";
                msg += "**** You must obtain the yaml-cpp library, build it, and re-compile Trilinos with the the following flags:\n";
                msg += "****   TPL_ENABLE_yaml-cpp:BOOL=ON\n";
                msg += "****   yaml-cpp_INCLUDE_DIRS:PATH=/path/to/yaml/include\n";
                msg += "****   yaml-cpp_LIBRARY_DIRS:PATH=/path/to/yaml/lib\n";

Note that I already added those lines with the correct directories. 
Any ideas on how I fix that? 

Thanks.

**Comment by oldninja** [comment]
Clean all the directories and rebuild Trilinos and Peridigm.
