### ISSUE TITLE
Peridigm Test Error: exodiff: Files are different

### ISSUE THREAD

**Issue by suaid94** [peridigm/peridigm#287]
Greetings, 

I have an issue while compiling peridigm, some of the tests fail returning the following error:

exodiff: Files are different

Any ideas on what could be causing this or how to fix it?

One of the failed tests log file is attached for your reference.:
[DeformationGradient_PlaneStrainCompression_np1.log](https://github.com/peridigm/peridigm/files/10322711/DeformationGradient_PlaneStrainCompression_np1.log)

Thanks!

**Comment by oldninja** [comment]
I believe those tests need to be revised. Is that the only one failing?

**Comment by suaid94** [comment]
Hello @oldninja,

No, there are multiple ones that are failing with the same error. Please find them attached:


[DeformationGradient_PlaneStrainCompression_np1.log](https://github.com/peridigm/peridigm/files/10324504/DeformationGradient_PlaneStrainCompression_np1.log)
[DeformationGradient_PlaneStrainCompression_np4.log](https://github.com/peridigm/peridigm/files/10324505/DeformationGradient_PlaneStrainCompression_np4.log)
[DeformationGradient_PureShear_np1.log](https://github.com/peridigm/peridigm/files/10324506/DeformationGradient_PureShear_np1.log)
[DeformationGradient_PureShear_np4.log](https://github.com/peridigm/peridigm/files/10324507/DeformationGradient_PureShear_np4.log)
[DeformationGradient_SimpleShear_np1.log](https://github.com/peridigm/peridigm/files/10324508/DeformationGradient_SimpleShear_np1.log)
[DeformationGradient_SimpleShear_np4.log](https://github.com/peridigm/peridigm/files/10324509/DeformationGradient_SimpleShear_np4.log)
[DeformationGradient_SolidRotation_np1.log](https://github.com/peridigm/peridigm/files/10324510/DeformationGradient_SolidRotation_np1.log)
[DeformationGradient_SolidRotation_np4.log](https://github.com/peridigm/peridigm/files/10324511/DeformationGradient_SolidRotation_np4.log)
[IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np1.log](https://github.com/peridigm/peridigm/files/10324512/IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np1.log)
[IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np4.log](https://github.com/peridigm/peridigm/files/10324513/IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np4.log)
[IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np1.log](https://github.com/peridigm/peridigm/files/10324514/IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np1.log)
[IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np4.log](https://github.com/peridigm/peridigm/files/10324515/IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np4.log)
[Pals_Simple_Shear.log](https://github.com/peridigm/peridigm/files/10324516/Pals_Simple_Shear.log)
[ViscoplasticNeedlemanFullyPrescribedTension_NoFlaw_np1.log](https://github.com/peridigm/peridigm/files/10324517/ViscoplasticNeedlemanFullyPrescribedTension_NoFlaw_np1.log)
[ViscoplasticNeedlemanFullyPrescribedTension_NoFlaw_np4.log](https://github.com/peridigm/peridigm/files/10324518/ViscoplasticNeedlemanFullyPrescribedTension_NoFlaw_np4.log)
[ViscoplasticNeedlemanFullyPrescribedTension_WithFlaw_np1.log](https://github.com/peridigm/peridigm/files/10324519/ViscoplasticNeedlemanFullyPrescribedTension_WithFlaw_np1.log)
[ViscoplasticNeedlemanFullyPrescribedTension_WithFlaw_np4.log](https://github.com/peridigm/peridigm/files/10324520/ViscoplasticNeedlemanFullyPrescribedTension_WithFlaw_np4.log)

**Comment by bdas123** [comment]
If you need help revising the old files, please feel free to reach out to me and @suaid94
