### ISSUE TITLE
Some questions about post-processing of ParaView

### ISSUE THREAD

**Issue by nsy19971013** [peridigm/peridigm#288]
I want to see the stress distribution of the test piece, but it has data only on the nodeset with boundary conditions set.
<img width="497" alt="1672404456697" src="https://user-images.githubusercontent.com/117352474/210071785-c623f7c8-4af9-4b79-a486-33a48f37bfc5.png">
<img width="496" alt="微信截图_20221230205215" src="https://user-images.githubusercontent.com/117352474/210072103-f024f9ff-15cf-46d0-b6c1-e1c4d72b5bdd.png">

**Comment by jritta** [comment]
Hi @nsy19971013 ,

Determining the stress distribution is not that trivial. It depends on what kind of stress you want and which material model you use. For example for the `Elastic` material model the so called `Partial_Stress` can be computed. This is a form of a virial stress. Not all material models compute a stress. If you want something special you have to implement it on your own. As starting point you maybe can use the "Elastic" material model, see:

- [Peridigm_ElasticMaterial.cpp](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ElasticMaterial.cpp)
- [elastic.cxx](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/elastic.cxx)

As far as I know following material models compute some kind of stress formulation:

- [Elastic Bond Associated Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ElasticBondAssociatedCorrespondenceMaterial.cpp),
- [Elastic Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ElasticCorrespondenceMaterial.cpp),
- [Elastic Hypoelastic Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ElasticHypoelasticCorrespondenceMaterial.cpp),
- [Elastic](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ElasticMaterial.cpp),
- [Elastic Plastic Bond Associated Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ElasticPlasticBondAssociatedCorrespondenceMaterial.cpp),
- [Elastic Plastic Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ElasticPlasticCorrespondenceMaterial.cpp),
- [Elastic Plastic Hypoelastic Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ElasticPlasticHypoelasticCorrespondenceMaterial.cpp),
- [Isotropic Hardening Bond Associated Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_IsotropicHardeningPlasticBondAssociatedCorrespondenceMaterial.cpp),
- [Isotropic Hardening Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_IsotropicHardeningPlasticCorrespondenceMaterial.cpp),
- [Isotropic Hardening Hypoelastic Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_IsotropicHardeningPlasticHypoelasticCorrespondenceMaterial.cpp) and
- [Viscoplastic Needleman Correspondence](https://github.com/peridigm/peridigm/blob/d369819345c2c72535ff4fdb0edb31f9d3a96f6f/src/materials/Peridigm_ViscoPlasticNeedlemanCorrespondenceMaterial.cpp)

Best,
Jonas

PS: If you just need the force for the middle part, as you have indicated in the attached picture, you can simply dump the force distribution by activating it in the `Output` section.
