### ISSUE TITLE
Implication of failed trilinos tests

### ISSUE THREAD

**Issue by milyas7** [peridigm/peridigm#29]
I am trying to build trilinos and following tests are failing:

FINITE_VALUE_HAVE_GLOBAL_ISNAN
FINITE_VALUE_HAVE_GLOBAL_ISINF
HAVE_TEUCHOS_LAPACKLARND
HAVE_CXX_PRAGMA_WEAK

Is it possible to know what are the implications on build of peridigm?

**Comment by djlittl** [comment]
I personally would not worry too much about achieving 100% of tests passing for Trilinos.  I would be much more concerned if any of the Peridigm tests fail.  In theory, we should obviously strive for 100% of tests passing for both Trilinos and Peridigm, but I am not surprised that you’re seeing a few Trilinos tests fail.

If you want to know more about those particular tests, you should forward your question to the Trilinos mailing lists.  At first blush, they look like they are looking for specific compiler features.

Best,
Dave

**Comment by johntfoster** [comment]
I agree with @djlittl, and since this is not a Peridigm issue, I am closing.
