### ISSUE TITLE
When I Run Peridigm An error occurred in MPI_Comm_create_keyval

### ISSUE THREAD

**Issue by nsy19971013** [peridigm/peridigm#290]
I guess it‘s some trouble with Openmpi？Is there something wrong?

#openmpi
export CC=$home/local/openmpi/bin/mpicc
export CXX=$home/local/openmpi/bin/mpicxx
export CF=$home/local/openmpi/bin/mpif90
export FC=$home/local/openmpi/bin/mpif90
export F77=$home/local/openmpi/bin/mpif77
export LIBRARY_PATH=$home/local/openmpi/lib/:${LIBRARY_PATH}
export PATH=$home/local/openmpi/bin/:$PATH

Peridigm disk_impact.yaml

-- Peridigm
-- version 1.5.0 (Dev)

[dp-virtual-machine:2001] *** An error occurred in MPI_Comm_create_keyval
[dp-virtual-machine:2001] *** reported by process [1238564865,0]
[dp-virtual-machine:2001] *** on communicator MPI_COMM_WORLD
[dp-virtual-machine:2001] *** MPI_ERR_ARG: invalid argument of some other kind
[dp-virtual-machine:2001] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[dp-virtual-machine:2001] ***    and potentially your MPI job)

**Comment by diehlpk** [comment]
How do you start the code?

Are you using `mpirun ` or` mpiexec`?
