### ISSUE TITLE
Why didn't the bond break

### ISSUE THREAD

**Issue by gagbeer** [peridigm/peridigm#304]
Dear Developer
As a beginner in Peridynamic. I would like to achieve tensile tests of center-cracked plates with Peridigm(A case from the “Peridynamic Theory and Its Application”). But I failed. The bond didn't break. I'd like to know why the bond in my test didn't break. At the same time, I found that the crack opening displacement is the same with and without damage.
It is a 50*50mm plate with a 10mm crack test in the center. This is my input script file.
[input.txt](https://github.com/peridigm/peridigm/files/10895460/input.txt)
Thanks
Gagbeer

**Comment by djlittl** [comment]
Roughly speaking, your critical stretch value is a bit over 4% strain.  Is your loading large enough to create that strain?

If you plot damage, do you see any nonzero values?

For troubleshooting, you could try using a small value of critical stretch, maybe 0.0001, just to make sure it's working.

**Comment by gagbeer** [comment]
Thank you for your answer.

In the damage diagram drawn before, the damage value is always 0. 
I think I didn't set the proper boundary conditions, and the proper critical stretch amount of the model.

After adjusting the boundary conditions, I tried to break several simple models, and the maximum damage was 0.41 instead of 1. Does that mean it's broken?

**Comment by djlittl** [comment]
The variable that is plotted in this case ("Damage") is the percentage of bonds that are broken for each node in the model.  So a value of 0.41 means that 41% of the bonds attached to that node are broken.  If you broke the model into two pieces, I'd expect the percentage of broken bonds for nodes near the failure surface to be in the range of roughly 40% - 60%.  So yes, I think this means you have a bona fide crack in your model.

Note that Peridigm has a different internal variable called "Bond_Damage".  This is the per-bond variable that ranges from zero to one, with a value of one indicating that the individual bond is broken.  For the critical stretch bond failure rule, the only allowable values are zero (unbroken) or one (broken).  More generally, bond failure laws could have intermediate values, indicating partial damage.  The Bond_Damage variable is really hard to post-process for visualization and whatnot.  Writing bond data to disk increases the size of the output file by several orders of magnitude.  And if you try to visualize the bonds in Paraview, there are so many of them that it's nearly impossible to isolate individual bonds or reach any useful conclusions.  Hence we use the per-node variable "Damage", which as described above is the percentage of bonds that are broken for a given node.

**Comment by gagbeer** [comment]
Thanks so much for your detailed response, David.The model was successfully cracked
