### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by VictorEijkhout** [peridigm/peridigm#313]
```-D BOOST_ROOT=/usr/local/boost/ \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++11
```

1. The cmake says that `BOOST_ROOT` is not used.

2. I think you need to compile with C++17 since you're using `std::bool_constant`

**Comment by oldninja** [comment]
Boost was removed at some point if I recall correctly.

**Comment by oldninja** [comment]
I think the std::bool_constant is available since c++11...

**Comment by VictorEijkhout** [comment]
Nope. https://en.cppreference.com/w/cpp/types/integral_constant

**Comment by VictorEijkhout** [comment]
Please see my latest comment. I think instructions need to be updated. Up to you.
