### ISSUE TITLE
Trouble Reinstalling Peridigm

### ISSUE THREAD

**Issue by bdas123** [peridigm/peridigm#314]
Hello,

I am trying to reinstall Peridigm to keep the program updated using Trilinos/13.0.

Here is my shell script: 

```
#!/usr/bin/env bash

export INSTALL_LOCATION=$WORK2'/projects/peridigm3'

module load intel impi trilinos
module load cmake boost

export F77='which mpif90 || /bin/true'
export COPTFLAGS="-O1"
export CC='which mpicc || /bin/true'
export CXX='which mpicxx || /bin/true'

rm -f CMakeCache.txt

cmake \
  -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_LOCATION \
  -D CMAKE_CXX_COMPILER:STRING='mpicxx' \
  -D CMAKE_C_COMPILER:STRING='mpicc' \
  -D CMAKE_BUILD_TYPE:STRING=Release \
  -D CMAKE_C_FLAGS:STRING="${COPTFLAGS}" \
  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} -std=c++11" \
  -D BOOST_ROOT:STRING=$TACC_BOOST_DIR \
```

I get the following error:

CMakeFiles/Peridigm.dir/core/Peridigm_Main.cpp.o: In function `main':
Peridigm_Main.cpp:(.text+0x24d): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Peridigm_Main.cpp:(.text+0x37f): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Peridigm_Main.cpp:(.text+0x5c9): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'

Do you have any idea what the problem could be?

**Comment by andrisfreimanis** [comment]
I think the newer Trilinos version require C++14 standard. You can check a similar discussion here: https://github.com/peridigm/peridigm/issues/295

Best regards
Andris

From: Barun Das ***@***.***>
Sent: perjantai 14. huhtikuuta 2023 8.39
To: peridigm/peridigm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [peridigm/peridigm] Trouble Reinstalling Peridigm (Issue #314)


Hello,

I am trying to reinstall Peridigm to keep the program updated using Trilinos/13.0.

Here is my shell script:

#!/usr/bin/env bash



export INSTALL_LOCATION=$WORK2'/projects/peridigm3'



module load intel impi trilinos

module load cmake boost



export F77='which mpif90 || /bin/true'

export COPTFLAGS="-O1"

export CC='which mpicc || /bin/true'

export CXX='which mpicxx || /bin/true'



rm -f CMakeCache.txt



cmake \

  -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_LOCATION \

  -D CMAKE_CXX_COMPILER:STRING='mpicxx' \

  -D CMAKE_C_COMPILER:STRING='mpicc' \

  -D CMAKE_BUILD_TYPE:STRING=Release \

  -D CMAKE_C_FLAGS:STRING="${COPTFLAGS}" \

  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} -std=c++11" \

  -D BOOST_ROOT:STRING=$TACC_BOOST_DIR \

I get the following error:

CMakeFiles/Peridigm.dir/core/Peridigm_Main.cpp.o: In function main': Peridigm_Main.cpp:(.text+0x24d): undefined reference to std::basic_ostream<char, std::char_traits >& std::operator<< <char, std::char_traits, std::allocator >(std::basic_ostream<char, std::char_traits >&, std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)'
Peridigm_Main.cpp:(.text+0x37f): undefined reference to std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' Peridigm_Main.cpp:(.text+0x5c9): undefined reference to std::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_create(unsigned long&, unsigned long)'

Do you have any idea what the problem could be?

-

**Comment by bdas123** [comment]
I rebuilt Trilinos using C++14, but I am still getting an error (found in the attached text file). 

[make_output.txt](https://github.com/peridigm/peridigm/files/11249687/make_output.txt)

The following is the Peridigm shell script: 

```
#!/usr/bin/env bash

export INSTALL_LOCATION=$WORK2'/projects/peridigm3'

module load intel impi trilinos
module load cmake boost 

export F77='which mpif90 || /bin/true'
export COPTFLAGS="-O1"
export CC='which mpicc || /bin/true'
export CXX='which mpicxx || /bin/true'

rm -f CMakeCache.txt

cmake \
  -D CMAKE_INSTALL_PREFIX:PATH=$INSTALL_LOCATION \
  -D CMAKE_CXX_COMPILER:STRING='mpicxx' \
  -D CMAKE_C_COMPILER:STRING='mpicc' \
  -D CMAKE_BUILD_TYPE:STRING=Release \
  -D CMAKE_C_FLAGS:STRING="${COPTFLAGS}" \
  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} -std=c++14" \
  -D TRILINOS_DIR:PATH=$WORK2'/projects/trilinos' \
  -D BOOST_ROOT:STRING=$TACC_BOOST_DIR \
  ..

```

The following is the Trilinos shell script: 

```
#!/usr/bin/env bash

module load cmake python2 boost phdf5 netcdf 
export F77='which mpif90 || /bin/true'
export COPTFLAGS="-O1"
export CC='which mpicc || /bin/true'
export CXX='which mpicxx || /bin/true'

export INSTALL_LOCATION=$WORK2'/projects/trilinos/'

cmake \
  -D BUILD_SHARED_LIBS:BOOL=ON \
  -D Trilinos_VERBOSE_CONFIGURE=OFF \
  -D CMAKE_VERBOSE_MAKEFILE=ON \
  -D Trilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
  -D Trilinos_ENABLE_TESTS:BOOL=OFF \
  -D Trilinos_ENABLE_EXAMPLES:BOOL=OFF \
  \
  -D CMAKE_INSTALL_PREFIX:PATH=${INSTALL_LOCATION} \
  -D CMAKE_BUILD_TYPE:STRING=RELEASE \
  -D CMAKE_C_FLAGS:STRING="${COPTFLAGS} -mkl" \
  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} -mkl -DMPICH_SKIP_MPICXX" \
  \
  -D BLAS_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D BLAS_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D BLAS_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  -D LAPACK_INCLUDE_DIRS:PATH="${TACC_MKL_INC}" \
  -D LAPACK_LIBRARY_DIRS:PATH="${TACC_MKL_LIB}" \
  -D LAPACK_LIBRARY_NAMES:STRING="mkl_intel_lp64;mkl_sequential;mkl_core;pthread" \
  \
  -D TPL_ENABLE_MPI:BOOL=ON \
  -D MPI_EXEC:FILEPATH="/usr/local/bin/ibrun" \
  -D TPL_ENABLE_GLM=OFF \
  -D TPL_ENABLE_Matio=OFF \
  \
  -D TPL_ENABLE_Boost:BOOL=ON \
  -D Boost_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D Boost_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  -D TPL_ENABLE_BoostLib:BOOL=ON \
  -D BoostLib_INCLUDE_DIRS:PATH=$TACC_BOOST_INC      \
  -D BoostLib_LIBRARY_DIRS:PATH=$TACC_BOOST_LIB      \
  \
  -D TPL_ENABLE_HDF5:BOOL=ON \
  -D HDF5_INCLUDE_DIRS:PATH=$TACC_HDF5_INC    \
  -D HDF5_LIBRARY_DIRS:PATH=$TACC_HDF5_LIB    \
  -D TPL_ENABLE_Netcdf:BOOL=ON \
  -D Netcdf_INCLUDE_DIRS:PATH=$TACC_NETCDF_INC    \
  -D Netcdf_LIBRARY_DIRS:PATH=$TACC_NETCDF_LIB    \
  \
  -D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=ON \
  -D Trilinos_ENABLE_ALL_FORWARD_DEP_PACKAGES:BOOL=ON    \
  -D Trilinos_ENABLE_AztecOO:BOOL=ON \
  -D Trilinos_ENABLE_Belos:BOOL=ON \
  -D Trilinos_ENABLE_Epetra:BOOL=ON \
  -D Trilinos_ENABLE_EpetraExt:BOOL=ON \
  -D Trilinos_ENABLE_FEI:BOOL=OFF \
  -D Trilinos_ENABLE_Ifpack:BOOL=ON \
  -D Trilinos_ENABLE_Intrepid:BOOL=ON \
  -D Trilinos_ENABLE_Isorropia:BOOL=ON \
  -D Trilinos_ENABLE_MueLu:BOOL=ON \
  -D Trilinos_ENABLE_NOX:BOOL=ON \
  -D Trilinos_ENABLE_Pamgen:BOOL=ON \
  -D Trilinos_ENABLE_Panzer:BOOL=OFF \
  -D Trilinos_ENABLE_Phalanx:BOOL=ON \
  -D Phalanx_EXPLICIT_TEMPLATE_INSTANTIATION:BOOL=ON \
  -D Trilinos_ENABLE_Sacado:BOOL=ON \
  -D Trilinos_ENABLE_SEACAS:BOOL=ON \
  -D Trilinos_ENABLE_SECONDARY_STABLE_CODE:BOOL=ON \
  -D Trilinos_ENABLE_Shards:BOOL=ON \
  -D Trilinos_ENABLE_STK:BOOL=OFF \
  -D Trilinos_ENABLE_Sundance:BOOL=OFF \
  -D Trilinos_ENABLE_Teuchos:BOOL=ON \
  -D Trilinos_ENABLE_Tpetra:BOOL=OFF \
  -D Trilinos_ENABLE_Zoltan:BOOL=ON \
  -D CMAKE_PYTHON_INCLUDE_DIR:PATH="${TACC_PYTHON2_INC}" \
  -D CMAKE_PYTHON_LIBRARIES:STRING="${TACC_PYTHON2_LIB}" \
  -D Trilinos_ENABLE_PyTrilinos:Bool=OFF \
  -D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} -std=c++14" \
  \
  ..
```

**Comment by Aitare** [comment]
It seems that the C++ standard flag for the Trilinos build script is correctly set to C++14, but it's not set for the Peridigm build script. You should modify the Peridigm shell script to set the C++ standard flag to C++14 as well.

Change the line in the Peridigm shell script from:

bash

-D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} -std=c++14" \

to

bash

-D CMAKE_CXX_FLAGS:STRING="${COPTFLAGS} -std=c++14 -D_GLIBCXX_USE_CXX11_ABI=0" \

Also, make sure that both Trilinos and Peridigm are built with the same compiler versions (Intel, in this case). look for conflicts or discrepancies in the loaded modules.

After making the necessary changes, clean your build directories for both Trilinos and Peridigm, and try build them again.
