### ISSUE TITLE
Communication btw procs

### ISSUE THREAD

**Issue by masoudbehzadinasab** [peridigm/peridigm#32]
Let's say there is a scalar element field variable that I need to find its largest value through all the PD nodes at some point in the material evaluation. What would be an easy and efficient way for the processors communication here? Would be great if you can refer me to part of the code where I can find similar MPI management stuff. 

Thank you in advance for your comment. 

Regards,
Masoud

**Comment by MDBrothers** [comment]
Massoud you are looking for something like:

http://mpitutorial.com/tutorials/mpi-reduce-and-allreduce/

use MPI_MAX as your operator.

Cheers.

**Comment by johntfoster** [comment]
@masoudbehzadinasab if your field variable is stored as an EpetraVector, you should probably use the Epetra interface and call `MaxValue` on the vector

https://trilinos.org/docs/dev/packages/epetra/doc/html/classEpetra__MultiVector.html

**Comment by djlittl** [comment]
See also Peridigm_Compute_BlockData.cpp.  This compute class does almost exactly what you're proposing, albeit for post-processing.

One thing to keep in mind is that if you're looking at an element variable, they are block specific.  In other words, it's possible to have a simulation in which a certain element variable exists only in some of the blocks.  This should be taken into consideration when coding up your all reduce.

**Comment by masoudbehzadinasab** [comment]
Thank you all for your prompt responses. 

@djlittl That's exactly what I was looking for. Big help! 

Thanks.
