### ISSUE TITLE
Damage model

### ISSUE THREAD

**Issue by DP52** [peridigm/peridigm#320]
What damage model can be used besides Critical Stretch?

When I do crack propagation problems, using elastic materials and Critical Stretch model, the crack can grow normally. But when the material is replaced by other materials, the crack is only open and does not expand, so I am thinking about whether it is a damage model. However, other damage models cannot be used normally.

The following is an error when using the Interface Aware model
[
![图片1](https://user-images.githubusercontent.com/128480691/236595336-6ca4f3ab-f6d7-4eb9-9587-fb24a3cd940c.png)
](url)

In addition, when I used the Critical Energy model, I was prompted that this model was not available, as shown in the figure below.
[
![图片2](https://user-images.githubusercontent.com/128480691/236599060-aa4a284a-fc08-4ea1-8d76-e8ada63e7d80.png)
](url)

How to solve the problem that the crack only opens but does not expand?

**Comment by oldninja** [comment]
>What damage model can be used besides Critical Stretch?
I believe that is the only damage model implemented on this master branch of Peridigm. You can create your own damage model and apply it accordingly. 

>In addition, when I used the Critical Energy model, I was prompted that this model was not available, as shown in the figure below.
Correct, that is not a yet-supported model in the master Peridigm repo.

**Comment by diehlpk** [comment]
Yes, you would need to implement your own damage model. ### 

Maybe this paper will help you to understand how to add a new damage model

https://link.springer.com/article/10.1007/s42102-023-00100-0

**Comment by oldninja** [comment]
> Maybe this paper will help you to understand how to add a new damage model

This is great!
