### ISSUE TITLE
Spring Constant

### ISSUE THREAD

**Issue by bdas123** [peridigm/peridigm#331]
Hello, Page 155 of the  [Peridigm User Manual](chrome-extension://bdfcnmeidppjeaggnmidamkiddifkdib/viewer.html?file=https://elib.dlr.de/126320/1/Peridigm_Users_Guide.pdf) suggests that the spring constant should be 10x the force of the constitutive model. I am running a simulation right now to determine the maximum force value. Would this be the "Contact Force", "Contact Force Density", "Force", or "Force Density" output?

**Comment by oldninja** [comment]
Force density I believe.

**Comment by oldninja** [comment]
Yes. I would try to use consistent units, just like in any FEM software.

**Comment by djlittl** [comment]
<img width="763" alt="consistent_units_table" src="https://github.com/peridigm/peridigm/assets/5599237/162cfeaa-2807-4398-853c-6fccfa30b073">

Agreeing with @oldninja, adding a useful table.
