### ISSUE TITLE
Difficulty building Peridigm (master)

### ISSUE THREAD

**Issue by smenon92** [peridigm/peridigm#34]
Hi,
**_## EDIT: Issue was with the VM lacking virtual memory.
 I'm not fiddling with make -j anymore. I've built Peridigm with the serial make.
I appreciate your quick responses._**
I've been trying to build Peridigm from version 1.4.1 and later from the master version here on GitHub. 
I am running Ubuntu 16.04 on a Virtual Machine.
With both versions configuring seems to finish without errors, but the 'make -j' command just hangs @50%. I'm not really sure what to do, since there is no .log file for the 'make' process,AFAIK.

[ 50%] Building CXX object src/CMakeFiles/PeridigmLib.dir/materials/Peridigm_ViscoPlasticNeedlemanCorrespondenceMaterial.cpp.o
[ 51%] Building CXX object src/CMakeFiles/PeridigmLib.dir/materials/Peridigm_MultiphysicsElasticMaterial.cpp.o
[ 51%] Building CXX object src/CMakeFiles/PeridigmLib.dir/materials/Peridigm_Pals_Model.cpp.o

I've run  'make -j' several times and have never got past this point. How do I begin to diagnose this?

Thanks!

**Comment by MDBrothers** [comment]
A basic first step is to pipe the output  of make from the terminal to a file yourself with:

$ make -j 8 > log.txt

Then search for the word 'error'.

Chances are you neglected to modify you library path environment variable to include a dependency for peridigm.

**Comment by LasseSH** [comment]
Hi,
you can set the Makefile variable VERBOSE to 1 to get more information and write the output directly to a log file via

make -j VERBOSE=1 > make.log 2>&1

With a second terminal in the same folder you can follow the process by

tail -f make.log

**Comment by smenon92** [comment]
@MDBrothers @LasseSH Will try that and update. Thanks.

**Comment by smenon92** [comment]
S[ 51%] Building CXX object src/CMakeFiles/PeridigmLib.dir/materials/Peridigm_ViscoPlasticNeedlemanCorrespondenceMaterial.cpp.o
cd /home/sm92/Desktop/Peridigm/PeridigmBuildParallel/src && /usr/bin/mpicxx   -DPD_LIB_EXPORTS_MODE -I/usr/local/trilinos/include -I/home/sm92/Desktop/HDF5.1/CMake-hdf5-1.10.1/HDF_Group/HDF5/1.10.1/include -I/home/sm92/Desktop/boost_1_64_0/ManualBuild/include -I/home/sm92/Desktop/NetCDF4/netcdf-4.4.1.1/installdir/include -I/home/sm92/Desktop/Peridigm/peridigm-master -I/home/sm92/Desktop/Peridigm/peridigm-master/src -I/home/sm92/Desktop/Peridigm/peridigm-master/src/core -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io/discretization -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io/mesh_input -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io/mesh_input/quick_grid -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io/mesh_output -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io/bond_volume -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io/utilities -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io/pdneigh -I/home/sm92/Desktop/Peridigm/peridigm-master/src/contact -I/home/sm92/Desktop/Peridigm/peridigm-master/src/materials -I/home/sm92/Desktop/Peridigm/peridigm-master/src/damage -I/home/sm92/Desktop/Peridigm/peridigm-master/src/api -I/home/sm92/Desktop/Peridigm/peridigm-master/src/compute -I/home/sm92/Desktop/Peridigm/peridigm-master/src/io/bond_volume/quick_grid  -O2 -Wall -ansi -pedantic -Wno-long-long -ftrapv -Wno-deprecated -std=gnu++11 -O3 -DNDEBUG   -o CMakeFiles/PeridigmLib.dir/materials/Peridigm_ViscoPlasticNeedlemanCorrespondenceMaterial.cpp.o -c /home/sm92/Desktop/Peridigm/peridigm-master/src/materials/Peridigm_ViscoPlasticNeedlemanCorrespondenceMaterial.cpp
**_virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
g++: internal compiler error: Killed (program cc1plus)_**
1)That's the relevant portion of the log file just before 'make -j' got stuck. Looks like a VM issue. Surprising really, I've already given it 5GB of RAM. I'll try taking it up to 8 and see if anything changes.
2) Out of curiosity I used the serial make and that built just fine.
