### ISSUE TITLE
Search Radius and Contact Radius

### ISSUE THREAD

**Issue by bdas123** [peridigm/peridigm#345]
Hello, are there any rules of thumb for selecting a search radius and contact radius?

My contact radius (0.061 in) is half the mesh size (0.12 in). 

Horizon is 0.37 in.

**Comment by diehlpk** [comment]
For the search radius delta = 3 times mesh size is a common choice for bond-based models. 

The contact radius, I would say depends on the material or maybe your application.

**Comment by bdas123** [comment]
Awesome, thank you!

**Comment by bdas123** [comment]
Based on your experience, what is a common range of the size of the contact radius (relative to the mesh size)?
