### ISSUE TITLE
Compatibility with Trilinos 14.x.x is not given

### ISSUE THREAD

**Issue by jritta** [peridigm/peridigm#348]
Dear community,

I am trying to compile Peridigm with the current Trilinos version 14.2.0, but I am facing some issues. Since Trilinos 14.0.0, the build system has been changed to modern CMake, which breaks backward compatibility and raises issues building Peridigm. First of all, I am encountering a linking error for the test `ut_ringCellVolumeFraction.cxx`:
```
/usr/bin/ld: ../libQuickGridVolFrac.a(calculators.cxx.o): in function `BOND_VOLUME::QUICKGRID::RingVolumeFractionCalculator::operator()(double const*, double const*) const':
calculators.cxx:(.text+0x3ac): undefined reference to `QUICKGRID::getDiscretization(QUICKGRID::Spec1D const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [src/io/bond_volume/quick_grid/unit_test/CMakeFiles/ut_ringCellVolumeFraction.dir/build.make:239: src/io/bond_volume/quick_grid/unit_test/ut_ringCellVolumeFraction] Error 1
make[1]: *** [CMakeFiles/Makefile2:1497: src/io/bond_volume/quick_grid/unit_test/CMakeFiles/ut_ringCellVolumeFraction.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
By disabling this test, I can at least compile Peridigm, but some tests still fail due to missing YAML support, even though Trilinos is compiled with YAML support. Up to now, I am unsure if the above-mentioned linking error can be traced back to the broken backward compatibility of Trilinos with the current build system used in Peridigm.

The second issue is that in [CMakeLists.txt](https://github.com/peridigm/peridigm/blob/734a10a67edcebf6989462dd05acbf4d60079674/CMakeLists.txt#L48C1-L86C8), it is tested for the variable `Trilinos_TPL_LIST` to ensure that NetCDF is installed, and it is also checked if the Trilinos installation comes with YAML support. However, in Trilinos 14.x.x, all variables `Trilinos_TPL_*` no longer exist. Therefore, during the CMake configuration of Peridigm, the message
```
FATAL_ERROR 

Error:  Netcdf NOT found.  Netcdf is a REQUIRED Trilinos TPL.
```
is displayed.

@djlittl , do you have any ideas on how we can fix this problem in the build system of Peridigm? Do you perhaps also have a guess about the origin of this linking error for the test `ut_ringCellVolumeFraction.cxx`?

Best,
Jonas

PS: I already opened an [issue](https://github.com/trilinos/Trilinos/issues/12077) in the Trilinos repo.

**Comment by oldninja** [comment]
@jritta  were you able to test the branch from [Issue 12077](https://github.com/trilinos/Trilinos/issues/12077#issuecomment-1664635921)
