### ISSUE TITLE
Error In Peridigm make & make install in Ubuntu

### ISSUE THREAD

**Issue by Bapun-kumar** [peridigm/peridigm#358]
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/Peridigm.dir/build.make:682: src/Peridigm] Error 1
make[1]: *** [CMakeFiles/Makefile2:1287: src/CMakeFiles/Peridigm.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

**Comment by diehlpk** [comment]
@Bapun-kumar can you please provide more details?
