### ISSUE TITLE
CMake test fail with peridigm 1.5.0 (master)

### ISSUE THREAD

**Issue by HongyangDing** [peridigm/peridigm#359]
Hi, 
I have an issue while compiling peridigm, some of the tests fail returning the following errors:

93% tests passed, 13 tests failed out of 195

Total Test time (real) = 138.37 sec

The following tests FAILED:
	183 - InterfaceAwareDamageModelOneBlockNP1 (Failed)
	184 - InterfaceAwareDamageModelTwoBlocksSameValuesNP1 (Failed)
	185 - InterfaceAwareDamageModelTwoBlocksDifferentValuesNP1 (Failed)
	186 - InterfaceAwareDamageModelTwoBlocksDifferentValuesNP2 (Failed)
	187 - InterfaceAwareDamageModelTwoBlocksDifferentValuesNP3 (Failed)
	188 - PredictorFromPreviousSolverNOXFalse_np1 (Failed)
	189 - PredictorFromPreviousSolverNOXTrue_np1 (Failed)
	190 - PredictorFromPreviousSolverNOXFalse_np3 (Failed)
	191 - PredictorFromPreviousSolverNOXTrue_np3 (Failed)
	192 - PredictorFromPreviousSolverQSFalse_np1 (Failed)
	193 - PredictorFromPreviousSolverQSTrue_np1 (Failed)
	194 - PredictorFromPreviousSolverQSFalse_np3 (Failed)
	195 - PredictorFromPreviousSolverQSTrue_np3 (Failed)

My cmake script is as follows
`cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D CMAKE_INSTALL_PREFIX:PATH=/home/dinghy/bin/ \
-D Trilinos_DIR:PATH=/home/dinghy/bin/trilinos_13.2/lib/cmake/Trilinos \
-D Trilinos_LIBRARY_DIRS:PATH=/home/dinghy/bin/trilinos_mybuild10/lib \
-D CMAKE_C_COMPILER:STRING=/home/dinghy/bin/openmpi_5.0.0rc/bin/mpicc \
-D CMAKE_CXX_COMPILER:STRING=/home/dinghy/bin/openmpi_5.0.0rc/bin/mpicxx \
-D BOOST_ROOT:PATH=/home/dinghy/bin/boost_1.83.0/ \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++17 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
/home/dinghy/peridigm_required/peridigm-master`

The log file does not give any hint about the error 
I think it may be due to the damage model. 

Any ideas?
Thanks!

Here is part of the log file

192/195 Testing: PredictorFromPreviousSolverQSFalse_np1
192/195 Test: PredictorFromPreviousSolverQSFalse_np1
Command: "/opt/miniconda3/bin/python" "./np1/PredictorFromPreviousSolverQSFalse.py"
Directory: /home/dinghy/peridigm_required/peridigm-master/mybuild1/test/verification/PredictorFromPreviousSolver
"PredictorFromPreviousSolverQSFalse_np1" start time: Sep 22 21:25 CST
Output:

<end of output>
Test time =   0.09 sec

Test Failed.
"PredictorFromPreviousSolverQSFalse_np1" end time: Sep 22 21:25 CST
"PredictorFromPreviousSolverQSFalse_np1" time elapsed: 00:00:00

193/195 Testing: PredictorFromPreviousSolverQSTrue_np1
193/195 Test: PredictorFromPreviousSolverQSTrue_np1
Command: "/opt/miniconda3/bin/python" "./np1/PredictorFromPreviousSolverQSTrue.py"
Directory: /home/dinghy/peridigm_required/peridigm-master/mybuild1/test/verification/PredictorFromPreviousSolver
"PredictorFromPreviousSolverQSTrue_np1" start time: Sep 22 21:25 CST
Output:

<end of output>
Test time =   0.09 sec

Test Failed.
"PredictorFromPreviousSolverQSTrue_np1" end time: Sep 22 21:25 CST
"PredictorFromPreviousSolverQSTrue_np1" time elapsed: 00:00:00

**Comment by oldninja** [comment]
These tests usually fail in my case too. No issues with the others? If not, then installation is correct.

**Comment by HongyangDing** [comment]
> These tests usually fail in my case too. No issues with the others? If not, then installation is correct.

No issues with others. Thank you!
