### ISSUE TITLE
Make the scalar field of all elements available to all processors in a quasi-static solver

### ISSUE THREAD

**Issue by maxincrease** [peridigm/peridigm#363]
Dear developers,

Could you suggest a way to make the scalar field of all elements (in my case, a damage field) available to all processors in a quasi-static solver? As I understand it, the method used for this in the explicit solver does not work for the quasi-static solver, does it?

Thank you very much in advance,
Max

**Comment by maxincrease** [comment]
The only option I found was to use the dataManager.scatterToGhosts() function for this purpose. 

This function seems to make all fields available to all processors, which might be more computationally expensive than doing it for a specific field, right?

Thanks,
Max

**Comment by djlittl** [comment]
[I thought I posted this comment a few days ago, but apparently I didn't click the green button.  Attempting to re-post now.]

This is actually a pretty nuanced question.  The short answer is that there is a function called synchronizeDataAfterPrecompute() that is called within ModelEvaluator::evalModel().  This function synchs data across processors.  You can see exactly what it does in the file Peridigm_Block.cpp.  This function acts on fields that were flagged as needing to be synched.  The vision is that the material models would know which fields need to be synched.  You can see this in Peridigm.cpp in this code:

std::vector<int> fieldIdsForSynchronizationAfterPrecompute = blockIt->getMaterialModel()->FieldIdsForSynchronizationAfterPrecompute();

dataManagerSynchronizer.setFieldIdsToSynchronizeAfterPrecompute(fieldIdsForSynchronizationAfterPrecompute);

For starters, you could just hack it and add the field_id of the field that you're interested in to this list.

But there are a few ways that things can go wrong.  For one, the synch function assumes that the entries for nodes that exist on multiple processors will be added, and the resulting sum will then be put into the data field on all processors.  This is what you want for things like force.  If a field is actually computed only on one processor and communicated to the other processors, then this works too, as long as the pre-synchronized value on the off-processors is zero.

A subtle way things can go wrong is the way these fields affect the nonlinear solver loop in the quasi-static solver.  Under normal conditions, the solver computes a tangent stiffness matrix at each step in the nonlinear solve and uses it to find the search direction.  If you include a variable like damage, this will obviously have a significant effect on the tangent matrix.  Trouble is, after you've moved to the next candidate configuration in the nonlinear solve process, the damage values will be different.  The whole idea of the tangent stiffness matrix is that it points you in the right direction to minimize the residual.  But this breaks down if the damage keeps changing at every iteration, and it's almost certain that the solver won't be able to minimize the residual, it will just keep jumping around, or worse it will jump to a nonsense configuration and the whole thing will error out.

And of course the quasi-static solver assumes static equilibrium.  So if the crack growth is unstable (most is), then the quasi-static solver is not appropriate.

I've given quasi-static solves with damage a lot of thought and would love to work on it.  Just need to find the time ...

**Comment by djlittl** [comment]
A follow up on your comment about dataManager.scatterToGhosts().  At first blush this seems like it would work.  Looking at the code, it acts slightly differently than the synchronize functions I mention above.  The scatterToGhosts() function takes the value on the process that "owns" the data and copies the value to all the processors that have ghosted copies of it.  It does not sum values, which may or may not be what you want.  Also, the scatterToGhosts() function is much less efficient that the synchronize functions because it ghosts all the data (!) and also I can see that it allocates temporary multivectors for use as scratch space.  That's pretty brutal.  But on the other hand, for quasi-statics there aren't that many steps and the global solves dominate anyway, so if scatterToGhosts() gives you want you want I think that's a great place to start.

I think the purpose of scatterToGhosts() is to synch everything everywhere before performing a rebalance.  That's why it's so exhaustive and the expense isn't a primary concern.  I.e., it wasn't designed to be called every step.

**Comment by maxincrease** [comment]
Thank you very much for such a comprehensive answer. I'm doing this to implement a known fatigue crack model (based on a cyclic bond strain) into Peridigm, at first just to perform simple benchmark tests, hopefully with stable crack propagation. Then in a viscoplastic case (surely, in the implicit solver) with the development of an appropriate analytical model for this.

I have one more very simple question. You probably remember if the implemented implicit (not a quasi-static) solver ignores the prescribed displacements? So it seems at first glance. Thank you very much.

**Comment by djlittl** [comment]
Prescribed displacement BC are taken into account, as in the tensile_test example problem.  If I recall correctly, the tangent stiffness matrix and the vectors are first set up with no regard for BC, and then there is a function that modifies the matrix and vectors to take BC into account.  I don’t have code in front of me, but you can see this in the executeQuasiStatics() function in Peridigm.cpp.  The function that modifies the linear system has a very descriptive name, so it should be clear.  It does something like zero out the rows and columns for degrees of freedom that have prescribed displacement BC and puts a 1 on the diagonal (I think the 1 is actually scaled to some other constant).  Then the corresponding value in the vector for the right hand side is set such that the solver returns the correct (prescribed) value for the displacement for the degree of freedom with applied displacement BC on it.  Hope that makes sense.

**Comment by maxincrease** [comment]
I'm really sorry that I bother you so often (I'm very limited on time and your anwers are very helpful). Probably you remember whether damage of bonds affects the computation of both quasi-static and implicit solvers (does a bond failure affect the computed field of displacements for these solvers)? Thank you very much in advance.
