### ISSUE TITLE
Peridigm installation in Ubuntu terminal

### ISSUE THREAD

**Issue by Bapun-kumar** [peridigm/peridigm#364]
Actually I am getting issue while installing trilinos and eventually peridigm installation is showing error.
These are the commands  am using step by step in Ubuntu terminal. Can anyone please tell me where is the mistake and where has been required to change.
#Build Trilinos
git clone https://github.com/trilinos/Trilinos.git trilinos
git checkout trilinos-release-13-0-0
mkdir trilinos/build
mv trilinos-debian-cmake.sh /trilinos/build/trilinos-debian-cmake.sh
cd trilinos/build
./trilinos-debian-cmake.sh
make && make install
cd ../..
rm -rf trilinos

apt-get -yq install openmpi-bin
apt-get -yq install openssh-server
apt-get -yq install libboost1.55
git clone https://github.com/peridigm/peridigm peridigm

mkdir peridigm/build

cd peridigm/build
cmake \
	-D CMAKE_BUILD_TYPE:STRING=Release \
	-D CMAKE_INSTALL_PREFIX:PATH=/home/rama/local/peridigm \
	-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -std=c++14 -pedantic -Wno-long-long -ftrapv -Wno-deprecated" \
	-D TRILINOS_DIR:PATH=/home/rama/local/trilinos \
	-D CMAKE_CXX_COMPILER:STRING="mpicxx" \
	-D USE_DAKOTA:BOOL=OFF \
	..; \
make && make install
cd ..
rm -rf peridigm

**Comment by oldninja** [comment]
What is the actual error? Can you show me where it happens?

**Comment by diehlpk** [comment]
@Bapun-kumar Yes, without the error message, it is nearly impossible to help you.
