### ISSUE TITLE
Symbol not found: Field_NS::FieldSpec::FieldSpec

### ISSUE THREAD

**Issue by VictorEijkhout** [peridigm/peridigm#366]
Error:
```
[ 58%] Linking CXX executable Peridigm
## really long link line elided
/opt/apps/gcc/13.2.0/bin/ld: io/pdneigh/libPdNeigh.so: undefined reference to `Field_NS::FieldSpec::FieldSpec(Field_ENUM::Type, Field_ENUM::Relation, Field_ENUM::Length, Field_ENUM::Temporal, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
```

And indeed I can not find that symbol anywhere in the build tree:

```
[staff peridigm:933] findsymbol -d /work2/00434/eijkhout/peridigm/build-git-stampede3-intel24-impi/ Field_NS::FieldSpec::FieldSpec
Found in /work2/00434/eijkhout/peridigm/build-git-stampede3-intel24-impi/src/io/pdneigh/CMakeFiles/PdNeigh.dir/OverlapDistributor.cxx.o:
                 U Field_NS::FieldSpec::FieldSpec(Field_ENUM::Type, Field_ENUM::Relation, Field_ENUM::Length, Field_ENUM::Temporal, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Found in /work2/00434/eijkhout/peridigm/build-git-stampede3-intel24-impi/src/io/pdneigh/libPdNeigh.so:
                 U Field_NS::FieldSpec::FieldSpec(Field_ENUM::Type, Field_ENUM::Relation, Field_ENUM::Length, Field_ENUM::Temporal, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
```

**Comment by VictorEijkhout** [comment]
?

**Comment by oldninja** [comment]
I haven't had this error in the past... 
Not sure if this is related, but I've always used older versions of GCC to compile: 
/usr/bin/gcc-4.8 -
  slave g++: /usr/bin/g++-4.8
  slave gcov: /usr/bin/gcov-4.8
  slave gfortran: /usr/bin/gfortran-4.8
/usr/bin/gcc-5 - priority 50
  slave g++: /usr/bin/g++-5
  slave gcov: /usr/bin/gcov-5
  slave gfortran: /usr/bin/gfortran-5

**Comment by VictorEijkhout** [comment]
I don't think the choice of compiler can make a difference regarding a missing symbol.

Any developers want to weigh in?

**Comment by oldninja** [comment]
I recall this comment by @djlittl --> https://github.com/peridigm/peridigm/issues/76#issuecomment-440746637 
Looks like the resolution was an earlier version of gcc/gfortran --> https://github.com/peridigm/peridigm/issues/76#issuecomment-441009085

**Comment by VictorEijkhout** [comment]
That is a totally different issue. Static assert vs missing symbol.

**Comment by VictorEijkhout** [comment]
I think this was caused by another problem and I didn't read far enough back. New ticket opened.
