### ISSUE TITLE
Coupling of Peridigm with FE structural solver (e.g. Albany)

### ISSUE THREAD

**Issue by maxincrease** [peridigm/peridigm#367]
Dear developers,

Could you tell me please the way for coupling of Peridigm with FE structural solver (e.g. Albany)? Are there any examples for this?

Thank you,
Maksim

**Comment by oldninja** [comment]
I haven't had a chance to work on this but I recall this: [Tag on Albany for Peridigm end of support](https://github.com/sandialabs/Albany/releases/tag/PERIDIGM_support_end)

**Comment by diehlpk** [comment]
```
This commit is the last one for which we guarantee
a working Peridigm, when Albany is compiled against commit

ec7ddad27cbfca383fb4c70f8beeba6193739853

in Trilinos.
```

You could try using the above Trilinos version and Albany from around this time.
