### ISSUE TITLE
contact problem

### ISSUE THREAD

**Issue by lihao194** [peridigm/peridigm#369]
Dear Developer
I'm a beginner at Peridigm.In my contact simulation with contact model: "Short Range Force", when block1 impacts block2 at a certain speed, the material points of block2 (Three rows of red material points in the pictureare) always kept in front of block1 at the same distance (this distance is bigger than the contact radius). This phenomenon continues throughout the simulation. My contact radius is set to 0.75 element size.
<img width="243" alt="2024-04-01 105611" src="https://github.com/peridigm/peridigm/assets/165614828/a9c40a48-165b-4380-93c3-cb1026522505">
Thanks

**Comment by oldninja** [comment]
Could you post your full yaml input file? If possible.

**Comment by lihao194** [comment]
> Could you post your full yaml input file? If possible.

thank you for the response.This is my yaml file.
[1.txt](https://github.com/peridigm/peridigm/files/14830281/1.txt)


And it's not just this time that this happens, it also happens in two-dimensional simulations,even though change Critical Stretch.

**Comment by oldninja** [comment]
I'm not entirely sure why that happens, but have you tried starting from different initial locations/conditions?

**Comment by lihao194** [comment]
> I'm not entirely sure why that happens, but have you tried starting from different initial locations/conditions?
thank you ,i will try again
