### ISSUE TITLE
Trouble Extracting Data with NetCDF

### ISSUE THREAD

**Issue by bdas123** [peridigm/peridigm#372]
Hello, my peridigm simulation is running smoothly. However, I am having trouble mapping the output list to the actual variables. 

Here are the Outputs from my simulation:

```
**** GET VARIABLE INFORMATION AND NAMES ****
Found 15 nodal variables.
	CoordinatesX    CoordinatesY    CoordinatesZ    ForceX          ForceY          
	ForceZ          DisplacementX   DisplacementY   DisplacementZ   VelocityX       
	VelocityY       VelocityZ       Force_DensityX  Force_DensityY  Force_DensityZ  

Found 22 element variables.
	Green_Lagrange_StrainXX  Green_Lagrange_StrainXY  Green_Lagrange_StrainXZ  
	Green_Lagrange_StrainYX  Green_Lagrange_StrainYY  Green_Lagrange_StrainYZ  
	Green_Lagrange_StrainZX  Green_Lagrange_StrainZY  Green_Lagrange_StrainZZ  
	PK2_StressXX             PK2_StressXY             PK2_StressXZ             
	PK2_StressYX             PK2_StressYY             PK2_StressYZ             
	PK2_StressZX             PK2_StressZY             PK2_StressZZ             
	Principal_StrainsX       Principal_StrainsY       Principal_StrainsZ       
	Volume    

```

Here are the variables that are found when I read the Exodus output using NetCDF:

`'info_records',
 'qa_records',
 'time_whole',
 'eb_status',
 'eb_prop1',
 'eb_names',
 'ns_status',
 'ns_prop1',
 'ns_names',
 'coordx',
 'coordy',
 'coordz',
 'coor_names',
 'connect1',
 'connect2',
 'connect3',
 'connect4',
 'node_ns1',
 'dist_fact_ns1',
 'node_ns2',
 'dist_fact_ns2',
 'node_ns3',
 'dist_fact_ns3',
 'vals_nod_var1',
 'vals_nod_var2',
 'vals_nod_var3',
 'vals_nod_var4',
 'vals_nod_var5',
 'vals_nod_var6',
 'vals_nod_var7',
 'vals_nod_var8',
 'vals_nod_var9',
 'vals_nod_var10',
 'vals_nod_var11',
 'vals_nod_var12',
 'vals_nod_var13',
 'vals_nod_var14',
 'vals_nod_var15',
 'name_nod_var',
 'name_elem_var',
 'vals_elem_var1eb1',
 'vals_elem_var2eb1',
 'vals_elem_var3eb1',
 'vals_elem_var4eb1',
 'vals_elem_var5eb1',
 'vals_elem_var6eb1',
 'vals_elem_var7eb1',
 'vals_elem_var8eb1',
 'vals_elem_var9eb1',
 'vals_elem_var10eb1',
 'vals_elem_var11eb1',
 'vals_elem_var12eb1',
 'vals_elem_var13eb1',
 'vals_elem_var14eb1',
 'vals_elem_var15eb1',
 'vals_elem_var16eb1',
 'vals_elem_var17eb1',
 'vals_elem_var18eb1',
 'vals_elem_var19eb1',
 'vals_elem_var20eb1',
 'vals_elem_var21eb1',
 'vals_elem_var22eb1',
 'vals_elem_var1eb2',
 'vals_elem_var2eb2',
 'vals_elem_var3eb2',
 'vals_elem_var4eb2',
 'vals_elem_var5eb2',
 'vals_elem_var6eb2',
 'vals_elem_var7eb2',
 'vals_elem_var8eb2',
 'vals_elem_var9eb2',
 'vals_elem_var10eb2',
 'vals_elem_var11eb2',
 'vals_elem_var12eb2',
 'vals_elem_var13eb2',
 'vals_elem_var14eb2',
 'vals_elem_var15eb2',
 'vals_elem_var16eb2',
 'vals_elem_var17eb2',
 'vals_elem_var18eb2',
 'vals_elem_var19eb2',
 'vals_elem_var20eb2',
 'vals_elem_var21eb2',
 'vals_elem_var22eb2',
 'vals_elem_var1eb3',
 'vals_elem_var2eb3',
 'vals_elem_var3eb3',
 'vals_elem_var4eb3',
 'vals_elem_var5eb3',
 'vals_elem_var6eb3',
 'vals_elem_var7eb3',
 'vals_elem_var8eb3',
 'vals_elem_var9eb3',
 'vals_elem_var10eb3',
 'vals_elem_var11eb3',
 'vals_elem_var12eb3',
 'vals_elem_var13eb3',
 'vals_elem_var14eb3',
 'vals_elem_var15eb3',
 'vals_elem_var16eb3',
 'vals_elem_var17eb3',
 'vals_elem_var18eb3',
 'vals_elem_var19eb3',
 'vals_elem_var20eb3',
 'vals_elem_var21eb3',
 'vals_elem_var22eb3',
 'vals_elem_var1eb4',
 'vals_elem_var2eb4',
 'vals_elem_var3eb4',
 'vals_elem_var4eb4',
 'vals_elem_var5eb4',
 'vals_elem_var6eb4',
 'vals_elem_var7eb4',
 'vals_elem_var8eb4',
 'vals_elem_var9eb4',
 'vals_elem_var10eb4',
 'vals_elem_var11eb4',
 'vals_elem_var12eb4',
 'vals_elem_var13eb4',
 'vals_elem_var14eb4',
 'vals_elem_var15eb4',
 'vals_elem_var16eb4',
 'vals_elem_var17eb4',
 'vals_elem_var18eb4',
 'vals_elem_var19eb4',
 'vals_elem_var20eb4',
 'vals_elem_var21eb4',
 'vals_elem_var22eb4',
 'elem_var_tab']`

I have a hunch that, for example, Green_Lagrange_strainXX corresponds to vals_elem_var1eb1. However, I'm not sure why there are four different suffixes to vals_elem_var1 (eb1, eb2, eb3, and eb4).

**Comment by oldninja** [comment]
Are you using an exodus mesh? Could it be a placeholder for the integration points?

**Comment by djlittl** [comment]
I think this is a result of using a netcdf reader, or MATLAB.  The mechanism in the exodus file format that maps variable names to the data arrays is an exodus file format feature, not a netcdf file format feature.  @johntfoster do you recall how to get around this?  Worst case, you have to manually map the variables.  Or you might try an alternative to your netcdf reader, like exodus.py or ParaView.

**Comment by bdas123** [comment]
Let's say my Peridynamics code produces a file called 2.45e-5.e, here is the Python code I used to extract the values. 

```
import netCDF4
import numpy as np

# Open the NetCDF file
file_path = '2.45e-5.e'
nc = netCDF4.Dataset(file_path, 'r')

# Extract the necessary variables
volume = nc.variables['vals_nod_var1'][:]
force_density_x = nc.variables['vals_nod_var10'][:]
force_density_y = nc.variables['vals_nod_var11'][:]
force_density_z = nc.variables['vals_nod_var12'][:]

x_coords = nc.variables['coordx'][:]
y_coords = nc.variables['coordy'][:]
z_coords = nc.variables['coordz'][:]

```
As you can see, the only variables that are easy to extract are "coordx", "coordy", and "coordz".

**Comment by bdas123** [comment]
Unfortunately, Github will not let me share the Exodus file

**Comment by bdas123** [comment]
@djlittl, I took your advice and tried to download exodus.py with the following command. 

`pip install exodus`

Here is the error I am getting: 

```
Collecting exodus
  Using cached exodus-1.0.8-py3-none-any.whl
Collecting blist (from exodus)
  Using cached blist-1.3.6.tar.gz (122 kB)
  Preparing metadata (setup.py) ... done
Collecting import-file (from exodus)
  Using cached import_file-1.11-py3-none-any.whl
Building wheels for collected packages: blist
  Building wheel for blist (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.1-arm64-cpython-311
      creating build/lib.macosx-11.1-arm64-cpython-311/blist
      copying blist/_btuple.py -> build/lib.macosx-11.1-arm64-cpython-311/blist
      copying blist/_sortedlist.py -> build/lib.macosx-11.1-arm64-cpython-311/blist
      copying blist/__init__.py -> build/lib.macosx-11.1-arm64-cpython-311/blist
      copying blist/_sorteddict.py -> build/lib.macosx-11.1-arm64-cpython-311/blist
      running build_ext
      building 'blist._blist' extension
      creating build/temp.macosx-11.1-arm64-cpython-311
      creating build/temp.macosx-11.1-arm64-cpython-311/blist
      clang -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/barundas/anaconda3/include -arch arm64 -fPIC -O2 -isystem /Users/barundas/anaconda3/include -arch arm64 -DBLIST_FLOAT_RADIX_SORT=1 -I/Users/barundas/anaconda3/include/python3.11 -c blist/_blist.c -o build/temp.macosx-11.1-arm64-cpython-311/blist/_blist.o
      blist/_blist.c:4583:37: error: implicit declaration of function '_PyObject_GC_IS_TRACKED' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                      if (leafs_n > 1 && !_PyObject_GC_IS_TRACKED(leafs[i]))
blist/_blist.c:5786:13: error: implicit declaration of function '_PyObject_GC_IS_TRACKED' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
              if (_PyObject_GC_IS_TRACKED(self))
                  ^
      blist/_blist.c:5789:9: warning: 'UsingDeprecatedTrashcanMacro' is deprecated [-Wdeprecated-declarations]
              Py_TRASHCAN_SAFE_BEGIN(self)
              ^
      /Users/barundas/anaconda3/include/python3.11/cpython/object.h:507:9: note: expanded from macro 'Py_TRASHCAN_SAFE_BEGIN'
              UsingDeprecatedTrashcanMacro cond=1; \
              ^
      /Users/barundas/anaconda3/include/python3.11/cpython/object.h:504:1: note: 'UsingDeprecatedTrashcanMacro' has been explicitly marked deprecated here
      Py_DEPRECATED(3.11) typedef int UsingDeprecatedTrashcanMacro;
      ^
      /Users/barundas/anaconda3/include/python3.11/pyport.h:336:54: note: expanded from macro 'Py_DEPRECATED'
      #define Py_DEPRECATED(VERSION_UNUSED) __attribute__((__deprecated__))
                                                           ^
      blist/_blist.c:6591:25: error: expression is not assignable
              Py_TYPE(&saved) = &PyRootBList_Type;
              ~~~~~~~~~~~~~~~ ^
      blist/_blist.c:6592:27: error: expression is not assignable
              Py_REFCNT(&saved) = 1;
              ~~~~~~~~~~~~~~~~~ ^
      blist/_blist.c:7378:32: error: expression is not assignable
              Py_TYPE(&PyBList_Type) = &PyType_Type;
              ~~~~~~~~~~~~~~~~~~~~~~ ^
      blist/_blist.c:7379:36: error: expression is not assignable
              Py_TYPE(&PyRootBList_Type) = &PyType_Type;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
      blist/_blist.c:7380:36: error: expression is not assignable
              Py_TYPE(&PyBListIter_Type) = &PyType_Type;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
      blist/_blist.c:7381:43: error: expression is not assignable
              Py_TYPE(&PyBListReverseIter_Type) = &PyType_Type;
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
      1 warning and 8 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for blist
  Running setup.py clean for blist
Failed to build blist
ERROR: Could not build wheels for blist, which is required to install pyproject.toml-based projects
Note: you may need to restart the kernel to use updated packages.

```

One interesting thing to note is that according to the [Sandia link](https://sandialabs.github.io/seacas-docs/exodus.html), there's a version 1.21.2.

However, according to the [Python library link](https://pypi.org/project/exodus/), only version 1.0.8 is available.

**Comment by bdas123** [comment]
I found a workaround to the problem, which is to use the meshio library. 

Here is some sample code. 


```
import meshio

import numpy as np

mesh = meshio.read('2.45e-5.e')

print(mesh)
```


This gives the output

```
<meshio mesh object>
  Number of points: 10336
  Number of cells:
    vertex: 544
    vertex: 7616
    vertex: 1632
    vertex: 544
  Point sets: NODELIST_1, NODELIST_2, NODELIST_3
  Point data: Coordinates, Force, Displacement, Velocity, Force_Density
  Cell data: Green_Lagrange_StrainXX, Green_Lagrange_StrainXY, Green_Lagrange_StrainXZ, Green_Lagrange_StrainYX, Green_Lagrange_StrainYY, Green_Lagrange_StrainYZ, Green_Lagrange_StrainZX, Green_Lagrange_StrainZY, Green_Lagrange_StrainZZ, PK2_StressXX, PK2_StressXY, PK2_StressXZ, PK2_StressYX, PK2_StressYY, PK2_StressYZ, PK2_StressZX, PK2_StressZY, PK2_StressZZ, Principal_StrainsX, Principal_StrainsY, Principal_StrainsZ, Volume

```

It's much easier to access the variables using meshio. 

For example, 

`e_xx = mesh.cell_data["Green_Lagrange_StrainXX"]`

**Comment by bdas123** [comment]
Please let me know if you have any questions. 

Thanks for the help, @djlittl and @oldninja
