### ISSUE TITLE
Erro running peridigm

### ISSUE THREAD

**Issue by MelissaCastellan** [peridigm/peridigm#375]
I run a peridigm example using multiphysics material and problems as follows：

The sublist ANONYMOUS->"Blocks" does not exist!

Throw number = 1

Wallclock Time (Seconds) :
Total 0.017

So i don't what is the "ANONYMOUS" or where to find it.
Another problem is that i run the example in /test ,i copy the file to another file.After runing it ,i can't find the output file,such as ***.e I don't konw why!

**Comment by oldninja** [comment]
Can you share your input file?

**Comment by MelissaCastellan** [comment]
I'm trying to run disk_impact example.

Il giorno lun 15 lug 2024 alle ore 23:26 oldninja ***@***.***>
ha scritto:

**Comment by oldninja** [comment]
Have you tried running it without changing the material?
Have you been able to look into the multiphysics example below? https://github.com/peridigm/peridigm/blob/82c6ad8f8152aaa3c8a2b4e7b31f82b8e1c6f28c/test/regression/Multiphysics_QS_3x2x2/Multiphysics_QS_3x2x2.xml#L24 

I cannot find any reference to "ANONYMOUS" in the source files.

**Comment by MelissaCastellan** [comment]
I didn't modify the example folder file, I just tried to run the program. Can I ask you this example how it would work?

**Comment by oldninja** [comment]
Then that means your installation is not correct. Are you able to run any tests?

**Comment by MelissaCastellan** [comment]
Looking back at the program it fails many tests if I run the make test command. I'll try to redo the installation. However, I have a question since I installed virtual box on Windows and following the instructions in the Peridigm Installation Guide pdf I installed opensuse-Leap-42.1, is it correct or should I change it?

**Comment by oldninja** [comment]
I am not sure about this document, Peridigm Installation Guide pdf, maybe include a link to it? 
I've only installed it on Ubuntu distros, so you may need different packages on opensuse - but not sure.

**Comment by MelissaCastellan** [comment]
the document in this https://core.ac.uk/download/pdf/211564148.pdf

**Comment by oldninja** [comment]
That's a good guide. Try to follow it step by step and double check at the end of each build (trilinos, hdf5, netcdf, etc). You don't need boost for Peridigm 1.5 dev version. It takes a few attempts to fully install everything properly.

**Comment by oldninja** [comment]
The guide is helpful. Follow it meticulously, step by step, and verify your progress after completing each build (Trilinos, HDF5, NetCDF, etc.). The Peridigm 1.5 development version does not require Boost. Installing everything correctly may require several attempts.
