### ISSUE TITLE
The failure surface

### ISSUE THREAD

**Issue by mashhadi18** [peridigm/peridigm#39]
Dr. Littlewood,
Have you implemented the damage growth based on **the failure surface** in the peridigm? 

A. Askari, Y. Azdoud, F. Han, G. Lubineau, and S. Silling, “Peridynamics for analysis of failure in advanced composite materials,” Numerical Modelling of Failure in Advanced Composite Materials, no. AUGUST, Elsevier, pp. 331-350, 2015.

D. J. Littlewood, S. A. Silling, J. A. Mitchell, P. D. Seleson, S. D. Bond, M. L. Parks, D. Z. Turner, D. J. Burnett, J. Ostien, and M. Gunzburger, “Strong local-nonlocal coupling for integrated fracture modeling,” Sandia Report SAND2015-7998, Sandia National Laboratories, vol. 3, 2015.

**Comment by djlittl** [comment]
No, that model is not currently implemented in Peridigm.

Dave
