### ISSUE TITLE
Gaussian Influence Function

### ISSUE THREAD

**Issue by raedma** [peridigm/peridigm#42]
A short question concerning the influence function: in `Peridigm_InfluenceFunction.hpp`, the gaussian influence distribution is given as

    static double gaussian(double zeta, double horizon){
      double h2=horizon*horizon;
      double xi2=zeta*zeta;
      return exp(-xi2/h2);
    }

which is approx. 0.368 at zeta/horizon=1. Is this really the desired value and if so, where does it come from? For another implementation I found 

    static double gaussian(double zeta, double horizon){
      double h2=horizon*horizon*0.4*0.4;
      double xi2=zeta*zeta;
      return exp(-xi2/h2);
    }

with a value of approx. 0 at zeta/horizon=1 from:

Pablo Seleson “Improved one-point quadrature algorithms for two-dimensional peridynamic models based on analytical calculations”. In: Computer Methods in Applied Mechanics and Engineering 282.Supplement C (2014), pp. 184–217. ISSN : 0045-7825. DOI : 10.1016/j.cma.2014.06.016. URL: http://www.sciencedirect.com/science/article/pii/S0045782514002023.

Where does the difference for both gaussian influence functions come from?

**Comment by djlittl** [comment]
Martin,

Thanks for pointing this out.  The second version, which drops off to approximately zero when the bond length is equal to the horizon, certainly makes more sense to me.  I suppose either version is “valid” in the sense that one can assign the influence function to be almost anything.

It looks like the first version appears in Tupek, Rimoli, and Radovitzky, CMAME 2013, and in Kilic and Madenci, Int J Fract 2009.  It’s likely that the specific code in Peridigm was used in the research for the PALS model, which was published in Mitchell, Silling, and Littlewood, JoMMS 2015.

I altered the Peridigm source code in my local repo to the second version, and all the tests still pass (which suggests a need for more tests).  If there are no objections, I’m happy to push the changes to GitHub.

If anyone has a reason to keep version 1 around, please let me know.

Note that you can use the expression parser to input an arbitrary influence function in the input deck.  So you can get either version of the Gaussian that way.  But the built-in ones are faster, and I vote for the one that drops off to close to zero.

Dave

**Comment by djlittl** [comment]
Update:  I just pushed the changes to the Peridigm repo.  The Gaussian is now h2=horizon*horizon*0.4*0.4.

Dave

From: "Littlewood, David John" <djlittl@sandia.gov>
Date: Tuesday, November 14, 2017 at 5:07 PM
To: peridigm/peridigm <reply@reply.github.com>, peridigm/peridigm <peridigm@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [EXTERNAL] [peridigm/peridigm] Gaussian Influence Function (#42)

Martin,

Thanks for pointing this out.  The second version, which drops off to approximately zero when the bond length is equal to the horizon, certainly makes more sense to me.  I suppose either version is “valid” in the sense that one can assign the influence function to be almost anything.

It looks like the first version appears in Tupek, Rimoli, and Radovitzky, CMAME 2013, and in Kilic and Madenci, Int J Fract 2009.  It’s likely that the specific code in Peridigm was used in the research for the PALS model, which was published in Mitchell, Silling, and Littlewood, JoMMS 2015.

I altered the Peridigm source code in my local repo to the second version, and all the tests still pass (which suggests a need for more tests).  If there are no objections, I’m happy to push the changes to GitHub.

If anyone has a reason to keep version 1 around, please let me know.

Note that you can use the expression parser to input an arbitrary influence function in the input deck.  So you can get either version of the Gaussian that way.  But the built-in ones are faster, and I vote for the one that drops off to close to zero.

Dave
