### ISSUE TITLE
C++ standard includes need fixing

### ISSUE THREAD

**Issue by ibaned** [peridigm/peridigm#43]
@djlittl Trilinos recently removed an unnecessary C++ standard library include from a Teuchos header, and this has been exposing missing includes in many codes. It looks like, at a minimum `Peridigm_ContactManager.hpp` should include `<set>`. Here is the CDash report I'm basing this on:

http://my.cdash.org/viewBuildError.php?buildid=1323956

**Comment by ibaned** [comment]
The Albany team is still seeing missing includes, in particular it looks like `src/compute/Peridigm_Compute_Bond_Visualization.cpp` and `src/core/Peridigm.cpp` both need to include `<fstream>`, also `src/core/Peridigm_InterfaceData.cpp`, `src/io/discretization/Peridigm_Discretization.cpp`, `src/io/discretization/Peridigm_AlbanyDiscretization.cpp`, and `src/io/discretization/Peridigm_ExodusDiscretization.cpp` still need to include `<set>`.

http://my.cdash.org/viewBuildError.php?buildid=1328722

@mperego can you confirm that the dashboard I just linked to is building the latest Peridigm master branch?

**Comment by mperego** [comment]
Hi Dan, that's correct. I sent a patch for Peridigm to @djlittl  during the the Thanksgiving holiday.

**Comment by mperego** [comment]
@jtostie @djlittl Here is an updated patch. It may not be a minimal set of required includes.
[patch.txt](https://github.com/peridigm/peridigm/files/1506686/patch.txt)

**Comment by djlittl** [comment]
Just pushed the changes from mperego.

**Comment by ibaned** [comment]
Thanks @djlittl !

**Comment by mperego** [comment]
Thanks @djlittl ! My nightly tests run fine!
