### ISSUE TITLE
Peridigm make -j 8

### ISSUE THREAD

**Issue by bahadorimr** [peridigm/peridigm#44]
Hello, 

I get the following error when I do "make -j 8" for Peridigm. I have installed boost 1.66.0 already. Thanks for your help.  

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
/Users/mb3544/scratch/Peridigm/src/io/utilities/MemoryInclude.h:66:2: warning: "Could not find compiler-supplied memory.hpp,

      substituting boost/tr1/memory.hpp" [-W#warnings]

#warning "Could not find compiler-supplied memory.hpp, substituting boost/tr1/memory.hpp"

 ^

/Users/mb3544/scratch/Peridigm/src/io/utilities/MemoryInclude.h:69:10: fatal error: 'boost/tr1/memory.hpp' file not found

#include <boost/tr1/memory.hpp> 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by djlittl** [comment]
What compiler are you using?

If you look at MemoryInclude.h, you’ll see what is happening.  The build system is trying to find memory.hpp.  MemoryInclude.h has hard-coded locations for gcc and ibm compilers.  For other compilers, it tries to use boots/tr1/memory.hpp.  I suspect that for newer versions of boost, the file memory.hpp has been moved to a different location.  Or perhaps it’s been removed completely under the assumption that you’re using a relatively recent compiler that has memory.hpp.  Regardless, you should be able to modify MemoryInclude.h to point to the correct location of memory.hpp on your system.

**Comment by bahadorimr** [comment]
Dear David,

I greatly appreciate your response. 

I also think there should be some issues with the new version of boost. 

I am using gcc compiler. I used brew to install boost on my mac. 

I modified my MemoryInclude.h by adding something like:

#include <usr/local/Cellar/boost/1.66.0/include/boost/config/no_tr1/memory.hpp>

But it still does not work.

**Comment by djlittl** [comment]
I think you are missing a slash in front of “usr” in your path.

**Comment by bahadorimr** [comment]
Hi,

Thanks. I added / but still does not work. I think the problem is they have completely removed tr1 in the new version of boost. I need to learn how to install and build the old version of boost.
