### ISSUE TITLE
Correspondence Material

### ISSUE THREAD

**Issue by sgsikuga** [peridigm/peridigm#45]
Dear all,
I want to use the elastic-plastic model and the elastic-plastic model with linear hardening. I set up a tensile test for a simple cuboid. It has 1400 points and the units I use are mm, ton, Newton. The body is meshed regularly and the distance between the nodes is 0.1. The cuboid has a length of 1.4 and width and height are 1.0. It is divided into three blocks. The outer blocks pull respectively contrary in x-direction and are as thick as the horizon to ensure proper boundary conditions. The node sets are the same as the blocks. The following is my input for the materials:

> <ParameterList name="Materials">
    <ParameterList name="Workpiece Material 1">
      <Parameter name="Material Model" type="string" value="Isotropic Hardening Correspondence"/>
      <Parameter name="Density" type="double" value="2.7e-9"/>
      <Parameter name="Bulk Modulus" type="double" value="65.167e3"/>
      <Parameter name="Shear Modulus" type="double" value="30.077e3"/>
      <Parameter name="Yield Stress" type="double" value="100.0"/>
      <Parameter name="Hourglass Coefficient" type="double" value="0.0"/>
      <Parameter name="Hardening Modulus" type="double" value="1.0"/>
      <Parameter name="Disable Plasticity" type="bool" value="False"/>
      <Parameter name="Apply Shear Correction Factor" type="bool" value="True"/>
      <Parameter name="Apply Automatic Differentiation Jacobian" type="bool" value="True"/>
    </ParameterList>
    <ParameterList name="Workpiece Material 2">
      <Parameter name="Material Model" type="string" value="Elastic Plastic Hardening"/>
      <Parameter name="Density" type="double" value="2.7e-9"/>
      <Parameter name="Bulk Modulus" type="double" value="65.167e3"/>
      <Parameter name="Shear Modulus" type="double" value="30.077e3"/>
      <Parameter name="Yield Stress" type="double" value="100.0"/>
      <Parameter name="Hardening Modulus" type="double" value="1.0"/>
    </ParameterList>
    <ParameterList name="Workpiece Material 3">
      <Parameter name="Material Model" type="string" value="Elastic Plastic Correspondence"/>
      <Parameter name="Density" type="double" value="2.7e-9"/>
      <Parameter name="Bulk Modulus" type="double" value="65.167e3"/>
      <Parameter name="Shear Modulus" type="double" value="30.077e3"/>
      <Parameter name="Yield Stress" type="double" value="100.0"/>
      <Parameter name="Hourglass Coefficient" type="double" value="0.0"/>
    </ParameterList>
    <ParameterList name="Workpiece Material 4">
      <Parameter name="Material Model" type="string" value="Elastic Plastic"/>
      <Parameter name="Density" type="double" value="2.7e-9"/>
      <Parameter name="Bulk Modulus" type="double" value="65.167e3"/>
      <Parameter name="Shear Modulus" type="double" value="30.077e3"/>
      <Parameter name="Yield Stress" type="double" value="100.0"/>
    </ParameterList>
  </ParameterList>

These are the horizons and boundary conditions:

>   <ParameterList name="Blocks">
    <ParameterList name="Workpiece Support Block">
      <Parameter name="Block Names" type="string" value="block_1"/>
      <Parameter name="Material" type="string" value="Workpiece Material 1"/>
      <Parameter name="Horizon" type="double" value="0.301"/>
    </ParameterList>
    <ParameterList name="Workpiece Block">
      <Parameter name="Block Names" type="string" value="block_2"/>
      <Parameter name="Material" type="string" value="Workpiece Material 1"/>
      <Parameter name="Horizon" type="double" value="0.301"/>
    </ParameterList>
    <ParameterList name="Tool Block">
      <Parameter name="Block Names" type="string" value="block_3"/>
      <Parameter name="Material" type="string" value="Workpiece Material 1"/>
      <Parameter name="Horizon" type="double" value="0.301"/>
    </ParameterList>
  </ParameterList>

>   <ParameterList name="Boundary Conditions">
        <ParameterList name="Workpiece Support 1 In X">
          <Parameter name="Type" type="string" value="Prescribed Displacement"/>
          <Parameter name="Node Set" type="string" value="nodelist_1"/>
          <Parameter name="Coordinate" type="string" value="x"/>
          <Parameter name="Value" type="string" value="-100.0*t"/>
        </ParameterList>
        <ParameterList name="Workpiece Support 2 In X">
          <Parameter name="Type" type="string" value="Prescribed Displacement"/>
          <Parameter name="Node Set" type="string" value="nodelist_3"/>
          <Parameter name="Coordinate" type="string" value="x"/>
          <Parameter name="Value" type="string" value="100.0*t"/>
        </ParameterList>
  </ParameterList>

By looking at the below prescribed time period, I should get a displacement of 0.3 in each direction, which should be a strain of approximately 43%.

>   <ParameterList name="Solver">
        <Parameter name="Verbose" type="bool" value="false"/>
        <Parameter name="Initial Time" type="double" value="0.0"/>
        <Parameter name="Final Time" type="double" value="0.003"/>
        <ParameterList name="Verlet">
          <Parameter name="Safety Factor" type="double" value="0.8"/>
        </ParameterList>
  </ParameterList>

Furthermore, I compute the forces and stress (only for the correspondence material) for my evaluation like this:

>   <ParameterList name="Compute Class Parameters">
     <ParameterList name="F_Res WP Sup 1">
       <Parameter name="Compute Class" type="string" value="Block_Data"/>
       <Parameter name="Calculation Type" type="string" value="Sum"/>
       <Parameter name="Block" type="string" value="block_1"/>
       <Parameter name="Variable" type="string" value="Force"/>
       <Parameter name="Output Label" type="string" value="F_WP_Sup_1"/>
     </ParameterList>
      <ParameterList name="F_Res WP Mid">
       <Parameter name="Compute Class" type="string" value="Block_Data"/>
       <Parameter name="Calculation Type" type="string" value="Maximum"/>
       <Parameter name="Block" type="string" value="block_2"/>
       <Parameter name="Variable" type="string" value="Von_Mises_Stress"/>
       <Parameter name="Output Label" type="string" value="Stress_VM_Max"/>
     </ParameterList>
      <ParameterList name="F_Res WP Sup 2">
       <Parameter name="Compute Class" type="string" value="Block_Data"/>
       <Parameter name="Calculation Type" type="string" value="Sum"/>
       <Parameter name="Block" type="string" value="block_3"/>
       <Parameter name="Variable" type="string" value="Force"/>
       <Parameter name="Output Label" type="string" value="F_WP_Sup_2"/>
     </ParameterList>
  </ParameterList>

The results for the correspondence material are as expected but I do not understand what happens for the normal state-based peridynamics formulation. 

I set the Hardening Modulus to 1 in order to get a nearly ideal plasticity. This is what I get for the "Isotropic Hardening Correspondence" but not for "Elastic Plastic Hardening". It looks like pure elastic behavior. 

The behavior of the "Elastic Plastic" compared to the "Elastic Plastic Correspondence" is also not evident for me. The correspondence material gives the exact results for the stresses and therefore I assume the sum of forces in block 1 to be true as well. The force in the same block (I only changed to the state-based peridynamics formulation) has a different absolute value. Furthermore the trend of the force falls at first an then rises again. I think it should only fall until it consolidates at a certain value regarding ideal plasticity.

Thanks in advance!

![el_pl_correspondence_fx_left](https://user-images.githubusercontent.com/34741740/34257864-ec1f3750-e65b-11e7-9b84-45df45e7118a.png)
Fig. 1: Elastic-plastic correspondence material Fx-time diagram

![el_pl_fx_left](https://user-images.githubusercontent.com/34741740/34257866-ec5b85a2-e65b-11e7-85df-461d3e1d06fc.png)
Fig. 2: Elastic-plastic Fx-time diagram

![el_pl_correspondence_stress_strain](https://user-images.githubusercontent.com/34741740/34257865-ec3c6fe6-e65b-11e7-954e-cddc5348cedb.png)
Fig. 3: Elastic-plastic correspondence material stress strain diagram

![el_pl_hardening_fx_left](https://user-images.githubusercontent.com/34741740/34257863-ebfd10ee-e65b-11e7-8e17-bd14a43c4a8d.png)
Fig. 4: Elastic-plastic hardening Fx-time diagram

![el_pl_hardening_correspondence_fx_left](https://user-images.githubusercontent.com/34741740/34257867-ec78db0c-e65b-11e7-8b86-d7a260d9e682.png)
Fig. 5: Elastic-plastic hardening correspondence material Fx-time diagram

![el_pl_hardening_correspondence_stress_strain](https://user-images.githubusercontent.com/34741740/34257869-ecaa9174-e65b-11e7-8179-360055e3ab1a.png)
Fig. 6: Elastic-plastic hardening correspondence material stress-strain diagram

**Comment by 752096822** [comment]
Wow,I found them!Thankyou very much!  May I ask you some other questions?  I have read some of the files, the .g files mean the model that you build, the .e files mean the results,and  .xml files mean the input files. Ok, what's the meaning of the .py files, .txt files ,.comp files , .blot files , .jou files and so on? I am sorry I can't speak English very well.I don't know whether your understand me.What's the relationship between these different format files?   When I write the input files by myself, is it enough to only write the .xml files?

**Comment by djlittl** [comment]
The files that you need to run a Peridigm simulation are:


1)       A discretization (mesh).  This can be either a genesis/exodus file (.g), or a text file (.txt).  There is also an internal mesh generator in Peridigm for simple geometries, but it’s really only used for testing and can’t be used for a realist engineering geometry.



2)       An input deck.  There are three file formats currently supported by Peridigm.  Xml is the oldest format, it works just fine but is not easy for human eyes to read.  The .peridigm format was introduced in an attempt to create a more human-readable format.  And most recently, Peridigm started supporting .yaml format.  The actual commands in the input deck are the same in all three cases, only the syntax is different.  You can use whichever format you want.

The output from Peridigm is an exodus file (.e), and occasionally a history (.h) file, which is an exodus file with only global data.

The other files you mention are not used by Peridigm.  They are either for pre-processing or post-processing.  Here is a brief description of each:

py   Python scripts, mainly used for post-processing.  Sometimes used in pre-processing for creating text file meshes.

txt  Text files.  Used for meshes (text file option) and for many other things as well.  Should be human readable, so just look in the file to see what it is.

comp   These are “comparison” files, which are used by the test system.  The test system uses a program called exodiff to compare an exodus output file with a “gold” file that contains the expected results.  The .comp file specifies the variables that are to be compared and the acceptable tolerances for each.

blot  Blot file, used for post-processing with the blot program.  Blot is a utility that can extract specified quantities from an exodus file, so it can be useful for obtaining data for plotting, etc.  Using a python script with exodus.py is probably easier for most users.

jou   Journal files, which list the geometry and meshing commands for the Cubit mesh generator.  Cubit is used extensively at Sandia, but unfortunately is not open source.

Hope this helps,
Dave

**Comment by sgsikuga** [comment]
Dear Dave,
could you please answer to my question as well? I think your answer belongs to another issue.

Best regards,
Simon
