### ISSUE TITLE
How to use Peridigm

### ISSUE THREAD

**Issue by 752096822** [peridigm/peridigm#46]
Thanks for your help,I have installed the Peridigm and I can run the examples successfully,but there is a problem that I don't know how to write input files by myself.For instance,I don't know what kind of rules I should follow when I write the input.xml.

**Comment by sgsikuga** [comment]
Hello,
you can have a look at the small examples in the test/regression and test/verification folders. There, the structure of input files and the accessible variables are shown. 
I think that you need to prescribe at least the Discretization, Materials, Blocks, Boundary Conditions, Solver and Output parameter lists to run your own example.

**Comment by 752096822** [comment]
Wow,I found them!Thankyou very much!  May I ask you some other questions?  I have read some of the files, the .g files mean the model that you build, the .e files mean the results,and  .xml files mean the input files. Ok, what's the meaning of the .py files, .txt files ,.comp files , .blot files , .jou files and so on? I am sorry I can't speak English very well.
I don't know whether your understand me.What's the relationship between these different format files?   When I write the input files by myself, is it enough to only write the .xml files?

**Comment by Coooooco** [comment]
Dear author,
Hi！Could you please tell  me how to run the examples ？Thanks a lot.
