### ISSUE TITLE
Can I use force boundary conditions in the Peridigm?

### ISSUE THREAD

**Issue by 752096822** [peridigm/peridigm#47]
I have study some exmaples,but I found that almost all the boundary conditions are the initial velocity or the presccribed displacement boundary conditions.I want to use the force or the stress boundary conditions, how can I do it?

**Comment by djlittl** [comment]
I grepped for “Body Force” in the test directory and found the following examples that apply a body force density:

regression/Body_Force/Body_Force_Explicit.xml
regression/Body_Force/Body_Force_QS.xml
regression/Body_Force/Body_Force_QS_NOX.xml
regression/CentrifugalLoad/CentrifugalLoad.xml

There is no direct way to apply a stress in peridynamics.  Boundary conditions in peridynamics must be applied over a nonlocal boundary region, typically on a volume that reaches into the depth of the body a distance of two times the horizon.

The only way that I’m aware of to approximate a stress boundary condition is to conjure up a body force and apply it over a volumetric boundary region, such that the action of the body force is roughly the same as the desired stress boundary condition.

**Comment by 752096822** [comment]
Wow,David,thank you very much,how do I to understand the meaning of "body force"? In the Peridigm,we have already taken the density,does the "body force" belong to the force belong to extra force or inherent gravity?

**Comment by 752096822** [comment]
Wow,David,thank you very much,how do I to understand the meaning of "body force"? In the Peridigm,we have already taken the density,does the "body force" belong to the extra force or the inherent gravity?

**Comment by 752096822** [comment]
Hello，David！I want to know is the Peridigm based on Bond-Based Peridynamics，Ordinary State-Based Peridynamics or Nonordinary State-Based Peridynamics？ Thankyou very much！

**Comment by djlittl** [comment]
Peridigm was written for state-based peridynamics.  But bond-based models are just a special case of state-based, so there is no reason why you couldn’t implement a bond-based model.

There is currently infrastructure in place for both ordinary and non-ordinary state-based models.
