### ISSUE TITLE
Rigid body

### ISSUE THREAD

**Issue by sgsikuga** [peridigm/peridigm#48]
Dear all,
is it possible to define a rigid body in Peridigm, which is able to interact with a body discretized by peridynamics as, for instance, shown in "Peridynamic modeling of the Kalthoff--Winkler experiment", S.A. Silling, 2001?
Thanks in advance!

**Comment by johntfoster** [comment]
There is currently no rigid material in Peridigm.  However, one approach
that can get you a "near rigid-body" and requires no changes to the code
would be to use a very stiff material (high elastic modulus) without a
damage model.  Alternatively, it should be quite easy to implement a rigid
constitutive model.
