### ISSUE TITLE
Peridigm in Debug mode

### ISSUE THREAD

**Issue by sgsikuga** [peridigm/peridigm#51]
Dear all,

there is the option to compile Peridigm in debug mode but many fields and quantities are not available in the debugger since they are "optimized out". Is there a way to get all information of Peridigm in the debugger?

Best regards,
Simon

**Comment by djlittl** [comment]
Can you be more specific about what quantities you are not able to see?

Generally speaking, Peridigm is like any other C++ code, and everything should be accessible in a debugger.  If you are trying to see things that live within a Trilinos library, then you will need to compile Trilinos in debug mode as well (and perhaps the libraries that Trilinos itself depends on, but I wouldn't bother with this at first).

**Comment by sgsikuga** [comment]
I think the problem is that I haven't compiled Trilinos in debug mode. If I set a breakpoint and and run Peridigm the variable names are available but the content of most of the fields, for instance, deformationGradient or defGrad is not available. It says <optimized out> or shows a system address (which refers somewhere to the Trilinos libraries, I think). But local variables within a function or its arguments are fully available.

Thanks for your help!
