### ISSUE TITLE
model for fatigue

### ISSUE THREAD

**Issue by mentianlong** [peridigm/peridigm#52]
Could you release a example for fatigue？

**Comment by MDBrothers** [comment]
Research on fatique, with Peridigm, was done at Advanced Cooling
Technologies in PA.

**Comment by mentianlong** [comment]
How can I get a example for fatigue？

**Comment by MDBrothers** [comment]
I would get into contact with Srujan Rokkam at Advanced Cooling Technologies...

**Comment by huangxw1995** [comment]
@mentianlong 
hello！ Did you get the example for fatigue？

**Comment by MDBrothers** [comment]
You might contact Dr. Srujan Rokkam of Advanced Cooling Technologies.

He is studying the peridynamics modelling of fatigue crack growth under
corrosive environments.

His branch of Peridigm is also closed source for now.
