### ISSUE TITLE
displacement boundary condition for disk impact example

### ISSUE THREAD

**Issue by nokyantenna** [peridigm/peridigm#53]
How does peridigm implement displacement boundary conditions where it isn't specified in the script, such as with the disk impact example?
Is there a deefault displacement boundary it uses when not specified?
Thank you..

**Comment by djlittl** [comment]
There are no displacement boundary conditions in those cases.  For the disk impact problem, there are only initial velocities.  It's a explicit dynamics simulations, so rigid body modes are okay (and expected in this case).
