### ISSUE TITLE
Segmentation Fault -- Run Peridigm

### ISSUE THREAD

**Issue by mechanicalstudent** [peridigm/peridigm#56]
After compile the following the required packages i receive following error.

Can anyone help me to solve this problem ?

![failure](https://user-images.githubusercontent.com/39726007/40646822-a1290752-632a-11e8-8c6a-c4f0753c870e.png)

**Comment by mechanicalstudent** [comment]
Thanks. 

Is the "decomp" utility a ShellScript, or should it also be a executeable ?

**Comment by djlittl** [comment]
It is a script that calls other executables (e.g., nem_spread).  Decomp should be in the "bin" directory where you installed Trilinos.

**Comment by mechanicalstudent** [comment]
Ok.     After solving this problem  ...  following error occours

![failure](https://user-images.githubusercontent.com/39726007/40927232-7f6f9c72-681e-11e8-9a85-df53ae01551e.png)

What does not work ?

**Comment by MDBrothers** [comment]
It appears that the input *.g files are not present. Have you run 'decomp'
on tensile_test.g?

**Comment by smenonUF** [comment]
djlittl mentions above where you can find decomp.

**Comment by avvasen** [comment]
The error means that Peridigm is not able to find your geometry files. You need to decompose your geometry into N files, where N is the number of processors you intend to use. Also, make sure to execute Peridigm from the same folder where you stored your geometry and input files.

**Comment by mechanicalstudent** [comment]
Ok, then following error occours  >>  No command 'decomp' found
but in trilinos-bin there is decomp (Shellscript)

**Comment by avvasen** [comment]
You need either copy it to your working folder or create a path.

**Comment by 15121992** [comment]
I am doing this and getting error:


anirban@anirban-desktop:~/iisc/Softwares/peridigm/Peridigm/examples/fragmenting_cylinder_1$ ls

Output: 

fragmenting_cylinder_generate_mesh.py  fragmenting_cylinder.peridigm  fragmenting_cylinder.txt


anirban@anirban-desktop:~/iisc/Softwares/peridigm/Peridigm/examples/fragmenting_cylinder_1$ /usr/local/openmpi/bin/mpiexec -np 4 /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm fragmenting_cylinder.peridigm

Output:

-- Peridigm
-- version 1.4.1

MPI initialized on 4 processors.

[anirban-desktop:30720] *** Process received signal ***
[anirban-desktop:30720] Signal: Aborted (6)
[anirban-desktop:30720] Signal code:  (-6)
[anirban-desktop:30720] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f94ac2ff390]
[anirban-desktop:30720] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f94abf59428]
[anirban-desktop:30720] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f94abf5b02a]
[anirban-desktop:30720] [ 3] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x33f5)[0x7f94ac50e3f5]
[anirban-desktop:30720] [ 4] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS13seed_rand_numEj+0x28)[0x7ef7a8]
[anirban-desktop:30720] [ 5] [anirban-desktop:30719] *** Process received signal ***
[anirban-desktop:30719] Signal: Aborted (6)
[anirban-desktop:30719] Signal code:  (-6)
[anirban-desktop:30719] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fe5eebc9390]
[anirban-desktop:30719] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7fe5ee823428]
[anirban-desktop:30719] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fe5ee82502a]
[anirban-desktop:30719] [ 3] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x33f5)[0x7fe5eedd83f5]
[anirban-desktop:30719] [ 4] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS8PeridigmC2ERKP19ompi_communicator_tN7Teuchos3RCPINS5_13ParameterListEEENS6_INS_14DiscretizationEEE+0xc72)[0x6d9cf2]
[anirban-desktop:30720] [ 6] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS15PeridigmFactory6createENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKP19ompi_communicator_tN7Teuchos3RCPINS_14DiscretizationEEE+0x1bc)[0x7d597c]
[anirban-desktop:30720] [ 7] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS13seed_rand_numEj+0x28)[0x7ef7a8]
[anirban-desktop:30719] [ 5] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS15PeridigmFactory6createENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKP19ompi_communicator_t+0x99)[0x7d2599]
[anirban-desktop:30720] [ 8] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS8PeridigmC2ERKP19ompi_communicator_tN7Teuchos3RCPINS5_13ParameterListEEENS6_INS_14DiscretizationEEE+0xc72)[0x6d9cf2]
[anirban-desktop:30719] [ 6] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(main+0x2bb)[0x6b3d4b]
[anirban-desktop:30720] [ 9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f94abf44830]
[anirban-desktop:30720] [10] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS15PeridigmFactory6createENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKP19ompi_communicator_tN7Teuchos3RCPINS_14DiscretizationEEE+0x1bc)[0x7d597c]
[anirban-desktop:30719] [ 7] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_start+0x29)[0x6c67e9]
[anirban-desktop:30720] *** End of error message ***
/home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS15PeridigmFactory6createENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKP19ompi_communicator_t+0x99)[0x7d2599]
[anirban-desktop:30719] [ 8] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(main+0x2bb)[0x6b3d4b]
[anirban-desktop:30719] [ 9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fe5ee80e830]
[anirban-desktop:30719] [10] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_start+0x29)[0x6c67e9]
[anirban-desktop:30719] *** End of error message ***
[anirban-desktop:30721] *** Process received signal ***
[anirban-desktop:30721] Signal: Aborted (6)
[anirban-desktop:30721] Signal code:  (-6)
[anirban-desktop:30721] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fc4014fc390]
[anirban-desktop:30721] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7fc401156428]
[anirban-desktop:30721] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7fc40115802a]
[anirban-desktop:30721] [ 3] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x33f5)[0x7fc40170b3f5]
[anirban-desktop:30721] [ 4] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS13seed_rand_numEj+0x28)[0x7ef7a8]
[anirban-desktop:30721] [ 5] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS8PeridigmC2ERKP19ompi_communicator_tN7Teuchos3RCPINS5_13ParameterListEEENS6_INS_14DiscretizationEEE+0xc72)[0x6d9cf2]
[anirban-desktop:30721] [ 6] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS15PeridigmFactory6createENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKP19ompi_communicator_tN7Teuchos3RCPINS_14DiscretizationEEE+0x1bc)[0x7d597c]
[anirban-desktop:30721] [ 7] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS15PeridigmFactory6createENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKP19ompi_communicator_t+0x99)[0x7d2599]
[anirban-desktop:30721] [ 8] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(main+0x2bb)[0x6b3d4b]
[anirban-desktop:30721] [ 9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fc401141830]
[anirban-desktop:30721] [10] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_start+0x29)[0x6c67e9]
[anirban-desktop:30721] *** End of error message ***
[anirban-desktop:30718] *** Process received signal ***
[anirban-desktop:30718] Signal: Aborted (6)
[anirban-desktop:30718] Signal code:  (-6)
[anirban-desktop:30718] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f8420939390]
[anirban-desktop:30718] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f8420593428]
[anirban-desktop:30718] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f842059502a]
[anirban-desktop:30718] [ 3] /lib/x86_64-linux-gnu/libgcc_s.so.1(+0x33f5)[0x7f8420b483f5]
[anirban-desktop:30718] [ 4] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS13seed_rand_numEj+0x28)[0x7ef7a8]
[anirban-desktop:30718] [ 5] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS8PeridigmC2ERKP19ompi_communicator_tN7Teuchos3RCPINS5_13ParameterListEEENS6_INS_14DiscretizationEEE+0xc72)[0x6d9cf2]
[anirban-desktop:30718] [ 6] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS15PeridigmFactory6createENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKP19ompi_communicator_tN7Teuchos3RCPINS_14DiscretizationEEE+0x1bc)[0x7d597c]
[anirban-desktop:30718] [ 7] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_ZN10PeridigmNS15PeridigmFactory6createENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKP19ompi_communicator_t+0x99)[0x7d2599]
[anirban-desktop:30718] [ 8] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(main+0x2bb)[0x6b3d4b]
[anirban-desktop:30718] [ 9] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f842057e830]
[anirban-desktop:30718] [10] /home/anirban/iisc/Softwares/peridigm/Peridigm/src/Peridigm(_start+0x29)[0x6c67e9]
[anirban-desktop:30718] *** End of error message ***
--------------------------------------------------------------------------
mpiexec noticed that process rank 3 with PID 30721 on node anirban-desktop exited on signal 6 (Aborted).
--------------------------------------------------------------------------
