### ISSUE TITLE
problem with make test

### ISSUE THREAD

**Issue by amardahiya** [peridigm/peridigm#57]
I have passed the make for the installation of Peridigm, but after, when I run the make test command, there are only 32% tests passed, 127 tests failed out of 187.  Any help to resolve this issue? Similar issue (#25) is already resolved but doesn't work for me. 
The following tests FAILED:
          2 - utPeridigm_Compute_Force_MPI_np2 (Failed)
          4 - utPeridigm_Compute_Angular_Momentum_MPI_np2 (Failed)
          6 - utPeridigm_Compute_Linear_Momentum_MPI_np2 (Failed)
          8 - utPeridigm_Compute_Kinetic_Energy_MPI_np2 (Failed)
         10 - utPeridigm_State_np2 (Failed)
         12 - utPeridigm_PdQuickGridDiscretization_MPI_np2 (Failed)
         14 - utPeridigm_ExodusDiscretization_MPI_np2 (Failed)
         19 - ut_QuickGrid_solidCylinder_np2 (Failed)
         20 - ut_QuickGridMPI_np2_3x3x2 (Failed)
         21 - ut_QuickGridMPI_np3 (Failed)
         22 - ut_SmallMeshCylinder_np4 (Failed)
         24 - ut_frameset_2x2x1_np4 (Failed)
         27 - ut_Y-Z_crack_np4 (Failed)
         28 - ut_Y-Z_crack_jacobian_np4 (Failed)
         31 - ut_QuickGrid_loadBal_np2_3x1x1 (Failed)
         32 - ut_QuickGrid_loadBal_np2_4x4x4 (Failed)
         33 - ut_QuickGrid_loadBal_np8_4x4x4 (Failed)
         35 - utReloadBalance_np4 (Failed)
         45 - utPeridigm_ProximitySearch_np2 (Failed)
         46 - utPeridigm_ProximitySearch_np3 (Failed)
         47 - utPeridigm_ProximitySearch_np4 (Failed)
         48 - utPeridigm_ProximitySearch_np5 (Failed)
         55 - NOX_QS_MatrixFree_NoPrec_np1 (Failed)
         56 - NOX_QS_MatrixFree_NoPrec_np4 (Failed)
         57 - NOX_QS_MatrixFree_3x3Prec_np1 (Failed)
         58 - NOX_QS_MatrixFree_3x3Prec_np4 (Failed)
         59 - NOX_QS_MatrixFree_FullTangentPrec_np1 (Failed)
         60 - NOX_QS_MatrixFree_FullTangentPrec_np4 (Failed)
         61 - NOX_QS_Newton_NoPrec_np1 (Failed)
         62 - NOX_QS_Newton_NoPrec_np4 (Failed)
         63 - NOX_QS_Newton_AztecOOPrec_np1 (Failed)
         64 - NOX_QS_Newton_AztecOOPrec_np4 (Failed)
         65 - BodyForce_Implicit_np1 (Failed)
         66 - BodyForce_Implicit_np4 (Failed)
         67 - BodyForce_Explicit_np1 (Failed)
         68 - BodyForce_Explicit_np4 (Failed)
         69 - BodyForce_QS_np1 (Failed)
         70 - BodyForce_QS_np4 (Failed)
         71 - BodyForce_QS_NOX_np1 (Failed)
         72 - BodyForce_QS_NOX_np4 (Failed)
         73 - CentrifugalLoad_np1 (Failed)
         74 - CentrifugalLoad_np4 (Failed)
         76 - Compression_NLCGQS_3x2x2_np2 (Failed)
         77 - Contact_Cubes_np1 (Failed)
         78 - Contact_Cubes_np4 (Failed)
         79 - Contact_Cubes_Interaction_Blocks_np1 (Failed)
         80 - Contact_Cubes_Interaction_Blocks_np4 (Failed)
         81 - Contact_Ring_np1 (Failed)
         82 - Contact_Ring_np4 (Failed)
         83 - Contact_Perforation_np1 (Failed)
         84 - Contact_Perforation_np3 (Failed)
         86 - Compression_QS_3x2x2_np2 (Failed)
         88 - Multiphysics_QS_3x2x2_np2 (Failed)
         90 - Compression_QS_Explicit_3x2x2_np2 (Failed)
         92 - Compression_QS_Explicit_MultiFreqOutput_3x2x2_np2 (Failed)
         94 - Compression_QS_CyclicLoading_3x2x2_np2 (Failed)
         95 - Compression_QS_3x2x2_Exodus_np1 (Failed)
         96 - Compression_QS_3x2x2_Exodus_np2 (Failed)
         97 - Compression_QS_3x2x2_TextFile_np1 (Failed)
         98 - Compression_QS_3x2x2_TextFile_np3 (Failed)
         99 - WaveInBar_np1 (Failed)
        100 - WaveInBar_np3 (Failed)
        101 - WaveInBar_MultiBlock_np1 (Failed)
        102 - WaveInBar_MultiBlock_np4 (Failed)
        103 - Bar_OneBlock_OneMaterial_QS_np1 (Failed)
        104 - Bar_OneBlock_OneMaterial_QS_np2 (Failed)
        105 - Bar_TwoBlocks_OneMaterial_QS_np1 (Failed)
        106 - Bar_TwoBlocks_OneMaterial_QS_np2 (Failed)
        107 - Bar_TwoBlocks_TwoMaterial_QS_np1 (Failed)
        108 - Bar_TwoBlocks_TwoMaterial_QS_np2 (Failed)
        109 - Bar_TwoBlocks_TwoDifferentMaterial_QS_np1 (Failed)
        110 - Bar_TwoBlocks_TwoDifferentMaterial_QS_np2 (Failed)
        111 - Bar_TwoBlocks_TwoDifferentMaterial_QS_np3 (Failed)
        112 - Bar_TwoDisconnectedPieces_QS_np1 (Failed)
        113 - Bar_TwoDisconnectedPieces_QS_np2 (Failed)
        114 - Bar_TwoDisconnectedPieces_QS_np3 (Failed)
        117 - MultipleOutputFiles_np2 (Failed)
        118 - DefaultBlocks_np1 (Failed)
        119 - DefaultBlocks_np4 (Failed)
        120 - PrecrackedPlate_np1 (Failed)
        121 - PrecrackedPlate_np4 (Failed)
        122 - PrecrackedPlateTwoCracks_np1 (Failed)
        123 - PrecrackedPlateTwoCracks_np4 (Failed)
        124 - DeformationGradient_PlaneStrainCompression_np1 (Failed)
        125 - DeformationGradient_PlaneStrainCompression_np4 (Failed)
        126 - DeformationGradient_SimpleShear_np1 (Failed)
        127 - DeformationGradient_SimpleShear_np4 (Failed)
        128 - DeformationGradient_PureShear_np1 (Failed)
        129 - DeformationGradient_PureShear_np4 (Failed)
        130 - DeformationGradient_SolidRotation_np1 (Failed)
        131 - DeformationGradient_SolidRotation_np4 (Failed)
        132 - DeformationGradient_NoDeformation_np1 (Failed)
        133 - DeformationGradient_NoDeformation_np4 (Failed)
        134 - DeformationGradient_NoLoad_np1 (Failed)
        135 - DeformationGradient_NoLoad_np4 (Failed)
        137 - Interfaces_np4 (Failed)
        138 - Pals_Simple_Shear_np1 (Failed)
        140 - CompressionImplicit_2x1x1_np2 (Failed)
        142 - CompressionImplicitEssentialBC_2x1x1_np2 (Failed)
        143 - ElasticCorrespondenceFullyPrescribedTension_np1 (Failed)
        144 - ElasticCorrespondenceFullyPrescribedTension_np4 (Failed)
        146 - ElasticPlasticCorrespondenceFullyPrescribedTension_np4 (Failed)
        148 - ViscoplasticNeedlemanFullyPrescribedTension_WithFlaw_np4 (Failed)
        150 - ViscoplasticNeedlemanFullyPrescribedTension_NoFlaw_np4 (Failed)
        152 - IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np4 (Failed)
        154 - IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np4 (Failed)
        155 - ElasticCorrespondenceQSTension_np1 (Failed)
        156 - ElasticCorrespondenceQSTension_np4 (Failed)
        157 - MultipleHorizons_np1 (Failed)
        158 - MultipleHorizons_np4 (Failed)
        159 - VariableHorizonParsing_np1 (Failed)
        160 - VariableHorizonParsing_np4 (Failed)
        162 - Compression_2x1x1_np2 (Failed)
        164 - CompressionInitDisp_2x1x1_np2 (Failed)
        166 - Compression_3x1x1_np2 (Failed)
        167 - Compression_3x1x1_np3 (Failed)
        169 - Compression_3x1x1_InfluenceFunction_np2 (Failed)
        170 - Compression_3x1x1_InfluenceFunction_np3 (Failed)
        173 - BondBreakingInitialVelocity_np3 (Failed)
        174 - BondBreakingInitialVelocity-EP_np1 (Failed)
        175 - BondBreakingInitialVelocity-EP_np3 (Failed)
        177 - BondBreakingInitialVelocity_TimeDependentCS_np3 (Failed)
        179 - Contact_2x1x1_np2 (Failed)
        181 - Contact_Friction_np2 (Failed)
        183 - Contact_Friction_Time_Dependent_Coefficient_np2 (Failed)
        185 - ThermalExpansionCube_np4 (Failed)
        187 - ThermalExpansionBondFailure_np4 (Failed)
Errors while running CTest
make: *** [test] Error 8

File attached contains the details of failed tests
[Peridigm_CTest.txt](https://github.com/peridigm/peridigm/files/2135914/Peridigm_CTest.txt)

**Comment by GeoGroup** [comment]
I have the same problem. Do you solve this problem??? Thank you.

**Comment by djlittl** [comment]
Each of the tests produces a log file.  Please dig into the test directory for one of the failing tests, and post the contents of the log file.  Hopefully the log file will tell us what's going wrong.

**Comment by twagnert** [comment]
The 78 failed test seem to be related to your system. I also experienced that one system (CentOS) had problems with the relatives paths and was searching for the *.g file in a subfolder (WaveInBar/np1 in your case) whereas the actual file is under WaveInBar. Debian for example did not cause me these problems. 
It is also exactly 78 tests that failed this way. You could try to just create symbolic links in each subfolder for the missing *.g files.
