### ISSUE TITLE
fracture by elastic correspondence material

### ISSUE THREAD

**Issue by yocchi2015** [peridigm/peridigm#62]
Dear Peridigm users,

I am trying to simulate a thin brittle plate being shattered by a colliding rigid ball. With "elastic material" in Peridigm and some critical stretch value set for its damage model, the plate nicely shattered as I expected. However, when I changed the material model to "elastic correspondence material", keeping the other settings the same, the plate elongated just like rubber no matter how fast the ball hit the plate. 

I am very puzzled about these different phenomena, which are caused only by the choice of the two material models. The elastic material model is good to show fracture patterns, I believe. But I also want to obtain stress and strain fields, which can be turned on by use of the elastic correspondence material. This is the reason I am trying to use the correspondence model in the simulation. 

Can someone suggest how to setup a simulation that involves crack, fracture, fragmentation by using the elastic correspondence model?  

Thank you for your suggestion in advance.
Yoichi

**Comment by bkak83** [comment]
I have encountered the same problem when trying to reproduce fracture with correspondence models. 

The damage contours are present but I cannot seem to get actual fracture or degradation of the material response. The damage seems to have no effect and I noticed that none of the correspondence model examples have a damage model in the input deck. 

I have encountered the same issue with the PALS model as well, which as I understand it is not a state based non-correspondence model.

I did read somewhere that correspondence models currently do not have a well defined failure criteria, however it would be worth clarifying this as I'm not sure whether I might be missing something in the input decks.
