### ISSUE TITLE
In example/tensile_test, How to post process

### ISSUE THREAD

**Issue by ignoranc** [peridigm/peridigm#63]
Dear Peridigm users,

I have ran the example tensile_test in the  example file, But I execute ./tensile_test.post to  post process .
It can't working ,the  wrong imformations:

./tensile_test.post: line 1: blot: command not found

set terminal pdf enhanced font "Times-Roman,24" size 12in, 8in 
             ^
"tensile_test.plotgen", line 9: unknown or ambiguous terminal type; type just 'set terminal' for a list

./tensile_test.post: line 3: tensile_test_compute_modulus.py: command not found

The  tensile_test.post :

blot tensile_test.e -input tensile_test.blot cps
gnuplot tensile_test.plotgen
tensile_test_compute_modulus.py
 
I don't know how to do!  Can you provide more information?

**Comment by djlittl** [comment]
It sounds like the Peridigm simulation itself ran without error.  If so, you can open tensile_test.e in ParaView to visualize the results.

The .post file is a script that runs blot (a seacas utility) and gnuplot.  Blot extracts the displacements of a pair of nodes (virtual strain gauge) and the reaction forces on the ends of the bar (the .blot file contains commands for blot).  They get written to a text file, and then gnuplot is called to generate an engineering stress-strain plot (the .plotgen file contains gnuplot commands).

To fix the blot error, you probably just need to add blot to your PATH.  Blot is built as part of seacas, and can be found in your trilinos build bin directory.  Gnuplot is an unrelated plotting program.  You can find it on the web and follow their installation instructions.  Gnuplot is available via most package management systems (e.g., MacPorts).

None of the post processing stuff is really necessary.  We included it with the examples to give users an example of one way to post process data.  You can just use ParaView for most post processing.  Or you can write a python script and use the exodus.py module.  Whatever works best for you.

Dave

**Comment by ignoranc** [comment]
Thanks !

I add the trilinos build bin directory and it work
