### ISSUE TITLE
In example/tensile_test, Error:  Aborting analysis.

### ISSUE THREAD

**Issue by ignoranc** [peridigm/peridigm#64]
Dear Peridigm users,

I have ran the example tensile_test in the example file and  I have added the Damage Model Critical Stretch 0.004; the strain also changed from 0.005 to 0.1 and load steps have added from 4 to 800. Unfortunately, It shows Error:  Aborting analysis when it load the 18th step. The  wrong imformations:

Load step 18, initial time = 0.021, final time = 0.022, convergence criterion = 1
  iteration 1: residual = 6.2e+08
  iteration 2: residual = 1.4e+04
Warning:  Belos linear solver aborted with Belos::CGIterateFailure.
  --switching nonlinear solver to damped Newton and deactivating preconditioner--
  iteration 3: residual = 3.5e+02
  iteration 4: residual = 3.4e+02
  iteration 5: residual = 3.2e+02
  --line search unable to reduce residual, attempting to increase residual by 10% in hopes of escaping local minimum--
  --selecting alpha = 10, increasing residual by 0.11--
  iteration 6: residual = 3.5e+02
  iteration 7: residual = 3.5e+02
  iteration 8: residual = 3.4e+02
  --line search unable to reduce residual, attempting to increase residual by 10% in hopes of escaping local minimum--
  --selecting alpha = 10, increasing residual by 0.14--
  iteration 9: residual = 3.9e+02
  iteration 10: residual = 3.5e+02
  --line search unable to reduce residual, attempting to increase residual by 10% in hopes of escaping local minimum--
  --selecting alpha = 10, increasing residual by 0.04--

Error:  Aborting analysis.

**In my another QuasiStatic compression test, It also Aborting when it load 122th steps . The  wrong imformations:**

Warning:  Nonlinear solver failed to converge in maximum allowable iterations.
  iteration 21: residual = 14
  cpu time for load step = 78 sec., cumulative cpu time = 4.6e+03 sec.

Load step 122, initial time = 0.12, final time = 0.12, convergence criterion = 2
  iteration 1: residual = 27
  iteration 2: residual = 26
Warning:  Belos linear solver aborted with Belos::CGIterateFailure.
  --switching nonlinear solver to damped Newton and deactivating preconditioner--
Warning:  Belos linear solver aborted with Belos::CGIterateFailure.

Error:  Belos linear solver failed to converge.

Error:  Aborting analysis.

I don't know how to do! Can you provide more information?

**Comment by djlittl** [comment]
The quasi-static solvers are not currently compatible with damage.  Try running explicit dynamics.

**Comment by ignoranc** [comment]
Thanks for your answer. 

I want to get the stress-strain  curve and  damage  through compress or tensile the specime quasi-statically. If the explicit dynamics can do it ? or there have other  ways in this program?

**Comment by ignoranc** [comment]
Thanks for your answer.

I want to get the stress-strain curve and damage through compress or tensile the specime quasi-statically. If the explicit dynamics can do it ? or there have other ways in this program? @djlittl

**Comment by ignoranc** [comment]
Thanks for your answer.

I still have some questions. If I stretch an specime (such as the specime in the example tensile_test ) very slowly  till it crack.

1. I want to konw how to make the dynamic effects (waves) are negligible in Peridigm during explicit dynamics?  It needs other setup  except for the follow setup?
"Solver
    Initial Time 0.0
    Final Time 2.5e-4
    Verlet
        Safety Factor 0.7
"
2. In the the twist_and_pull example, the quasi-static and explicit time integrators switch only one time. if  the quasi-static and explicit time integrators can switch many times alternately ?

**Comment by ignoranc** [comment]
Thanks for your answer.

I still have some questions. If I stretch an specime (such as the specime in the example tensile_test ) very slowly till it crack.

I want to konw how to make the dynamic effects (waves) are negligible in Peridigm during explicit dynamics? It needs other setup except for the follow setup?
"Solver
Initial Time 0.0
Final Time 2.5e-4
Verlet
Safety Factor 0.7
"
In the the twist_and_pull example, the quasi-static and explicit time integrators switch only one time. if the quasi-static and explicit time integrators can switch many times alternately ? @djlittl

**Comment by djlittl** [comment]
No, you'd have to add that yourself.  You'd do so in the explicit time integrator in the Peridigm.cpp file.
