### ISSUE TITLE
Can I compute the laminated composite materials by Peridigm?

### ISSUE THREAD

**Issue by 752096822** [peridigm/peridigm#69]
Can I compute the laminated composite materials by Peridigm? How can I do it? For instance, could I model through layer by layer,then give them different parameters?

**Comment by 752096822** [comment]
> There are no features in Peridigm that are specific for laminated materials, but you should be able to do exactly what you describe. Each layer could be modeled as a separate block. By default, the interaction between blocks will be an average of the material response from each of the two blocks. If desired, you could fairly easily implement a material model that acts differently on bonds that connect two different blocks.

**Comment by Annaovgu** [comment]
Thank you a lot!
