### ISSUE TITLE
Suggest modification to Trilinos build flags related to SEACAS 

### ISSUE THREAD

**Issue by gsjaardema** [peridigm/peridigm#7]
Im the Trilinos configuration script shown on the Peridigm web page, I would recommend adding:
```
-D TPL_Netcdf_Enables_Netcdf4:BOOL=ON \
-D Trilinos_EXTRA_LINK_FLAGS:STRING="-L${TPL}/lib -lhdf5_hl -lhdf5 -lz” \
```
Where `${TPL}` specifies the directory containing the hdf5 libraries.  We/I am working on simplifying the specification of the required libraries for SEACAS in Trilinos, but for now these are required if using netcdf-4 enabled netcdf libraries which is recommended.

**Comment by johntfoster** [comment]
@djlittl We just move the "getting started" guide to a file in the repo or the main README.md so we can accept pull requests against it.
