### ISSUE TITLE
How do I use contact model?

### ISSUE THREAD

**Issue by 752096822** [peridigm/peridigm#71]
Hi David,May I ask you some questions? First of all,How do I use contact model? What is the meanings in the contact model，for example search radius,search frequency,contact radius and spring constant? How do I set these parameters in my own model?   
Then  how do I use Output file for history data (global data) ?  What kind of data could I hist?For example,I find .h file in disk_impact example, and how do I open it ? How do I find information about Global_Kinetic_Energy ?
Thank you very much!

**Comment by 752096822** [comment]
Hi，David，May I ask you some questions?I want to extract some data from the models, such as energy changes，how do I do it？
Thank you very much!

**Comment by 752096822** [comment]
Hi David,May I ask you some questions? I want to extract data from some models, such as energy changes.How do I do it？ 
Thank you very much!

**Comment by djlittl** [comment]
Here's a document that could help answer some of your questions:

https://www.sandia.gov/~djlittl/docs/PeridynamicSoftwareRoadmap.pdf

Also, the original paper that presents the contact model is:

S. A. Silling and E. Askari. A meshfree method based on the peridynamic model of solid mechanics. Computers and Structures, 83:1526–1535, 2005.

Peridigm output follows the Exodus file format.  The standard (.e) output files contain data for the full mesh.  The history files (.h) contain only global data (no mesh data).  There are many ways to access the data in an exodus file.  Paraview is an excellent open-source visualization code that can read them.  You can also access the data using a python script and the exodus.py module.  A third option is the blot utility, distributed with SEACAS (which is built with Trilinos and should be in your Trilinos bin directory).

Peridigm has the ability to compute kinetic energy, as you mentioned (Global_Kinetic_Energy).  Stored elastic energy can be computed, but I believe it's only implemented for the Elastic model.  The material model itself must have a function for computing the stored elastic energy in order for Peridigm to output it.

**Comment by Annaovgu** [comment]
Thanks a lot for the answer!

**Comment by 752096822** [comment]
Thanks a lot for the answer!
