### ISSUE TITLE
fatal error: aprepro.h: No such file or directory

### ISSUE THREAD

**Issue by ggulgulia** [peridigm/peridigm#77]
I issued the command `make -j 4` and get the following error at some point during compilation  
(not pasting the entire output, but only few lines just before the error happened) : 

``
[ 22%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_CriticalTimeStep.cpp.o
[ 23%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_DataManager.cpp.o
[ 23%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Enums.cpp.o
[ 24%] Building CXX object src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Factory.cpp.o
/home/gulgulia/GG/Thesis/Peridigm/src/core/Peridigm_Factory.cpp:61:10: fatal error: aprepro.h: No such file or directory
 #include "aprepro.h"
          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/PeridigmLib.dir/build.make:544: src/CMakeFiles/PeridigmLib.dir/core/Peridigm_Factory.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:140: src/CMakeFiles/PeridigmLib.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
``
Update on missiing aprepros 
I assume this is some file in Trilinos. When i issued `locate aprepro.h` on the terminal, I got the following  output : 
`
/mhpc/programs64/Trelis-15.1/bin/help/appendix/aprepro/aprepro.htm
/mhpc/programs64/Trelis-16.4/bin/help/appendix/aprepro/aprepro.htm
/mhpc/programs64/Trelis-16.5/bin/help/appendix/aprepro/aprepro.htm
/mhpc/programs64/Trelis-16.5.2/bin/help/appendix/aprepro/aprepro.htm
/mhpc/programs64/cubit-10.2/components/cubit/help/appendix/aprepro/aprepro.htm
/mhpc/programs64/cubit-13.2/bin/help/appendix/aprepro/aprepro.htm
` 
which clearly indicates aprepros.h is missing in the trilinos package i generated. 

This happened due to some older version of trilinos which I found in my departments repository.

On further search google led me [here](https://github.com/trilinos/Trilinos/issues/1614) which says having this flag for trilinos should do the work : 
-D Trilinos_ENABLE_SEACASAprepro_lib:BOOL=ON

Is this old issue of trilinos not fixed yet or is this issue something specific to Peridigm and if yes, is there a way to get around it ? I basically want to avoid going through the pain of installing Trilinos all over again :/

**Comment by djlittl** [comment]
Is aprepro in your Trilinos bin directory?  Just trying to find out if it was actually built or not.

**Comment by ggulgulia** [comment]
Hi David,
I think I used an old version of Trilinos that didn't have aprepros so I guess this is seems to be not related to Peridigm but rather Trilinos
