### ISSUE TITLE
make test error

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#78]
When I type make test, it gives me:

52% tests passed, 91 tests failed out of 188

Total Test time (real) = 177.83 sec

The following tests FAILED:
          2 - utPeridigm_Compute_Force_MPI_np2 (Failed)
          4 - utPeridigm_Compute_Angular_Momentum_MPI_np2 (Failed)
          6 - utPeridigm_Compute_Linear_Momentum_MPI_np2 (Failed)
          8 - utPeridigm_Compute_Kinetic_Energy_MPI_np2 (Failed)
         10 - utPeridigm_State_np2 (Failed)
         12 - utPeridigm_PdQuickGridDiscretization_MPI_np2 (Failed)
         14 - utPeridigm_ExodusDiscretization_MPI_np2 (Failed)
         19 - ut_QuickGrid_solidCylinder_np2 (Failed)
         20 - ut_QuickGridMPI_np2_3x3x2 (Failed)
         21 - ut_QuickGridMPI_np3 (Failed)
         22 - ut_SmallMeshCylinder_np4 (Failed)
         24 - ut_frameset_2x2x1_np4 (Failed)
         27 - ut_Y-Z_crack_np4 (Failed)
         28 - ut_Y-Z_crack_jacobian_np4 (Failed)
         31 - ut_QuickGrid_loadBal_np2_3x1x1 (Failed)
         32 - ut_QuickGrid_loadBal_np2_4x4x4 (Failed)
         33 - ut_QuickGrid_loadBal_np8_4x4x4 (Failed)
         35 - utReloadBalance_np4 (Failed)
         44 - utPeridigm_ProximitySearch_np2 (Failed)
         45 - utPeridigm_ProximitySearch_np3 (Failed)
         46 - utPeridigm_ProximitySearch_np4 (Failed)
         47 - utPeridigm_ProximitySearch_np5 (Failed)
         55 - NOX_QS_MatrixFree_NoPrec_np4 (Failed)
         57 - NOX_QS_MatrixFree_3x3Prec_np4 (Failed)
         59 - NOX_QS_MatrixFree_FullTangentPrec_np4 (Failed)
         61 - NOX_QS_Newton_NoPrec_np4 (Failed)
         63 - NOX_QS_Newton_AztecOOPrec_np4 (Failed)
         65 - BodyForce_Implicit_np4 (Failed)
         67 - BodyForce_Explicit_np4 (Failed)
         69 - BodyForce_QS_np4 (Failed)
         71 - BodyForce_QS_NOX_np4 (Failed)
         73 - CentrifugalLoad_np4 (Failed)
         75 - Compression_NLCGQS_3x2x2_np2 (Failed)
         77 - Contact_Cubes_np4 (Failed)
         79 - Contact_Cubes_Interaction_Blocks_np4 (Failed)
         81 - Contact_Ring_np4 (Failed)
         83 - Contact_Perforation_np3 (Failed)
         85 - Compression_QS_3x2x2_np2 (Failed)
         87 - Multiphysics_QS_3x2x2_np2 (Failed)
         89 - Compression_QS_Explicit_3x2x2_np2 (Failed)
         90 - Compression_QS_Explicit_MultiFreqOutput_3x2x2_np1 (Failed)
         91 - Compression_QS_Explicit_MultiFreqOutput_3x2x2_np2 (Failed)
         93 - Compression_QS_CyclicLoading_3x2x2_np2 (Failed)
         95 - Compression_QS_3x2x2_Exodus_np2 (Failed)
         97 - Compression_QS_3x2x2_TextFile_np3 (Failed)
         99 - WaveInBar_np3 (Failed)
        101 - WaveInBar_MultiBlock_np4 (Failed)
        103 - Bar_OneBlock_OneMaterial_QS_np2 (Failed)
        105 - Bar_TwoBlocks_OneMaterial_QS_np2 (Failed)
        107 - Bar_TwoBlocks_TwoMaterial_QS_np2 (Failed)
        109 - Bar_TwoBlocks_TwoDifferentMaterial_QS_np2 (Failed)
        110 - Bar_TwoBlocks_TwoDifferentMaterial_QS_np3 (Failed)
        112 - Bar_TwoDisconnectedPieces_QS_np2 (Failed)
        113 - Bar_TwoDisconnectedPieces_QS_np3 (Failed)
        116 - MultipleOutputFiles_np2 (Failed)
        118 - DefaultBlocks_np4 (Failed)
        120 - PrecrackedPlate_np4 (Failed)
        122 - PrecrackedPlateTwoCracks_np4 (Failed)
        124 - DiskFilter_np4 (Failed)
        126 - DeformationGradient_PlaneStrainCompression_np4 (Failed)
        128 - DeformationGradient_SimpleShear_np4 (Failed)
        130 - DeformationGradient_PureShear_np4 (Failed)
        132 - DeformationGradient_SolidRotation_np4 (Failed)
        134 - DeformationGradient_NoDeformation_np4 (Failed)
        136 - DeformationGradient_NoLoad_np4 (Failed)
        138 - Interfaces_np4 (Failed)
        141 - Compression_2x1x1_np2 (Failed)
        143 - Compression_3x1x1_np2 (Failed)
        144 - Compression_3x1x1_np3 (Failed)
        146 - CompressionImplicit_2x1x1_np2 (Failed)
        148 - CompressionImplicitEssentialBC_2x1x1_np2 (Failed)
        150 - ElasticCorrespondenceFullyPrescribedTension_np4 (Failed)
        152 - ElasticPlasticCorrespondenceFullyPrescribedTension_np4 (Failed)
        154 - ViscoplasticNeedlemanFullyPrescribedTension_WithFlaw_np4 (Failed)
        156 - ViscoplasticNeedlemanFullyPrescribedTension_NoFlaw_np4 (Failed)
        158 - IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw_np4 (Failed)
        160 - IsotropicHardeningPlasticFullyPrescribedTension_WithFlaw_np4 (Failed)
        162 - ElasticCorrespondenceQSTension_np4 (Failed)
        164 - MultipleHorizons_np4 (Failed)
        166 - VariableHorizonParsing_np4 (Failed)
        168 - CompressionInitDisp_2x1x1_np2 (Failed)
        170 - Compression_3x1x1_InfluenceFunction_np2 (Failed)
        171 - Compression_3x1x1_InfluenceFunction_np3 (Failed)
        174 - BondBreakingInitialVelocity_np3 (Failed)
        176 - BondBreakingInitialVelocity-EP_np3 (Failed)
        178 - BondBreakingInitialVelocity_TimeDependentCS_np3 (Failed)
        180 - Contact_2x1x1_np2 (Failed)
        182 - Contact_Friction_np2 (Failed)
        184 - Contact_Friction_Time_Dependent_Coefficient_np2 (Failed)
        186 - ThermalExpansionCube_np4 (Failed)
        188 - ThermalExpansionBondFailure_np4 (Failed)
Errors while running CTest
Makefile:94: recipe for target 'test' failed
make: *** [test] Error 8

And I checked \home\rbh\peridigm\build\test\regression\WaveInBar\np3\WaveInBar.log:

[DESKTOP-CSSB1H6:02470] PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../../../../opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/v12/unpack.c at line 206
[DESKTOP-CSSB1H6:02470] PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../../../../opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/v12/unpack.c at line 147
[DESKTOP-CSSB1H6:02470] PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c at line 228
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[DESKTOP-CSSB1H6:02470] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[DESKTOP-CSSB1H6:02470] OPAL ERROR: Error in file ../../../../../opal/mca/pmix/pmix2x/pmix2x_client.c at line 109
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
[DESKTOP-CSSB1H6:02471] PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../../../../opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/v12/unpack.c at line 206
[DESKTOP-CSSB1H6:02471] PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../../../../opal/mca/pmix/pmix2x/pmix/src/mca/bfrops/v12/unpack.c at line 147
[DESKTOP-CSSB1H6:02471] PMIX ERROR: UNPACK-PAST-END in file ../../../../../../../opal/mca/pmix/pmix2x/pmix/src/client/pmix_client.c at line 228
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[DESKTOP-CSSB1H6:02471] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
[DESKTOP-CSSB1H6:02471] OPAL ERROR: Error in file ../../../../../opal/mca/pmix/pmix2x/pmix2x_client.c at line 109
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[21490,1],0]
  Exit code:    1
--------------------------------------------------------------------------
epu --  E Pluribus Unum
	(Out of Many One -- see http://www.greatseal.com/mottoes/unum.html)
	ExodusII Parallel Unification Program
	(Version: 4.28) Modified: 2018/07/26
	Parallel Capability Not Enabled.
Cannot open file './WaveInBar.e.3.0'
ERROR: (EPU) Problem initializing input and/or output files.

   *****************************************************************
              EXODIFF	(Version: 2.94) Modified: 2018-11-12
              Authors:  Richard Drake, rrdrake@sandia.gov           
                        Greg Sjaardema, gdsjaar@sandia.gov          
              Run on    2019/01/28   20:52:43 STD
   *****************************************************************

exodiff: ERROR: Couldn't open file "WaveInBar.e".
Reading first file ... 
exodiff: ERROR: exodiff: ERROR: Couldn't open file "WaveInBar.e". File does not exist.

To build peridigm, I used:

cmake \
-D CMAKE_BUILD_TYPE:STRING=Release \
-D Boost_NO_SYSTEM_PATHS=ON \
-D Trilinos_DIR:PATH=/home/rbh/trilinos/lib/cmake/Trilinos \
-D CMAKE_CXX_COMPILER=/home/rbh/local/openmpi-3.1.2/bin/mpicxx \
-D CMAKE_C_COMPILER=/home/rbh/local/openmpi-3.1.2/bin/mpicc \
-D BOOST_ROOT=/home\rbh/local/boost-1.67 \
-D CMAKE_CXX_FLAGS:STRING="-O2 -Wall -ansi -pedantic -Wno-long-long -ftrapv -Wno-deprecated -std=gnu++11 " \
..

And in the .bashrc file, I added:

export CC=/home/rbh/local/openmpi-3.1.2/bin/mpicc 
export CXX=/home/rbh/local/openmpi-3.1.2/bin/mpicxx
export CF=/home/rbh/local/openmpi-3.1.2/bin/mpif90 
export FC=/home/rbh/local/openmpi-3.1.2/bin/mpif90 
export F77=/home/rbh/local/openmpi-3.1.2/bin/mpif77
export LIBRARY_PATH=/home/rbh/local/openmpi-3.1.2/lib/:${LIBRARY_PATH}
export PATH=/home/rbh/local/openmpi-3.1.2/bin/:$PATH
export LD_LIBRARY_PATH=/home/rbh/local/openmpi-3.1.2/lib/:/home/rbh/local/openmpi-3.1.2/lib/:$LD_LIBRARY_PATH
export LIBRARY_PATH=/home/rbh/local/openmpi-3.1.2/lib/:/home/rbh/local/openmpi-3.1.2/lib/:$LIBRARY_PATH
export LD_LIBRARY_PATH=/home/rbh/trilinos/lib/:/home/rbh/trilinos/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/hdf5/openmpi/:/usr/lib/x86_64-linux-gnu/hdf5/openmpi/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
export LIBRARY_PATH=/home/rbh/trilinos/lib/:/home/rbh/trilinos/lib/:$LIBRARY_PATH
export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/hdf5/openmpi/:/usr/lib/x86_64-linux-gnu/hdf5/openmpi/:$LIBRARY_PATH
export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/:$LIBRARY_PATH

I am wondering why the test is failed, any help would be appreciated!

Thanks in advance!

Best!

**Comment by djlittl** [comment]
Looks like Peridigm is failing to run at all.  The particular errors you show for WaveInBar.log indicate that MPI isn't able to run Peridigm.

Looking at your build configuration, you have a mistake in your BOOST_ROOT path, one of the slashes is incorrect (should be / not \).

When you run "make", does the build process complete without error?

Also, if you're using the most recent version of the code from github, then you don't need boost any more, which simplifies the build process a bit.

**Comment by rbh007720** [comment]
> Looks like Peridigm is failing to run at all. The particular errors you show for WaveInBar.log indicate that MPI isn't able to run Peridigm.
> 
> Looking at your build configuration, you have a mistake in your BOOST_ROOT path, one of the slashes is incorrect (should be / not ).
> 
> When you run "make", does the build process complete without error?
> 
> Also, if you're using the most recent version of the code from github, then you don't need boost any more, which simplifies the build process a bit.

Thanks! I changed the slash and now the error reduced to 2:

The following tests FAILED:
         33 - ut_QuickGrid_loadBal_np8_4x4x4 (Failed)
         47 - utPeridigm_ProximitySearch_np5 (Failed)
Errors while running CTest
Makefile:94: recipe for target 'test' failed
make: *** [test] Error 8

I could not find the .log file for these two errors. When I run "make", the build process completes without error.

**Comment by djlittl** [comment]
The log files are at

YOUR_BUILD_DIR/src/io/pdneigh/unit_test/ut_QuickGrid_loadBal_np8_4x4x4.log

YOUR_BUILD_DIR/src/io/unit_test/utPeridigm_ProximitySearch.log

**Comment by rbh007720** [comment]
> The log files are at
> 
> YOUR_BUILD_DIR/src/io/pdneigh/unit_test/ut_QuickGrid_loadBal_np8_4x4x4.log
> 
> YOUR_BUILD_DIR/src/io/unit_test/utPeridigm_ProximitySearch.log

ut_QuickGrid_loadBal_np8_4x4x4.log:
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 8 slots
that were requested by the application:
  ./ut_QuickGrid_loadBal_np8_4x4x4

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------

utPeridigm_ProximitySearch.log:

--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 5 slots
that were requested by the application:
  ./utPeridigm_ProximitySearch

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------

**Comment by djlittl** [comment]
Well, there you go, your system is not capable of running 8 mpi ranks.  I think it's safe to ignore these failures and consider your installation a success.
