### ISSUE TITLE
Parallel question

### ISSUE THREAD

**Issue by rbh007720** [peridigm/peridigm#83]
I used "decomp -p 4" for the mesh file and ran the simulation with "mpirun -np 4", so it gave me four .e files, namely, e.4.0 to e.4.3. I am wondering how to deal with these result data. Is each file containing one of the four sub-regions or the whole simulation? What is the relationship among those files?  

Thanks very much!

**Comment by smenon92** [comment]
Each file is associated with the processor it ran on. Use Paraview to open
them. Paraview is an open source post processor and visualisation package.

**Comment by rbh007720** [comment]
So I have to open the four files at the same time? I take a look at one of them, looks like it gives the whole simulation results.

**Comment by smenon92** [comment]
If you use Paraview's interface to open the .e (Exodus) files it collects
them together.

**Comment by rbh007720** [comment]
Thanks! I just downloaded ParaView-5.6.0-Windows-msvc2015-64bit.exe and installed it. I opened one .e.4.0 file within Paraview, so it collects all four .e files and visualize the simulation? I don't need to combine them into one file somehow, correct?

**Comment by smenon92** [comment]
You done need to combine them. Paraview will collect the related files.

**Comment by rbh007720** [comment]
Thank you so much.
