### ISSUE TITLE
Problem with "Isotropic Hardening Correspondence" Material Model

### ISSUE THREAD

**Issue by Hostudent** [peridigm/peridigm#85]
@djlittl @johntfoster 
hi
in the material model of "Isotropic Hardening Correspondence" when the solver switches to Nonlinear solver, it aborts!
the output is this:
Load step 3, initial time = 0.2, final time = 0.3, convergence criterion = 1
  iteration 1: residual = 1.3e+05
  iteration 2: residual = 7.6e+03
  iteration 3: residual = 1.7e+02
  iteration 4: residual = 1.5e+02
  iteration 5: residual = 1e+02
  iteration 6: residual = 94
  iteration 7: residual = 92
Warning:  Belos linear solver aborted with Belos::CGIterateFailure.
  --switching nonlinear solver to damped Newton and deactivating preconditioner--
Warning:  Belos linear solver aborted with Belos::CGIterateFailure.

Error:  Belos linear solver failed to converge.

Error:  Aborting analysis.

what is the problem?
i've tested this model with "Elastic Plastic Correspondence" and it worked out!

**Comment by Hostudent** [comment]
this is my material properties:


Materials:
      steel_hardening:
        Material Model: "Isotropic Hardening Correspondence"
        Density: 7850.0
        Young's Modulus: 2.10e+11
        Poisson's Ratio: 0.30
        Yield Stress: 2.40e+08
        Hardening Modulus: 2.10e+10
        Hourglass Coefficient: 0.02

**Comment by djlittl** [comment]
Have you tried with a smaller step size (change Number of Steps to something larger in the input deck)?

**Comment by Hostudent** [comment]
@djlittl yes, I've decreased load increment but it just works until the linear solver converges, as soon as solver switches to Nonlinear, it aborts!!
I think hardening behavior in both "Isotropic Hardening Correspondence" and "Elastic Plastic Correspondence" Material Model has a problem, did u checked hardening behavior in a simple tension test with large deformation(about 0.01 strain)?

**Comment by djlittl** [comment]
I did not implement either model, so no, I did not perform any verification.  This is a challenge with open-source codes.

Looking at the output you pasted in your first message, what is happening is that the quasistatic time integrator is failing to converge to the specified tolerance (which seems like a reasonable tolerance).  The "switch" that you're seeing is something that the quasistatic solver does when the linear solver fails to converge.  It attempts to get through the difficulty by switching from a straightforward Newton approach to a "Damped Newton" approach.  This is a bit of a desperate tactic, and it doesn't work for your problem, hence you see an second Belos failure.

A couple of suggestions:

1)  If the material model is flawed, then obviously that needs to be fixed.  If you have some way of figuring that out, that would be fantastic.  I do not have the resources (time, funding) to work on this myself.

2) You could try the NOX solvers instead of the native quasistatic solver.  This is done by switching the solver from "QuasiStatic" to "NOXQuasiStatic".  If you search through the test directories, you can find some examples.

3) I did a bit of work earlier this week on the use of perconditioners in Peridigm.  I was working on a thermal diffusion problem, but there's some chance that the preconditioner work might help here.  Could you provide your input deck and mesh?  You can just copy-and-paste the input deck into this github issue.  I'm not sure what the best way is to supply the mesh.  Are you using a mesh that you created yourself?

**Comment by johntfoster** [comment]
@djlittl @Hostudent There were verification tests implemented.  The resulting stress/strain plots can be seen at the bottom of [this notebook](https://github.com/peridigm/peridigm/blob/master/test/verification/IsotropicHardeningPlasticFullyPrescribedTension_NoFlaw/plots.ipynb) located in the tests/verification directory.  The output is as expected for this simple problem.

**Comment by Hostudent** [comment]
@djlittl 

Peridigm:

#     Units are SI
#       mass          kg
#       length        m
#       time          s
#       density       kg/m^3
#       force         N
#       pressure      N/m^2
#       velocity      m/s
#       acceleration  m/s^2
#       energy        j

  Verbose: false
  Discretization:
      Type: "Exodus"
      Input Mesh File: "mesh.g"
      
  Materials:
      steel_hardening:
        Material Model: "Isotropic Hardening Correspondence"
        Density: 7850.0
        Young's Modulus: 2.10e+11
        Poisson's Ratio: 0.30
        Yield Stress: 2.40e+08
        Hardening Modulus: 2.10e+10
        Hourglass Coefficient: 0.02
  
# Nodelists and Blocks Description:
#  block_1 --> Main Block
#  block_2 --> Left Block
#  block_3 --> Left_Bot Block
#  block_4 --> Right Block
#  block_5 --> Right_Bot Block
#  nodelist_1 --> Left Boundary
#  nodelist_2 --> Left_Bot Boundary
#  nodelist_3 --> Right Boundary
#  nodelist_4 --> Right_Bot Boundary
  
  Blocks:
      My Block:
        Block Names: " block_1 block_2 block_3 block_4 block_5"
        Material: "steel_hardening"
        Horizon: 0.0031
  
  Boundary Conditions:
      Prescribed Displacement Left In X:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_1"
        Coordinate: "x"
        Value: "0.005*x*t"
      Prescribed Displacement Left_Bot In Y:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_2"
        Coordinate: "y"
        Value: "0.0"
      Prescribed Displacement Left_Bot In Z:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_2"
        Coordinate: "z"
        Value: "0.0"
      Prescribed Displacement Right In X:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_3"
        Coordinate: "x"
        Value: "0.005*x*t"
      Prescribed Displacement Right_Bot In Y:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_4"
        Coordinate: "y"
        Value: "0.0"
      Prescribed Displacement Right_Bot In Z:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_4"
        Coordinate: "z"
        Value: "0.0"
  
  Solver:
      Verbose: false
      Initial Time: 0.0
      Final Time: 10.0
      QuasiStatic:
        Number of Load Steps: 1000
        Absolute Tolerance: 1.0
        Maximum Solver Iterations: 50
  
  Compute Class Parameters:
      Strain Gage Left Initial Position:
        Compute Class: "Nearest_Point_Data"
        X: -0.0995
        Y: 0.0005
        Z: 0.0015
        Variable: "Model_Coordinates"
        Output Label: "Gage_Left_Initial_Position"
        Verbose: true
      Strain Gage Right Initial Position:
        Compute Class: "Nearest_Point_Data"
        X: 0.0995
        Y: 0.0005
        Z: 0.0015
        Variable: "Model_Coordinates"
        Output Label: "Gage_Right_Initial_Position"
        Verbose: true
      Strain Gage Left Displacement:
        Compute Class: "Nearest_Point_Data"
        X: -0.0995
        Y: 0.0005
        Z: 0.0015
        Variable: "Displacement"
        Output Label: "Gage_Left_Displacement"
        Verbose: true
      Strain Gage Right Displacement:
        Compute Class: "Nearest_Point_Data"
        X: 0.0995
        Y: 0.0005
        Z: 0.0015
        Variable: "Displacement"
        Output Label: "Gage_Right_Displacement"
        Verbose: true
      Left Reaction Force:
        Compute Class: "Block_Data"
        Calculation Type: "Sum"
        Block: "block_2"
        Variable: "Force"
        Output Label: "Left_Reaction_Force"
      Right Reaction Force:
        Compute Class: "Block_Data"
        Calculation Type: "Sum"
        Block: "block_4"
        Variable: "Force"
        Output Label: "Right_Reaction_Force"
        
  Output:
      Output File Type: "ExodusII"
      Output Filename: "plate_tension"
      Output Frequency: 20
      Output Variables:
        Displacement: true
        Velocity: true
        Element_Id: true
        Proc_Num: true
        Force_Density: true
        Hourglass_Force_Density: true
        Force: true
        Volume: true
        Gage_Left_Initial_Position: true
        Gage_Right_Initial_Position: true
        Gage_Left_Displacement: true
        Gage_Right_Displacement: true
        Left_Reaction_Force: true
        Right_Reaction_Force: true
        Deformation_Gradient: true
        Cauchy_Stress: true
        Radius: true
        Number_Of_Neighbors: true
        Neighborhood_Volume: true

**Comment by Hostudent** [comment]
@djlittl 

Peridigm:

/ #     Units are SI
/ #       mass          kg
/ #       length        m
/ #       time          s
/ #       density       kg/m^3
/ #       force         N
/ #        pressure      N/m^2
/ #       velocity      m/s
/ #       acceleration  m/s^2
/ #       energy        j 

  Verbose: false
  Discretization:
      Type: "Exodus"
      Input Mesh File: "mesh.g"
      
  Materials:
      steel_hardening:
        Material Model: "Isotropic Hardening Correspondence"
        Density: 7850.0
        Young's Modulus: 2.10e+11
        Poisson's Ratio: 0.30
        Yield Stress: 2.40e+08
        Hardening Modulus: 2.10e+10
        Hourglass Coefficient: 0.02
  
/ # Nodelists and Blocks Description:
/ #  block_1 --> Main Block
/ #  block_2 --> Left Block
/ #  block_3 --> Left_Bot Block
/ #  block_4 --> Right Block
/ #  block_5 --> Right_Bot Block
/ #  nodelist_1 --> Left Boundary
/ #  nodelist_2 --> Left_Bot Boundary
/ #  nodelist_3 --> Right Boundary
/ #  nodelist_4 --> Right_Bot Boundary
  
  Blocks:
      My Block:
        Block Names: " block_1 block_2 block_3 block_4 block_5"
        Material: "steel_hardening"
        Horizon: 0.0031
  
  Boundary Conditions:
      Prescribed Displacement Left In X:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_1"
        Coordinate: "x"
        Value: "0.005*x*t"
      Prescribed Displacement Left_Bot In Y:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_2"
        Coordinate: "y"
        Value: "0.0"
      Prescribed Displacement Left_Bot In Z:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_2"
        Coordinate: "z"
        Value: "0.0"
      Prescribed Displacement Right In X:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_3"
        Coordinate: "x"
        Value: "0.005*x*t"
      Prescribed Displacement Right_Bot In Y:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_4"
        Coordinate: "y"
        Value: "0.0"
      Prescribed Displacement Right_Bot In Z:
        Type: "Prescribed Displacement"
        Node Set: "nodelist_4"
        Coordinate: "z"
        Value: "0.0"
  
  Solver:
      Verbose: false
      Initial Time: 0.0
      Final Time: 10.0
      QuasiStatic:
        Number of Load Steps: 1000
        Absolute Tolerance: 1.0
        Maximum Solver Iterations: 50
  
  Compute Class Parameters:
      Strain Gage Left Initial Position:
        Compute Class: "Nearest_Point_Data"
        X: -0.0995
        Y: 0.0005
        Z: 0.0015
        Variable: "Model_Coordinates"
        Output Label: "Gage_Left_Initial_Position"
        Verbose: true
      Strain Gage Right Initial Position:
        Compute Class: "Nearest_Point_Data"
        X: 0.0995
        Y: 0.0005
        Z: 0.0015
        Variable: "Model_Coordinates"
        Output Label: "Gage_Right_Initial_Position"
        Verbose: true
      Strain Gage Left Displacement:
        Compute Class: "Nearest_Point_Data"
        X: -0.0995
        Y: 0.0005
        Z: 0.0015
        Variable: "Displacement"
        Output Label: "Gage_Left_Displacement"
        Verbose: true
      Strain Gage Right Displacement:
        Compute Class: "Nearest_Point_Data"
        X: 0.0995
        Y: 0.0005
        Z: 0.0015
        Variable: "Displacement"
        Output Label: "Gage_Right_Displacement"
        Verbose: true
      Left Reaction Force:
        Compute Class: "Block_Data"
        Calculation Type: "Sum"
        Block: "block_2"
        Variable: "Force"
        Output Label: "Left_Reaction_Force"
      Right Reaction Force:
        Compute Class: "Block_Data"
        Calculation Type: "Sum"
        Block: "block_4"
        Variable: "Force"
        Output Label: "Right_Reaction_Force"
        
  Output:
      Output File Type: "ExodusII"
      Output Filename: "plate_tension"
      Output Frequency: 20
      Output Variables:
        Displacement: true
        Velocity: true
        Element_Id: true
        Proc_Num: true
        Force_Density: true
        Hourglass_Force_Density: true
        Force: true
        Volume: true
        Gage_Left_Initial_Position: true
        Gage_Right_Initial_Position: true
        Gage_Left_Displacement: true
        Gage_Right_Displacement: true
        Left_Reaction_Force: true
        Right_Reaction_Force: true
        Deformation_Gradient: true
        Cauchy_Stress: true
        Radius: true
        Number_Of_Neighbors: true
        Neighborhood_Volume: true

**Comment by Hostudent** [comment]
@djlittl 
I use finite element meshes, then convert them to Exodus files. for this simple problem the mesh file is about 2 MB, isn't it possible to email the mesh file to you?

**Comment by djlittl** [comment]
Yes, I think that's the best option here.  djlittl@sandia.gov.  In general it's good to keep everything on the github issue so that it's archived, but I don't think there's a good way to attach a 2MB file.  If you were using Cubit/Trelis, then you could copy-and-paste the cubit commands.  But if you're not that's fine, you can email me the file as you suggested.

**Comment by Hostudent** [comment]
@johntfoster 
in that example, the solver is velocity verlet! I don't look for a dynamic solution!
here I'm trying to solve the problem with a quasistatic solver!
I think that in this case the material model is sensitive to solver?! is that possible?

**Comment by johntfoster** [comment]
@Hostudent Nevertheless, it shows that the return algorithm is working as expected.  I would try to use NOX as a solver for a quasi-static problem.

**Comment by djlittl** [comment]
I have not run the simulation to completion, but these solver setting appear to be working much better:

  Solver:
    Verbose: false
    Final Time: 10.0
    Peridigm Preconditioner: "None"
    NOXQuasiStatic:
      Nonlinear Solver: "Line Search Based"
      Number of Load Steps: 100
      Max Solver Iterations: 100
      Relative Tolerance: 1.0e-7
      Max Age Of Prec: 100
      Direction:
        Method: "Newton"
        Newton:
          Linear Solver:
            Jacobian Operator: "Matrix-Free"
            Preconditioner: "None"
      Line Search:
        Method: "Polynomial"

I also suggest the following:

1)  I had to add asterisks to the boundary condition expressions from your input deck above "0.005xt".  I'm guessing there was a copy-and-paste glitch that somehow erased the asterisks.

2)  I added Equivalent_Plastic_Strain to the list of output variables, as it is very relevant for this simulation.

3)  I set the output frequency to 1.

**Comment by djlittl** [comment]
Here are the solver settings again.  I'm attempted to "paste as code" so that the spacing is preserved.

`  Solver:
    Verbose: false
    Final Time: 10.0
    Peridigm Preconditioner: "None"
    NOXQuasiStatic:
      Nonlinear Solver: "Line Search Based"
      Number of Load Steps: 100
      Max Solver Iterations: 100
      Relative Tolerance: 1.0e-7
      Max Age Of Prec: 100
      Direction:
        Method: "Newton"
        Newton:
          Linear Solver:
            Jacobian Operator: "Matrix-Free"
            Preconditioner: "None"
      Line Search:
        Method: "Polynomial"
`

**Comment by djlittl** [comment]
Here are the solver settings again.  I'm attempting to copy-and-paste such that the spacing is preserved.

```  Solver:
    Verbose: false
    Final Time: 10.0
    Peridigm Preconditioner: "None"
    NOXQuasiStatic:
      Nonlinear Solver: "Line Search Based"
      Number of Load Steps: 100
      Max Solver Iterations: 100
      Relative Tolerance: 1.0e-7
      Max Age Of Prec: 100
      Direction:
        Method: "Newton"
        Newton:
          Linear Solver:
            Jacobian Operator: "Matrix-Free"
            Preconditioner: "None"
      Line Search:
        Method: "Polynomial"
```

**Comment by Hostudent** [comment]
@djlittl 
thank you so much, NOX solver works completely fine, where can I find some information about the details for the NOX solver setup?

**Comment by djlittl** [comment]
NOX is part of Trilinos.  There are a few different places on the web with Trilinos documentation.  Here's one I found for NOX:

https://trilinos.org/docs/dev/packages/nox/doc/html/nox_user_information.html

Note that Peridigm extracts the solver settings from the "NOXQuasiStatic" portion of the input deck and passes them into NOX (this is done in Peridigm.cpp).  This is the part of the input deck where you can change the NOX settings.
