### ISSUE TITLE
Damage modelling for correspondence materials

### ISSUE THREAD

**Issue by bkak83** [peridigm/peridigm#87]
I am trying to run a simple benchmark test for ductile and brittle tensile or bend test samples.

I'm finding that with the ordinary state-based material models, I am able to get fracture but the constitutive response is significantly affected by surface effects although I can get damage and fracture. Grid refinement improves the accuracy but it is still not good enough.

Although I get better accuracy for the constitutive response with the state-based correspondence models as well as the PALS model, I am unable to reproduce any fracture with these models. The damage does not appear to degrade the material when included.

I know this is an area of open research but do any of the correspondence models or the PALS model work with a critical stretch damage model? I'm trying to work out whether I'm missing something in my setup, I do not that none of these models have a damage model in the supplied test deck, so maybe it is that they currently don't work with the available damage models, but I just wanted to confirm this was the case.

**Comment by sahirbutt** [comment]
Yes you are right, the necessary code for taking the damage contribution into account with the PALS and the correspondence models is not in place.
If you add the criticalStretch damage model in input deck, it would compute the bond stretches and the bondDamage, but this bondDamage information needs to be communicated to the Pals or Correspondence model.
In Pals you can do it by adding (1-bondDamage) term in the following methods:
computeDilatationAndPalsPressure() (in expression for 'theta' and 'p')
 and computeInternalForcePals() (in expression for 't') in pals.cxx file. 
check out computeNormalizedWeightedVolume() method for reference.
Hope it helps.

**Comment by bkak83** [comment]
Thanks @sahirbutt .  That is helpful. Will try it out and let you know how it goes.

**Comment by bkak83** [comment]
I have tried to replicate the necessary code as described by @sahirbutt for the PALS model however I am still unable to get it to reproduce the damage. Any ideas of how to do this?

And can we definitely rule out damage and fracture for the correspondence materials?

**Comment by sahirbutt** [comment]
Did you get any error or it did not make a difference in results? 
If it did not make any difference then probably you didn't increment the bondDamage pointer in the for loops...
Can you paste here the functions that you changed?
