### ISSUE TITLE
ViscoplasticNeedleman_model_reference

### ISSUE THREAD

**Issue by ewpostek** [peridigm/peridigm#90]
Dear Colleagues,
I consider the ViscoplasticNeedlemanFullyPrescribedTension_NoFlaw.xml material model.
Could you give a reference to this model ?

I have found that the model is an extension to the one in the
paper in IJNME "Viscoplasticity using peridynamics", however, it
has additiona term in the hardterm, namely,
(1+(eqps/refstrain1)^2)^(-1).

Could you help ?
Best regards,
Elek

**Comment by djlittl** [comment]
This is the paper cited in the source code:

D. Peirce, C.F. Shih and A. Needleman, A tangent modulus method for rate dependent solids, Comput. & Structures 18(5) (1984) 875-887.

**Comment by johntfoster** [comment]
Answered.
