### ISSUE TITLE
How do I extract displacement data from the model? 

### ISSUE THREAD

**Issue by 752096822** [peridigm/peridigm#91]
Hi David,May I ask you some questions?I want to extract displacement data from the model, such as displacement of all points in the x direction from output files.

Could you tell how I do it by Paraview in detail or other ways?

Thank you very much!

**Comment by djlittl** [comment]
The exodus.py module provides a nice python interface for extracting data from an exodus file.  The exodus.py file should be in your Trilinos installation, probably in the lib subdirectory of your install directory.  See the following for an example of how to use exodus.py:

peridigm/test/regression/WaveInCube/postprocess_exodus_file.py

**Comment by 752096822** [comment]
Hi David,Sorry for disturbing you again.When I read the postprocess_exodus_file.py, I do not understand #    The path above is valid on the CEE LAN.  On other systems, you need to provide a path to a SEACAS build,and when import exodus
>>Import exodus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "exodus.py", line 95, in <module>
EXODUS_LIB = cdll.LoadLibrary(EXODUS.SO)
  File "/usr/lib/python2.7/ctypes/__init__.py, line 443, in LoadLibrary 
return self._dlltype(nane)
  File "/usr/lib/python2.7/ctypes/__init__.py, line 365, in __init_
    self._handle=_dlopen(self ._name, mode)
OSError: /home/mpf/Desktop/soft/trilinos/prefix/lib/llbexodus,so: cannot open shared object file: No such file or directory
Can you tell me how to use exdous in detail or other easy ways to extract data from the .e file, such as displacement of all points in the x direction from output files.
Thank you

**Comment by djlittl** [comment]
You need to remove

/Users/djlittl/Software/seacas/GCC_4.9.4/lib

from

sys.path.append('/Users/djlittl/Software/seacas/GCC_4.9.4/lib')

and replace it with a path that is valid on your computer.  That is, a path that points to libexodus.a (or libexodus.dylib if you're on a Mac).  You should be able to find libexodus.a in your Trilinos build directory.

**Comment by 752096822** [comment]
I have already replace  it with a path that is valid,in that path,it includes exodus.py and libexodus.a,but when I run import exodus,the same error again. 

In WaveInCube/postprocess_exodus_file.py, it tells me
# 2) Edit exodus.py as follows (approximately line 71):
#    accessPth = "/projects/seacas/linux_rhel6/current"
#    The path above is valid on the CEE LAN.  On other systems, you need to provide a path to a SEACAS build
#    that includes shared libraries.
I don't understand what it means,so I do not do it, is it influenced?
