### ISSUE TITLE
[fragmenting cylinder example] Zoltan error + Boundary Set Error

### ISSUE THREAD

**Issue by marcoprev** [peridigm/peridigm#95]
Hello,

When I try to run the fragmenting cylinder example I run into the following error:

**** Error in DirichletBC::apply(), node set not found: FULL DOMAIN

Which I guess means the example file is deprecated and the code no longer recognizes Full Domain as a node set. "Fixing" the example by assigning sets as done in the wave in bar example, another error pops up:

Zoltan_Comm_Do_Post returns the following error: nrecvs not zero, but recv_data = NULL. The full error is in the pastebin and attached to the post: https://pastebin.com/YrLe6XkF

My Trilinos build is untested due to the following build-error: https://github.com/trilinos/Trilinos/issues/2046
I have no problem running .g examples. I cannot provide a list of the make check results for my installation at this moment, however I can tell that I had a 52% test success rate before recompiling Trilinos to add yaml. I will try to update my informations
[zoltan_error.txt](https://github.com/peridigm/peridigm/files/3132414/zoltan_error.txt)
 as soon as possible.

The libraries installed in the system (VM) are the following:
- Ubuntu 18.04
- gcc 4:7.4.0 (apt)
- boost 1.70 (from binaries)
- BLAS 3.7.1 (apt)
- LAPACK 3.7.1 (apt, made sure Trilinos finds dggsvd3)
- doxygen 1.8.3 (apt)
- matio 1.5.15 (from binaries)
- libyaml-cpp-dev 0.5.2 (apt)
- hdf5 1.10.5 (using make https://github.com/peridigm/peridigm/blob/master/doc/HDF5.md)
- netcdf-c-4.6.3 (using make https://github.com/peridigm/peridigm/blob/master/doc/NetCDF.md)
- Trilinos (using cmake 3.14.3 https://github.com/peridigm/peridigm/blob/master/doc/Trilinos.md adding the yaml flag to read .yaml input files and disabling tests).

For the future, should I learn the xml file setup or the yaml file setup? I take the latter is becoming the standard?

Any help is appreciated.

**Comment by johntfoster** [comment]
Can confirm that all Peridigm tests pass?  It's usually not necessary to run the Trilinos tests if all the Peridigm tests pass.

**Comment by marcoprev** [comment]
Before recompiling Trilinos (to include yaml) my Peridigm tests had a 52% success rate. If I remember correctly, the errors were due to the missing yaml library to read some test input and due to exodus.
I currently do not have access to the VM to run the testing procedure again, I will follow up as soon as possible.

**Comment by marcoprev** [comment]
At best, 52% of all Peridigm tests pass, using a VM Clone without yaml installed and running with root privileges. The error appears to be related to parallelization. https://pastebin.com/U8q7ZHt3 Using the same VM, 0% of all tests pass if running without root privileges. 

Meanwhile, using the VM Clone with yaml installed, I get a 25% success rate using root https://pastebin.com/F7PHxRGy, and an higher percentage without root privileges. https://pastebin.com/LQTsHCNz. After attempting to run test 24: ut_frameset_2x2x1_np4, the terminal freezes. If it recovers, all subsequent tests fail. This behavior is not consistent as the terminal sometimes freezes earlier than test 24, and the tests 13 & 14 (Exodus Discretization) change their result between different test attempts (stopping the current with ctlr + c and re-running make test). For example, in the pastebin, the non-parallel attempt fails, while the parallel one passes.

        Start  13: utPeridigm_ExodusDiscretization
 13/198 Test  #13: utPeridigm_ExodusDiscretization ................................***Failed    0.53 sec
        Start  14: utPeridigm_ExodusDiscretization_MPI_np2
 14/198 Test  #14: utPeridigm_ExodusDiscretization_MPI_np2 ........................   Passed    2.65 sec

The both virtual machines have 4 cores. I'm starting to think that the inconsistency might be caused by VM-related issues but I have no way to verify this theory.

**Comment by marcoprev** [comment]
After checking the files, I might have found the source of the problem: having installed some files with root privileges, they are only accessible to root and this conflicts with mpiexec (which does not want room privileges). I will see if fixing this solves the problem.

**Comment by amardahiya** [comment]
Hello, I am also facing the same problem 
```
-- Peridigm
-- version 1.5.0 (Dev)

/home/marvel/peridigm/src/core/Peridigm_BoundaryCondition.cpp:175:

Throw number = 1

Throw test that evaluated to true: nodeSets->find(nodeSetName) == nodeSets->end()

**** Error in DirichletBC::apply(), node set not found: FULL_DOMAIN
```
@johntfoster , only 2 (following) out of 194 tests failed-
```
ut_QuickGrid_loadBal_np8_4x4x4
utPeridigm_ProximitySearch_np5
```
and these tests failed as my machine couldn't provide the required number of threads.
So, it can safely be said all tests passed.
Any help is appreciated.

Thanks
Amar

**Comment by djlittl** [comment]
The FULL_DOMAIN option was recently removed.  You should create a node set that covers the entire domain, and then apply the boundary condition to that node set.

**Comment by amardahiya** [comment]
@djlittl, thank you very much for the information and help.
