### ISSUE TITLE
 SOLVER ERROR : " failed to compute shape tensor "

### ISSUE THREAD

**Issue by Hostudent** [peridigm/peridigm#97]
@MDBrothers @djlittl @johntfoster 
I modeled a suspended body between two plates, one of them is completely fixed and another one is getting close to body step by step.
when I run the peridigm, it gives me this ERROR (without starting simulation) : 
#
****   Error:  CorrespondenceMaterial::initialize() failed to compute shape tensor.
****   Note that all nodes must have a minimum of three neighbors.  Is the horizon too small?
#
is that related to instability of the suspended body?

**Comment by djlittl** [comment]
For the correspondence models, you need a minimum of three non-coplanar neighbors for each node.  Are you sure you have this for all the nodes?

**Comment by Hostudent** [comment]
@djlittl I have already solved this problem by increasing neighbors.
My new problem is that NOX cant solve the system and after 100 iteration in 1st step of loading, it fails.
Does it relate to the suspended body?

**Comment by Hostudent** [comment]
@djlittl Dr Littlewood - Thank you so much. The problem hss been solved by increasing number of neighbors but my new problem that despite of using:

Omit_Bonds_Between_Blocks:"All"

command, I still think that the solver create bonds between suspended body and other blocks around it, because it expands at the begining of the simulation without any external contact force.
Is that possible?
I use NOX with Newton Line Search method as the solver.

**Comment by Hostudent** [comment]
@andrisfreimanis @johnftoster @djlittl
Isn't Contact implemented for NOX solver?
